<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."transaction/journal/"; ?>">Journal Entry</a></li>
   <li class="active">View</li>
</ul>
<div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            </div>
   </div>

<div class="row">
      <div class="col-md-2 pull-right">
          <button class="print btn btn-inverse" type="button" rel="content"><i class="icon-print"></i> Print</button>
          <button class="btn btn-inverse" type="button"  onclick="tableToExcel('content', 'Balance Sheet')"><i class="icon-file-excel"></i> Excel</button>
      </div>

</div> 
<div class="row">
<div class="col-md-12">
                            <div class="square-widget">
                                <div class="widget-head clearfix">
                                    <h4 class="pull-left"><i class="icon-user-4"></i> Journal Transaction Details</h4>
                                </div>
                                <div class="widget-container" style="margin-left:50px;">
                                <div class="row">
                                    <div class="col-md-3">
                                        <strong>Journal No </strong> <br/>
                                        <span><?php echo $this->journal[0]['journal_no']; ?></span>
                                    </div>
                                    <div class="col-md-3"> 
                                        <strong>Branch </strong><br>
                                        <span>
                                        <?php 
                                          if(isset($this->location) && !empty($this->location)) {
                                                foreach ($this->location as $location) {
                                                    if($location['id']==$this->journal[0]['fklocation_id']) {
                                                        echo ucfirst($location['name']);
                                                    }
                                                }
                                            }
                                        ?>
                                        </span>
                                        

                                    </div>
                                    <div class="col-md-3">
                                        <strong>Date </strong> <br/>
                                        <span><?php echo date("d-m-Y",strtotime($this->journal[0]['date'])); ?></span>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Description  </strong><br/>
                                        <span><?php echo $this->journal[0]['description']; ?></span> 
                                    </div>
                                    
                                    
                                </div><br/>
                                <div class="row">

                                  <div class="col-md-3">
                                        <strong>Auto Reversal Date </strong> <br/>
                                        <span>
                                        <?php 
                                          if($this->journal[0]['auto_reversal_date']!=NULL && $this->journal[0]['auto_reversal_date']!='0000-00-00') {
                                            echo date("d-m-Y",strtotime($this->journal[0]['auto_reversal_date'])); 
                                          } else {
                                            echo "Nil";
                                          }
                                        ?>
                                        </span>
                                    </div>

                                  <div class="col-md-3">
                                        <strong>Attachment </strong><br/>
                                        <span>
                                          <?php
                                          if(isset($this->journal[0]['attachment']) && !empty($this->journal[0]['attachment']) && file_exists($this->fileuploadpath.$this->journal[0]['attachment'])) {
                                         ?>
                                         
                                          <a href="<?php echo $this->sitePath.$this->fileuploadpath.$this->journal[0]['attachment']; ?>" target="_blank">Click to view</a> </label>
                                          <?php 
                                          } else {
                                          ?>
                                          No attachments available
                                          <?php 
                                            }
                                          ?>
                                        </span> 
                                    </div>

                                   <div class="col-md-3">
                                        <strong>Approval By / For </strong><br>
                                        <span>
                                        <?php 
                                            if(isset($this->approveUser) && !empty($this->approveUser)) {
                                                foreach ($this->approveUser as $approve) {
                                                  if($approve['account_type']==0) {
                                                        $account_type = "Developer";
                                                  } 
                                                  else if($approve['account_type']==1) {
                                                        $account_type = "Developer";
                                                  } 
                                                  else if($approve['account_type']==2) {
                                                        $account_type = "Super User";
                                                  } else if($approve['account_type']==3) {
                                                        $account_type = "Manager";
                                                  }
                                                  if($approve['id']==$this->journal[0]['approval_for']) {
                                                        echo $approve['username']." - ".$account_type;
                                                  }
                                                }
                                            }
                                        ?>
                                        </span>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Status </strong><br>
                                        <span>
                                        <?php 
                                            if($this->journal[0]['journal_status']==1) {
                                                echo "Approved / Verified";
                                            } else if($this->journal[0]['journal_status']==2) {
                                                echo "Saved / Unverified";
                                            } else if($this->journal[0]['journal_status']==3) {
                                                echo "Draft";
                                            }
                                        ?>
                                        </span>
                                    </div>
                                </div>
                               
                                </div>
                            </div>
                        </div>
                    </div>
<div class="row">
                         <div class="col-md-12">
                            <div class="square-widget">
                                <h5 class="pull-left"><i class="icon-user-4"></i> Journal List Details</h5>
                                <div class="widget-container">
                                    <table class="table responsive">
                                        <thead>
                                               <tr>
                                                <th>
                                                    Account Type
                                                </th>
                                                <th>
                                                    Description
                                                </th>
                                                <th style="text-align:right;">
                                                    Debit
                                                </th>
                                                <th style="text-align:right;">
                                                    Credit
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody id="journal_detail">
                                        <?php
                                            $j=1;
                                            $total_debit  = 0.00;
                                            $total_credit = 0.00;
                                            foreach ($this->journalEntryList  as $journalEntry) {
                                                $total_debit  += $journalEntry['debit'];
                                                $total_credit += $journalEntry['credit'];
                                        ?>
                                             <tr>
                                                <td style="width:20%;">
                                                    <input type="hidden" name="jid_<?php echo $j; ?>" id="jid_<?php echo $j; ?>" value="<?php echo $journalEntry['id']; ?>" />
                                                     
                                                            <?php
                                                                if(isset($this->payAccount) && !empty($this->payAccount)) {
                                                                    foreach ($this->payAccount as $payAccount) {
                                                                        if($journalEntry['fkaccount_id'] == $payAccount['id']) {
                                                                            echo $payAccount['account_name'];
                                                                        }
                                                                    }
                                                                }
                                                            ?>                                                       
                                                </td>
                                               
                                                <td style="width:40%;">
                                                    <?php echo $journalEntry['journal_description']; ?>
                                                </td>
                                                <td style="width:20%; text-align:right; ">
                                                    <?php echo number_format($journalEntry['debit'],2,'.',','); ?>
                                                </td>
                                                 <td style="width:20%; text-align:right; ">
                                                    <?php echo number_format($journalEntry['credit'],2,'.',','); ?>
                                                </td>
                                               
                                            </tr>
                                            <?php 
                                                    $j++;
                                                }
                                            ?>
                                             <tr>
                                              <td colspan="2" style="text-align:right;"><strong>Total</strong></td>
                                              <td style="text-align:right;"><strong><?php echo number_format($total_debit,2,'.',','); ?></strong></td>
                                              <td style="text-align:right;"><strong><?php echo number_format($total_credit,2,'.',','); ?></strong></td>
                                            </tr>
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <hr/>
<!-- 
                        <div class="form-group">
                            <div class="col-lg-12 col-md-offset-5">
                                 <div class="col-lg-2 col-md-offset-1">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Total :</label>
                                 </div>
                                 <div class="col-lg-2">
                                   <label class="col-lg-4 control-label" id="total_debit" style="padding-top:0px;"><?php echo number_format($total_debit,2,'.',','); ?></label>
                                 </div>
                                 <div class="col-lg-2">
                                   <label class="col-lg-4 control-label" id="total_credit" style="padding-top:0px;"><?php echo number_format($total_credit,2,'.',','); ?></label>
                                 </div>
                            </div>

                        </div> -->
                        
                            </div>





<div class="row" id="content" style="display:none;">
                         <div class="col-md-12">
                             <h4 align="center">Journal Transaction <?php echo $this->journal[0]['journal_no']; ?></h4> 
                             <h4 align="center">Date <?php echo date('d-m-Y',strtotime($this->journal[0]['date'])); ?></h4> 
                            <div class="square-widget">
                                <!-- <h5 class="pull-left"><i class="icon-user-4"></i> Journal List Details</h5> -->
                                <div class="widget-container">
                                    <table class="table responsive" align="center" width="100%" cellpadding="5" cellspacing="5" style="width:100%;">
                                        <thead>
                                               <tr>
                                                <th>
                                                    Account Type
                                                </th>
                                                <th>
                                                    Description
                                                </th>
                                                <th style="text-align:right;">
                                                    Debit
                                                </th>
                                                <th style="text-align:right;">
                                                    Credit
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody id="journal_detail">
                                        <?php
                                            $j=1;
                                            $total_debit  = 0.00;
                                            $total_credit = 0.00;
                                            foreach ($this->journalEntryList  as $journalEntry) {
                                                $total_debit  += $journalEntry['debit'];
                                                $total_credit += $journalEntry['credit'];
                                        ?>
                                             <tr>
                                                <td style="width:20%;">
                                                    <input type="hidden" name="jid_<?php echo $j; ?>" id="jid_<?php echo $j; ?>" value="<?php echo $journalEntry['id']; ?>" />
                                                     
                                                            <?php
                                                                if(isset($this->payAccount) && !empty($this->payAccount)) {
                                                                    foreach ($this->payAccount as $payAccount) {
                                                                        if($journalEntry['fkaccount_id'] == $payAccount['id']) {
                                                                            echo $payAccount['account_name'];
                                                                        }
                                                                    }
                                                                }
                                                            ?>                                                       
                                                </td>
                                               
                                                <td style="width:40%;">
                                                    <?php echo $journalEntry['journal_description']; ?>
                                                </td>
                                                <td style="width:20%; text-align:right; ">
                                                    <?php echo number_format($journalEntry['debit'],2,'.',','); ?>
                                                </td>
                                                 <td style="width:20%; text-align:right; ">
                                                    <?php echo number_format($journalEntry['credit'],2,'.',','); ?>
                                                </td>
                                               
                                            </tr>
                                            <?php 
                                                    $j++;
                                                }
                                            ?>
                                            <tr>
                                              <td colspan="2" style="text-align:right;"><strong>Total</strong></td>
                                              <td style="text-align:right;"><strong><?php echo number_format($total_debit,2,'.',','); ?></strong></td>
                                              <td style="text-align:right;"><strong><?php echo number_format($total_credit,2,'.',','); ?></strong></td>
                                            </tr>
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                        <!-- <hr/>

                        <div class="form-group">
                            <div class="col-lg-12 col-md-offset-5">
                                 <div class="col-lg-2 col-md-offset-1">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Total :</label>
                                 </div>
                                 <div class="col-lg-2">
                                   <label class="col-lg-4 control-label" id="total_debit" style="padding-top:0px;"><?php echo number_format($total_debit,2,'.',','); ?></label>
                                 </div>
                                 <div class="col-lg-2">
                                   <label class="col-lg-4 control-label" id="total_credit" style="padding-top:0px;"><?php echo number_format($total_credit,2,'.',','); ?></label>
                                 </div>
                            </div>

                        </div> -->
                        
                            </div>
<script type="text/javascript">
  (function ($) {
  var rules = document.styleSheets[document.styleSheets.length-1].cssRules;
  for (var idx = 0, len = rules.length; idx < len; idx++) {
    $(rules[idx].selectorText).each(function (i, elem) {
      elem.style.cssText += rules[idx].style.cssText;
    });
  }
  $('style').remove();
})(jQuery);

var tableToExcel = (function() {
  var uri = 'data:application/vnd.ms-excel;base64,'
    , template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>'
    , base64 = function(s) { return window.btoa(unescape(encodeURIComponent(s))) }
    , format = function(s, c) { return s.replace(/{(\w+)}/g, function(m, p) { return c[p]; }) }
  return function(table, name) {
    if (!table.nodeType) table = document.getElementById(table)
    var ctx = {worksheet: name || 'Worksheet', table: table.innerHTML}
    window.location.href = uri + base64(format(template, ctx))
  }
})()
</script>

