<?php
  $logSession = new Zend_Session_Namespace('sess_login');

  function convertCurrency($amount, $from){
    $to   = 'SGD';
    $url  = "https://www.google.com/finance/converter?a=$amount&from=$from&to=$to";
    $data = file_get_contents($url);
    preg_match("/<span class=bld>(.*)<\/span>/",$data, $converted);
    $converted = preg_replace("/[^0-9.]/", "", $converted[1]);
    return round($converted, 3);
  }
?>
<div id="popup">
<span class="button b-close"><span>X</span></span>
<div class="row" id="add_receipt" style="display:none;">
<h4>Add Receipts</h4>
<div class="widget-container col-md-12 col-md-offset-1">
 <form class="form-horizontal" id="add-receipt" method="post">
<div class="form-group">
    <label class="control-label col-lg-4">Receipts <span class="mandatory">*</span></label>
      <div class="col-lg-5" id="receipt_add">
            <p>No Receipts Found</p>
      </div>
</div>
   <div class="form-group">
        <div class="col-lg-8 col-lg-offset-3">
            <div class="form-actions">
               <input type="button" name="attach_receipts" class="btn btn-primary " id="attach_receipts" value="Attach Receipt" onclick="return addReceipt();" />
                <button type="reset" class="btn" onclick="return bPopup_close();">Cancel</button>
            </div>
        </div>
     </div>
</form>
</div>
</div>

<div class="row" id="add_payment" style="display:none;">
 <h4>Add Payment</h4>
<div class="widget-container col-md-12 col-md-offset-1">
 <form class="form-horizontal" id="add-payment" method="post">
    <div class="form-group">
      <label class="control-label col-lg-4">Payment Date <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <input type="hidden" name="expense_id" id="expense_id" />
            <input type="hidden" name="currency_status" id="currency_status" />
            <input type="text" name="date" id="date" class="form-control date-pick" placeholder="Select Date"  autocomplete="off" value="<?php echo date('d-m-Y'); ?>" />
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Cash / Bank Account <span class="mandatory">*</span></label>
        <div class="col-lg-5">
             <select class="form-control" name="pay_account" id="pay_account">
                <option value="">Select</option>
                    <?php
                        /*if(isset($this->payAccount) && !empty($this->payAccount)) {
                            foreach ($this->payAccount as $payAccount) {*/
                    ?>
                        <!-- <option value="<?php echo $payAccount['id']; ?>"><?php echo $payAccount['account_name']; ?></option> -->
                    <?php
                          /*  }
                        }*/
                    ?>                                                       
              </select>
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Amount <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <input type="text" name="pay_amount" id="pay_amount" class="form-control amount-align" placeholder="Enter Amount"  autocomplete="off"  onchange="return numberWithCommasInput(this.value,this.id);" />
            <input type="hidden" name="pending_amount" id="pending_amount" class="form-control" autocomplete="off"   />
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Payment Method <span class="mandatory">*</span></label>
        <div class="col-lg-5">
          <select name="pay_method" id="pay_method" class="form-control">
            <option value="">Select</option>
           <?php 
                foreach ($this->payMethod as $key => $pay) {
           ?>
                <option value="<?php echo $key; ?>"><?php echo $pay; ?></option>
           <?php
                }
           ?>
          </select>
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Bank Cheque / Draft No </label>
        <div class="col-lg-5">
            <input type="text" name="cheque_draft_no" id="cheque_draft_no" class="form-control" placeholder="Enter Cheque / Draft No"  autocomplete="off"  />
        </div>
    </div>
     <div class="form-group">
      <label class="control-label col-lg-4">Prompt Payment Discount <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <select class="form-control" name="payment_discount" id="payment_discount" onchange="discountAddPayment(this.value);">
                <option value="1">Yes</option>
                <option value="2" selected>No</option>
            </select>
        </div>
    </div>
     <div class="form-group">
      <label class="control-label col-lg-4">Discount Amount <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <input type="text" name="discount_payment_amount" id="discount_payment_amount" class="form-control amount-align" value="0" disabled  autocomplete="off" onchange="return numberWithCommasInput(this.value,this.id);" />
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Additional Description / Notes </label>
        <div class="col-lg-5">
        <textarea name="description" id="description" class="form-control"></textarea>
        </div>
    </div>

     <div class="form-group">
      <label class="control-label col-lg-8"><input type="checkbox" name="payment_status" id="payment_status" value="1" /> <span>Check this to confirm the full payment received</span> </label>
        
    </div>

     <div class="form-group">
        <div class="col-lg-8 col-lg-offset-3">
            <div class="form-actions">
               <input type="submit" name="add_payment" class="btn btn-primary " id="add_payment" value="Add Payment" />
                <button type="reset" class="btn" onclick="return bPopup_close();">Cancel</button>
            </div>
        </div>
     </div>

</form>
</div>
</div>
</div>

<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li class="active">Expense</li>
</ul>

  
  <div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            <div class="alert alert-success" id="success" style="display:none;">
            </div>
            <div class="alert alert-danger" id="failure" style="display:none;">
            </div>
            </div>
   </div>
   <?php
     if(!empty($_GET['location']) && $_GET['location']) { 
         $show_filter = 'display:none;';
          $hide_filter = '';
      } else {   
           $show_filter = '';
          $hide_filter = 'display:none;';
          
      }
    $logSession = new Zend_Session_Namespace('sess_login');
   ?>
   <?php 
        if($logSession->type!=5 && $logSession->proxy_type!=5) {
   ?>
   <div class="row">
       <div class="col-md-12 grid-spacing">
       <a href="javascript:void(0)" class="btn btn-primary" type="button" onclick="showExpense();">Add Expense</a>
        <a href="javascript:void(0)" class="btn btn-primary" id="show_filter" style="<?php echo $show_filter; ?>" type="button">Show Filters</a>
       <a href="javascript:void(0)" class="btn btn-primary" id="hide_filter" type="button" style="<?php echo $hide_filter; ?>">Hide Filters</a>
            <!-- Element to pop up -->    
       </div>
   </div>

     <div class="row" id="add_expense" style="display:none;">


                        <div class="col-md-12 widget-module">

                            <div class="square-widget widget-collapsible">
                                <div class="widget-head clearfix">
                                    <h4 class="pull-left"><i class="icon-paragraph-justify-2"></i> New Expense Transaction</h4>
                                </div>

                                <div class="widget-container col-md-12">
                                <form class="form-horizontal" id="add-expense" method="post" enctype="multipart/form-data">
                                        <div class="form-group">

                                            <div class="col-lg-2">
                                             <label>Branch <span class="mandatory">*</span></label>
                                                <select class="select2" name="location" id="location" required>
                                                <!-- <option value="">Select</option> -->  
                                                     <?php
                                                        if(isset($this->location) && !empty($this->location)) {
                                                            foreach ($this->location as $location) {
                                                              if($location['is_default']==1) {
                                                                $locationSelect = 'selected';
                                                              } else {
                                                                $locationSelect = '';
                                                              }
                                                    ?>
                                                        <option value="<?php echo $location['id']; ?>" <?php echo $locationSelect; ?>><?php echo ucwords($location['name']); ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                      
                                                </select>
                                            </div> 

                                            <div class="col-lg-3">
                                              <label>Date <span class="mandatory">*</span></label>
                                                <input type="text" name="date" id="exp-date" class="form-control date-pick" placeholder="Select Date" value="<?php if(isset($this->date) && !empty($this->date)) { echo $this->date; } else { echo date('d-m-Y'); } ?>"  autocomplete="off" onchange="return creditSelect();" />
                                            </div>
                                             
                                            <div class="col-lg-3">
                                            <label>Receipt No <span class="mandatory">*</span></label>
                                                <input type="text" name="receipt" id="receipt" class="form-control" placeholder="Enter Receipt No"  autocomplete="off" value="<?php if(isset($this->receipt) && !empty($this->receipt)) { echo $this->receipt; } ?>" onchange="checkReceipt(this.value);">
                                                <label for="receipt" generated="true" class="error receipt_error" style="display:none;"></label>
                                            </div>    
                                            <div class="col-lg-2">
                                             <label>Vendor Name <span class="mandatory">*</span> <a href="javascript:void(0)" title="Refresh List" data-title="Refresh List" target="_blank" onclick="return refreshList(1);" class="vendor-refresh" style="margin-left:0px;"><i class="icon-refresh"></i></a></label>
                                             <div id="vendorRefresh">
                                                <select class="select2" name="vendor" id="vendor">
                                                    <option value="">Select</option>
                                                    <?php
                                                      $vendorSelect = '';
                                                        if(isset($this->vendor) && !empty($this->vendor)) {
                                                            foreach ($this->vendor as $vendor) {
                                                              $coa = $vendor['coa_link'];
                                                              if(isset($this->vendor) && !empty($this->vendor)) {
                                                                if($this->vendorid==$vendor['id'])
                                                                  $vendorSelect = 'selected';
                                                                else
                                                                  $vendorSelect = '';
                                                            }
                                                    ?>
                                                        <option value="<?php echo $vendor['id']; ?>" <?php echo $vendorSelect; ?> data-coa='<?php echo $coa; ?>'><?php echo $vendor['vendor_name']; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                    
                                                </select>
                                                </div>
                                                <?php 
                                                      if($logSession->type!= 5 && $logSession->proxy_type!=5) {
                                                 ?>
                                                <a href="<?php echo $this->sitePath."business/vendor/add"; ?>" title="Click to add new vendor" data-title="Click to add new vendor" target="_blank" id="add-vendor"><i class="icon-plus-circle-2"></i> Add New Vendor</a>
                                                <?php
                                                      }
                                                ?>
                                            </div> 

                                            
                                          

                                          <div class="col-lg-2">
                                             <label>Currency <span class="mandatory">*</span></label>
                                                <select class="select2" name="currency" id="currency" onchange="return calculateTotal();">
                                                <option value="">Select</option>  
                                                     <?php
                                                     $currencySelect = '';
                                                        if(isset($this->currencies) && !empty($this->currencies)) {
                                                            foreach ($this->currencies as $key => $currency) {
                                                                if(isset($this->currencyid) && !empty($this->currencyid)) {
                                                                if($this->currencyid==$key)
                                                                 $currencySelect = 'selected';
                                                                else
                                                                  $currencySelect = '';
                                                              } else {
                                                                if($key=='SGD') 
                                                                    $currencySelect = "selected";
                                                                else
                                                                    $currencySelect = "";
                                                              }
                                                    ?>
                                                        <option value="<?php echo $key; ?>" <?php echo $currencySelect; ?>><?php echo $currency; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                      
                                                </select>
                                            </div> 
                                           
                                         


                                           
                                        </div>

                                        <div class="form-group">


                                        <div class="col-lg-2">
                                             <label>Credit Term <span class="mandatory">*</span></label>
                                                <select class="form-control" name="credit_term" id="credit_term" onchange="return creditSelect();">
                                                    <?php
                                                        $days = '';
                                                        $creditSelect = '';
                                                        if(isset($this->creditTerm) && !empty($this->creditTerm)) {
                                                            foreach ($this->creditTerm as $key => $credit) {
                                                                if($key!=1) {
                                                                    $credits = $credit." Days";
                                                                } else {
                                                                    $credits = $credit;
                                                                }
                                                                if(isset($this->credit_term) && !empty($this->credit_term)) {
                                                                  if($this->credit_term==$key) {
                                                                    if($key!=1) {
                                                                        $days = $credit;
                                                                    } 
                                                                    $creditSelect = 'selected';
                                                                  }
                                                                  else {
                                                                    $creditSelect = '';
                                                                  }
                                                                } else if($this->creditSet==$key) {
                                                                    if($key!=1) {
                                                                        $days = $credit;
                                                                    } 
                                                                    $creditSelect = 'selected';
                                                                }
                                                                else {
                                                                    $creditSelect = '';
                                                                }
                                                    ?>
                                                        <option value="<?php echo $key; ?>" <?php echo $creditSelect; ?>><?php echo $credits; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                        
                                                </select>
                                            </div> 


                                            <div class="col-lg-2">
                                              <label>Due Date </label>
                                               <?php
                                               if(isset($this->due_date) && !empty($this->due_date)) { 
                                                  $due_date = $this->due_date;
                                               } else {
                                                  if(isset($days) && $days!='' && !empty($days)) {
                                                    $cur_date = date('d-m-Y');
                                                    $mod_date = strtotime($cur_date."+ ".$days." days");
                                                    $due_date = date('d-m-Y',$mod_date);
                                                   } else {
                                                    $due_date = date('d-m-Y');
                                                   // $mod_date = strtotime($cur_date."+ 15 days");
                                                  //  $due_date = date('d-m-Y',$mod_date);
                                                   }
                                                 }
                                              ?>
                                                <input type="text" name="due_date" id="due_date" class="form-control date-pick" placeholder="Select Date" value="<?php echo $due_date; ?>"  autocomplete="off" />
                                            </div>


                                    
                                            <div class="col-lg-2">
                                              <label>Prompt Payment Discount <span class="mandatory">*</span></label>
                                                <select class="form-control" name="payment_discount" id="payment_discount">
                                                  <?php
                                                    if(isset($this->discount) && !empty($this->discount)) {
                                                        if($this->discount==1) { 
                                                  ?>
                                                    <option value="1" selected>Yes</option>  
                                                    <option value="2">No</option>  
                                                  <?php
                                                        } else if($this->discount==2) { 
                                                  ?>
                                                    <option value="1">Yes</option>  
                                                    <option value="2">No</option>  
                                                  <?php 
                                                        }
                                                    } else {
                                                  ?>
                                                     <option value="1">Yes</option>  
                                                     <option value="2" selected>No</option>  
                                                  <?php 
                                                    }
                                                  ?>
                                                </select>
                                            </div>

                                           

                                             <div class="col-lg-2 ">
                                              <label>Permit No <span class="mandatory">*</span></label>
                                                <input type="text" name="permit_no" id="permit_no" class="form-control" placeholder="Enter Permit No"  autocomplete="off" value="<?php if(isset($this->permit) && !empty($this->permit)) { echo $this->permit; } ?>" />
                                            </div>

                                             <div class="col-lg-2 ">
                                              <label>D.O / S.O No </label>
                                                <input type="text" name="do_so_no" id="do_so_no" class="form-control" placeholder="Enter D.O / S.O No"  autocomplete="off" value="<?php if(isset($this->do_so_no) && !empty($this->do_so_no)) { echo $this->do_so_no; } ?>" />
                                            </div>

                                        </div>

                        <div class="col-md-12">
                            <div class="square-widget">
                                
                                <div class="widget-container">
                                    <table class="table responsive">
                                        <thead>
                                            <tr>
                                            <th style="width:2%;"></th>
                                                <th>
                                                    Expense Type <a href="javascript:void(0)" title="Refresh List" data-title="Refresh List" target="_blank" class="expenseaccount-refresh" onclick="return refreshExpenseList();" style="margin-left:0px;"><i class="icon-refresh"></i></a>
                                                </th>
                                                <th>
                                                    Product ID
                                                </th>
                                                <th>
                                                    Product Description
                                                </th>
                                                <th>
                                                    Quantity
                                                </th>
                                                <th>
                                                    Unit Price
                                                </th>
                                                <th>
                                                    Tax Code
                                                </th>
                                                <th style="text-align:center;">
                                                    GST
                                                </th>
                                                <th style="text-align:center;">
                                                    Amount
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody id="expense_detail">
                                       
                                            <tr>
                                            <td style="width:2%"></td>
                                                <td style="width:20%;">
                                                <input type="hidden" name="expense_counter" id="expense_counter" value="1" /><br/>
                                                <div id="expenseRefresh1">
                                                   <select class="form-control" name="expense_type_1" id="expense_type_1" required>
                                                    <option value="">Select</option>    
                                                    <?php
                                                        $accountType = array();
                                                        if(isset($this->expenseAccount) && !empty($this->expenseAccount)) {
                                                            foreach ($this->expenseAccount as $expense) {
                                                              if(!in_array($expense['account_type'], $accountType)) {
                                                                if($expense['account_type']==1) {
                                                                  echo '<optgroup label="Assets">';
                                                                } else if($expense['account_type']==2) {
                                                                 echo '<optgroup label="Liability / Credit Card">';
                                                                } else if($expense['account_type']==3) {
                                                                 echo '<optgroup label="Income">';
                                                                } else if($expense['account_type']==4) {
                                                                 echo '<optgroup label="Expense">';
                                                                } else if($expense['account_type']==5) {
                                                                 echo '<optgroup label="Equity">';
                                                                }
                                                                $accountType[] = $expense['account_type'];
                                                              }
                                                    ?>
                                                        <option value="<?php echo $expense['id']; ?>"><?php echo $expense['account_name']; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                      
                                                </select>
                                                </div>
                                                <?php 
                                                      if($logSession->type!= 5 && $logSession->proxy_type!=5) {
                                                 ?>
                                                <a href="<?php echo $this->sitePath."settings/account"; ?>" class="add-expenseaccount" title="Click to add new expense" data-title="Click to add new expense" target="_blank" onclick="expenseAccountRefresh();"><i class="icon-plus-circle-2"></i> Add New Expense</a>  &nbsp; 
                                                <?php 
                                                      }
                                                ?>
                                                </td>
                                                <td style="width:10%;">
                                                    <input type="text" name="product_id_1" id="product_id_1" class="form-control" placeholder="Product ID"  autocomplete="off" />
                                                </td>
                                                <td style="width:20%;">
                                                    <input type="text" name="product_description_1" id="product_description_1" class="form-control" placeholder="Enter Product Description" required  autocomplete="off" />
                                                </td>
                                                <td style="width:7%;">
                                                    <input type="text" name="quantity_1" id="quantity_1" class="form-control" required number="true" minlength="1" maxlength="5" onkeyup="return calculateTotal();" pattern="[0-9]{1,5}" title="Whole numbers only"  autocomplete="off" />
                                                </td>
                                                <td style="width:10%;">
                                                    <input type="text" name="price_1" id="price_1" class="form-control amount-align" required number="true" onkeyup="return calculateTotal();"  autocomplete="off" onchange="return numberWithCommasInput(this.value,this.id);" />
                                                </td>
                                                <td style="width:12%;">
                                                    <select class="form-control" name="tax_code_1" id="tax_code_1" required  onchange="return calculateTotal();">
                                                    <option value="">Select</option>    
                                                    <option value="0" title="Not Applicable">NA</option>  
                                                    <?php
                                                        if(isset($this->taxCode) && !empty($this->taxCode)) {
                                                            foreach ($this->taxCode as $tax) {
                                                              foreach ($this->purchase as $key => $purchase) {
                                                                if($tax['tax_code']==$key) {
                                                                    $code = $purchase['name'];
                                                                }
                                                              }

                                                    ?>
                                                        <option value="<?php echo $tax['id']."_".$tax['tax_percentage']; ?>"  title="<?php echo ucfirst(str_replace("\r\n", " ", $tax['description'])); ?>"><?php echo $code." - ".$tax['tax_percentage']." %"; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                  
                                                </select>
                                                </td>
                                                 <td style="width:10%;">
                                                    <input type="text" name="gst_amount_1" id="gst_amount_1" class="form-control amount-align" value="0.00" onkeyup="return calculateGstTotal();"  required number="true"  autocomplete="off" onchange="return numberWithCommasInput(this.value,this.id);" readonly />
                                                </td>
                                                <td style="text-align:right; padding-right:20px;">
                                                    <strong id="net_amount_1"></strong>
                                                </td>
                                            </tr>

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <hr/>
                        <div class="form-group">
                            <div class="col-lg-4 col-md-offset-10">
                              <div class="form-group">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Sub Total :</label>
                                   <div class="col-lg-4">
                                    <span id="sub_total"></span>
                                </div>
                             </div>
                             <div class="form-group">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Total GST :</label>
                                   <div class="col-lg-4">
                                    <span id="total_gst"></span>
                                </div>
                             </div>
                             <div class="form-group">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Grand Total :</label>
                                   <div class="col-lg-4">
                                    <span id="grand_total"></span>
                                </div>
                             </div>
                             <div class="form-group">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Exchange Rate :</label>
                                   <div class="col-lg-4">
                                    <input type="text" name="exchange_rate" id="exchange_rate" class="form-control" style="width:65%; height:30px;" number="true" onchange="return originalRate(this.value);" autocomplete="off" />
                                    
                                </div>
                             </div>
                             <div class="form-group">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">SGD GST :</label>
                                   <div class="col-lg-4">
                                    <input type="text" name="total_gst_rate" id="total_gst_rate" class="form-control" style="width:65%; height:30px;" number="true" autocomplete="off" onkeyup="return gstRate(this.value);" />
                                    
                                </div>
                             </div>
                             <div class="form-group">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Grand Total SGD :</label>
                                   <div class="col-lg-4">
                                    <input type="hidden" name="foreign_currency" id="foreign_currency" />
                                    <input type="hidden" name="sub_total_sgd" id="sub_total_sgd" />
                                    <span id="grand_total_sgd"></span>
                                </div>
                             </div>

                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-lg-3">
                                <a href="javascript:void(0)" id="expense_row" class="btn btn-primary green" type="button">Add Row</a>
                            </div>
                        </div>

                            <br/>


                    <div class="form-group">
                     <div class="col-lg-3">
                     <label>Attach Invoice or Receipt </label><br/>
                        <!-- <input type="file" name="file" id="file" class="btn" /> -->
                        <input type="button" class="btn btn-info" value="Choose File" id="file" name="file">
                     </div>
                      <div class="col-lg-3 attach_file" style="display:none;">
                       <label>Attached File : </label> <br/>
                       <input type="hidden" name="attached_file" id="attached_file" />
                         <div class="view_remove_file" style="display:none;">
                          
                         </div>
                     </div>

                    </div>

                  <div class="row">
                  <div class="col-lg-2">
                    <div class="progress progress-striped active" id="progress-bar" style="display:none;">
                        <div style="width: 100%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="10" role="progressbar" class="progress-bar progress-bar-success">
                            <span class="sr-only"></span>
                        </div>
                    </div>
                  </div>
                  </div>


<div class="row" id="trigger_payment" style="display:none;">
 <h4>Add Payment</h4>
    <div class="form-group">
     
        <div class="col-lg-2">
         <label>Payment Date <span class="mandatory">*</span></label>
            <input type="text" name="addpay_date" required id="addpay_date" class="form-control date-pick" placeholder="Select Date"  autocomplete="off" value="<?php echo date('d-m-Y'); ?>" />
        </div>
      
        <div class="col-lg-3">
        <label>Cash / Bank Account <span class="mandatory">*</span></label>
             <select class="form-control" name="addpay_pay_account" id="addpay_pay_account" required>
               <!-- <optgroup label="Cash and Cash Equivalents"> -->
                    <?php
                        if(isset($this->cashAccount) && !empty($this->cashAccount)) {
                            foreach ($this->cashAccount as $cash) {
                    ?>
                        <option value="<?php echo $cash['id']; ?>"><?php echo $cash['account_name']; ?></option>
                    <?php
                            }
                        }
                    ?>     
                </optgroup>    
                                                                     
              </select>
        </div>
     
        <div class="col-lg-2">
         <label>Amount <span class="mandatory">*</span></label>
            <input type="text" name="addpay_pay_amount" id="addpay_pay_amount" class="form-control amount-align" required number="true" autocomplete="off"  onchange="return numberWithCommasInput(this.value,this.id);"  />
            <input type="hidden" name="addpay_pending_amount" id="addpay_pending_amount" class="form-control" autocomplete="off"   />
        </div>

      
        <div class="col-lg-2">
        <label>Payment Method <span class="mandatory">*</span></label>
          <select name="addpay_pay_method" id="addpay_pay_method" class="form-control" required>
            <option value="">Select</option>
           <?php 
                foreach ($this->payMethod as $key => $pay) {
           ?>
                <option value="<?php echo $key; ?>"><?php echo $pay; ?></option>
           <?php
                }
           ?>
          </select>
        </div>

        <div class="col-lg-2">
         <label>Bank Cheque / Draft No </label>
            <input type="text" name="addpay_cheque_draft_no" id="addpay_cheque_draft_no" class="form-control" placeholder="Enter Cheque / Draft No"  autocomplete="off"  />
        </div>
    </div>
    <div class="form-group">
     
        <div class="col-lg-2">
        <label>Prompt Payment Discount <span class="mandatory">*</span></label>
            <select class="form-control" name="addpay_payment_discount" id="addpay_payment_discount" onchange="discountTriggerPayment(this.value);">
                <option value="1">Yes</option>  
                <option value="2" selected>No</option>  
            </select>
        </div>

      
        <div class="col-lg-2">
        <label>Discount Amount <span class="mandatory">*</span></label>
            <input type="text" name="addpay_discount_payment_amount" id="addpay_discount_payment_amount" class="form-control amount-align" value="0" disabled  autocomplete="off"  onchange="return numberWithCommasInput(this.value,this.id);" />
        </div>

      
        <div class="col-lg-6">
        <label>Additional Description / Notes </label>
        <textarea name="addpay_description" id="addpay_description" class="form-control"></textarea>
        <input type="hidden" name="payment_trigger" id="payment_trigger" value="0" />
        </div>

    <div class="col-lg-3">
      <label><input type="checkbox" name="add_payment_status" id="add_payment_status" value="1" /> <span>Check this to confirm the full payment received</span> </label>
        
    </div>

    </div>


</div>
                    


                                   <div class="form-group">
                                    <div class="col-lg-1">
                                         <div class="form-actions">
                                            <input type="hidden" name="action" id="action" value="save_draft_expense" />
                                            <input type="button" name="save_draft_expense" class="btn btn-primary" id="save_draft_expense" value="Save as Draft" onclick="return saveDraft();" /><br/>
                                            <i>Save Draft Expense</i>
                                          </div>
                                      </div>
                                        <div class="col-lg-3" style="margin-left:10px;">
                                        <div class="form-actions">
                                            <select class="form-control" name="approval_for" id="approval_for">
                                            <option value="">For Approval</option>
                                                        <?php
                                                            if(isset($this->approveUser) && !empty($this->approveUser)) {
                                                                foreach ($this->approveUser as $approve) {
                                                                  if($approve['account_type']==2) {
                                                                     $account_type = "Super User";
                                                                  } else if($approve['account_type']==3) {
                                                                     $account_type = "Manager";
                                                                  }
                                                                  if($approve['account_type']==3 && ($approve['id']==$logSession->id || $approve['id']==$logSession->proxy_id)) {
                                                                     } else {
                                                        ?>
                                                            <option value="<?php echo $approve['id']; ?>" ><?php echo $approve['username']." - ".$account_type; ?></option>
                                                        <?php
                                                                  }
                                                                }
                                                            }
                                                        ?>                                                      
                                                    </select>
                                          </div>
                                          
                                      </div>
                                       <div class="col-lg-1" style="margin-left:10px;">
                                         <div class="form-actions">
                                            <input type="submit" name="unapprove_save" class="btn btn-primary add_approve_expense_transaction" id="unapprove_save_expense" value="For Approval" /><br/>
                                            <i>Save Expense for approval</i>
                                          </div>
                                      </div>
                                      <?php 
                                              if($logSession->type!=4 && $logSession->proxy_type!=4) {
                                      ?>
                                       <div class="col-lg-1" style="margin-left:10px;">
                                         <div class="form-actions">
                                            <input type="submit" name="approve_expense" class="btn btn-primary add_expense_transaction" id="approve_expense" value="Approve" /><br/>
                                            <i>Approve Expense for account posting</i>
                                            </div>
                                         </div>
                                      <?php
                                            }
                                      ?>
                                         <div class="col-lg-1" style="margin-left:0px;">
                                         <div class="form-actions">
                                            <button type="reset" class="btn"  onclick="return hideExpense();">Cancel</button>
                                            </div>
                                         </div>
                                    </div>

                                </form>
                                    
                                </div>
                            </div>
                        </div>
                    </div>

               
   <?php 
        }
    ?>

<div class="row" id="filters_id" style="<?php echo $hide_filter; ?>">
    <div class="col-md-12">

      <form class="form-horizontal" id="filter-by" method="get" novalidate="novalidate">
        <div class="form-group">

          <label class="col-lg-5 control-label">Branch </label>
          <div class="col-lg-3">
               <select class="form-control" name="location" id="locations" required>
<!--                   <option value="all" <?php if($this->setlocation=='all') { echo "selected"; } ?>>All Branch</option>
 -->                  <?php
                     if(isset($this->locations) && !empty($this->locations)) {
                        foreach ($this->locations as $location) {
                          if(isset($this->setlocation) && !empty($this->setlocation)) {
                            if($location['id']==$this->setlocation) {
                                 $locationSelect = 'selected';
                              } else {
                                 $locationSelect = '';
                              }
                          } else {
                             if($location['is_default']==1) {
                                 $locationSelect = 'selected';
                              } else {
                                 $locationSelect = '';
                              }
                          }
                  ?>
                        <option value="<?php echo $location['id']; ?>" <?php echo $locationSelect; ?>><?php echo ucwords($location['name']); ?></option>
                   <?php
                          }
                        }
                   ?>                                                      
                 </select>
          </div>

        </div>


        <div class="form-group">

          <label class="col-lg-5 control-label">Financial Year </label>
          <div class="col-lg-3">
               <select class="form-control" name="financial_year" id="financial_year" required>
                  <option value="all" <?php if($this->setfinance=='all') { echo "selected"; } ?>>All Financial Year</option>
                  <?php
                     $financeSelect = '';
                     if(isset($this->finance) && !empty($this->finance)) {
                        foreach ($this->finance as $finance) {
                          $start = date('d-m-Y',strtotime($finance['financial_start']));
                          $end   = date('d-m-Y',strtotime($finance['financial_end']));
                          if(isset($this->setfinance) && !empty($this->setfinance)) {
                            if($finance['id']==$this->setfinance) {
                                 $financeSelect = 'selected';
                              } else {
                                 $financeSelect = '';
                              }
                          } else {
                             if($finance['id']==$this->checkFinance) {
                                 $financeSelect = 'selected';
                              } else {
                                 $financeSelect = '';
                              }
                          }
                  ?>
                        <option value="<?php echo $finance['id']; ?>" <?php echo $financeSelect; ?>><?php echo $start." to ".$end; ?></option>
                   <?php
                          }
                        }
                   ?>                                                      
                 </select>
          </div>

        </div>


        <div class="form-group">
         <label class="col-lg-5 control-label">&nbsp;</label>
           <div class="col-lg-3">
              <div class="form-actions">
                <button type="submit" id="update" class="btn btn-primary">Filter</button>
                <a class="btn btn-default" href="<?php echo $this->sitePath."transaction/expense" ?>">
                Cancel</a>
              </div>
           </div>
        </div>
      </form>

    </div>
  </div>
 <div class="row">
                <div class="col-md-12">
                          <h5 style="text-align:right;">
                            <strong>Sort By:</strong>
                            <a href="<?php echo $this->sitePath."transaction/expense" ?>" class="btn btn-primary" type="button"><?php if(isset($this->sort) && $this->sort=='') { ?><i class="icon-ok"><?php } ?></i> All</a>
                            <a href="<?php echo $this->sitePath."transaction/expense/index/sort/1" ?>" class="btn btn-primary" type="button"><?php if(isset($this->sort) && $this->sort==1) { ?><i class="icon-ok"><?php } ?></i> Verified</a>
                             <a href="<?php echo $this->sitePath."transaction/expense/index/sort/2" ?>" class="btn btn-primary" type="button"><?php if(isset($this->sort) && $this->sort==2) { ?><i class="icon-ok"><?php } ?></i> Unverified</a>
                             </h5>
                        </div>

                        <div class="col-md-12">
                            <div class="box-widget">
                                <table class="table responsive" id="expense-table">
                                    <thead>
                                        <tr>
                                            <th>
                                                Date
                                            </th>
                                            <th style="display:none;">Sortable Date</th>
                                            <th>
                                                Receipt No
                                            </th>
                                            <th>
                                                Expense Type
                                            </th>
                                            <th>
                                                Branch
                                            </th>
                                            <th>
                                                Vendor
                                            </th>
                                            <th style="text-align:center;">
                                               Amount Due
                                            </th>
                                            <th style="text-align:center;">
                                               Total Amount
                                            </th>
                                            <th style="text-align:center;">
                                                Actions
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody id="expense_detail">
                                    <?php 
                                        if(isset($logSession->proxy_type) && !empty($logSession->proxy_type)) {
                                          $user_type = $logSession->proxy_type;
                                        } else {
                                          $user_type = $logSession->type;
                                        }
                                        $i=1;
                                        foreach($this->result as $results) {
                                           $expense_name        = '';
                                           $product_description = '';
                                           $pay_amount = 0.00;
                                           $coa_link = $results['coa_link'];
                                            foreach ($this->payments as $pay) {
                                              if($pay['fkiei_id']==$results['id']) {
                                                  $pay_amount += $pay['payment_amount']+$pay['discount_amount'];
                                              }
                                            }
                                            foreach ($this->maximumExpense as $key => $max) {
                                                if($key==$results['id']) {
                                                    $expense_name        = $max['account_name'];
                                                    $product_description = $max['product_description'];
                                                }
                                            }
                                            /*if($results['total_gst']!=0.00) {
                                              $total_amount   = $results['amount'] + $results['total_gst'];
                                            } else {
                                              $total_amount   = $results['amount'] + $results['tax_amount'];
                                            }*/

                                            $fixedAssets = 0;
                                            if(isset($this->fixedExpense) && !empty($this->fixedExpense)) {
                                              foreach ($this->fixedExpense as $fixedExpense) {
                                                if($fixedExpense['exp_id']==$results['id']) {
                                                  $fixedAssets = 1;
                                                }
                                              }
                                            }
                                            
                                            if($results['transaction_currency']!='SGD') {
                                              if($results['total_gst']!=0.00) {
                                                $total_amount   = $results['amount'];
                                                $converted_amount = ($results['exchange_rate']*$total_amount)+$results['total_gst'];
                                              } else {
                                                $total_amount   = $results['amount'] + $results['tax_amount'];
                                                $converted_amount = $results['exchange_rate']*$total_amount;
                                              }
                                               
                                               $pay_status = 2;
                                            } else {
                                              $total_amount   = $results['amount'] + $results['tax_amount'];
                                              $converted_amount = $total_amount;
                                              $pay_status = 1;
                                            }
                                            $pending_amount = $converted_amount - $pay_amount;
                                    ?>
                                        <tr>
                                        <td style="width:7%;"><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['transaction_status']; ?>','<?php echo $user_type; ?>')"><?php echo date("d-m-Y",strtotime($results['date'])); ?></a></td>
                                        <td style="display:none;"><?php echo date("Ymd",strtotime($results['date'])); ?></td>
                                        <td style="width:10%;"><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['transaction_status']; ?>','<?php echo $user_type; ?>')"><?php echo $results['receipt_no']; ?></a></td>
                                        <td style="width:15%;"><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['transaction_status']; ?>','<?php echo $user_type; ?>')"><?php echo $expense_name; ?></a></td>
                                        <td style="width:15%;"><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['transaction_status']; ?>','<?php echo $user_type; ?>')"><?php echo ucwords($results['location']); ?></a></td>
                                        <td style="width:12%;"><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['transaction_status']; ?>','<?php echo $user_type; ?>')"><?php echo ucfirst($results['vendor_name']); ?></a></td>
                                        <td style="width:10%; text-align:right; padding-right:20px;"><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['transaction_status']; ?>','<?php echo $user_type; ?>')"><?php if($results['payment_status']==1) { echo "Nil"; } else { echo number_format($pending_amount,2,'.',','); } ?></a></td>
                                        <td style="width:10%; text-align:right; padding-right:20px;"><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['transaction_status']; ?>','<?php echo $user_type; ?>')"><?php echo number_format($converted_amount,2,'.',','); ?></a></td>
                                        <td class="action-bar" style="width:10%; padding-left: 35px;">

                                        <div class="btn-group col-md-1">
                                    <button data-toggle="dropdown" class="btn btn-small dropdown-toggle"> <span class="caret"></span></button>
                                    <ul class="dropdown-menu" style="min-width:0px !important;">
                                        <li><a href="<?php echo $this->sitePath."transaction/expense/view/id/".base64_encode($results['id']); ?>">View</a></li>
                                         <?php 
                                            if($logSession->type!=5 && $logSession->proxy_type!=5) {
                                         ?>
                                         <?php 
                                            if($results['transaction_status']!=3) {
                                         ?>
                                         <li><a href="javascript:void(0)" onclick="return addPayment('<?php echo $pending_amount; ?>','<?php echo $results['id']; ?>','<?php echo $results['discount_status']; ?>','<?php echo $coa_link; ?>','<?php echo $results['payment_status']; ?>','<?php echo $pay_status; ?>')">Add Payment</a></li>
                                         <?php
                                            }
                                        ?>
                                         <li><a href="javascript:void(0)" class="<?php if($results['transaction_status']==1) { echo "disable-indication disabled"; } ?>"  onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['transaction_status']; ?>')">Edit</a></li>
                                        <?php 
                                            if($results['transaction_status']!=3) {
                                         ?>
                                        <li><a href="javascript:void(0)" onclick="return copyExpense('<?php echo base64_encode($results['id']); ?>')">Copy</a></li>
                                        <?php
                                            }
                                        ?>
                                        <?php
                                            }
                                        ?>

                                        <?php 
                                          $faid = '';
                                          if(($logSession->proxy_type==2 || $logSession->type==2)) {
                                            if($results['transaction_status']==1 && $fixedAssets!=0) {
                                              if(isset($this->fixedAsset) && !empty($this->fixedAsset)) {
                                                foreach ($this->fixedAsset as $fixedassets) {
                                                  if($fixedassets['expense_id']==$results['id']) {
                                                    $faid = $fixedassets['id'];
                                                  }
                                                }
                                              }

                                              if(!empty($faid)) {
                                                $url = $this->sitePath."transaction/fixedassets/edit/id/".base64_encode($faid);
                                                $text = 'Manage in FA Module';
                                              } else {
                                                $url = $this->sitePath."transaction/fixedassets/add/id/".base64_encode($results['id']);
                                                $text = 'Add to FA Module';
                                              }
                                        ?>

                                        <li><a href="<?php echo $url; ?>"><?php echo $text; ?></a></li>

                                        <?php
                                            }
                                          }
                                        ?>

                                        <?php 
                                            if($logSession->type!=5 && $logSession->proxy_type!=5) {
                                         ?>
                                        <li><a href="javascript:void(0)" class="widget-remove" onclick="return deleteExpense('<?php echo base64_encode($results['id']); ?>')">Delete</a></li>
                                        <?php
                                            }
                                        ?>
                                    </ul>
                                    </div>

                                        <div class="col-md-2" style="margin-left:20px;">
                                        <?php 
                                          if(($logSession->proxy_type==2 || $logSession->type==2)) {
                                              $authorised = 1;
                                          } else if (($logSession->type==3 && $logSession->id==$results['approval_for']) || ($logSession->proxy_type==3 && $logSession->proxy_id==$results['approval_for'])) {
                                             $authorised = 1;
                                          }  else {
                                             $authorised = 2;
                                          }
                                          if($results['transaction_status']==1) {
                                        ?>
                                          <a class="btn btn-mini btn-success" href="javascript:void(0)" data-original-title="Unverify"  onclick="changeTransactionStatus('<?php echo base64_encode($results['id']); ?>',2,'<?php echo $authorised; ?>')"><i class="icon-ok"></i></a>
                                        <?php 
                                          } else if($results['transaction_status']==2) {
                                        ?>
                                          <a class="btn btn-mini btn-default" href="javascript:void(0)" data-original-title="Verify"  onclick="changeTransactionStatus('<?php echo base64_encode($results['id']); ?>',1,'<?php echo $authorised; ?>')"><i class="icon-ok"></i></a>
                                        <?php 
                                          } 
                                        if($results['transaction_status']==3) {
                                        ?>
                                         <a class="btn btn-mini btn-default" href="javascript:void(0)" data-original-title="Draft"><i class="icon-envelope"></i></a>
                                        <?php
                                            } 
                                        ?>
                                        </div>

                                    
                                                             
                                        </td>
                                        </tr>
                                    <?php 
                                        }
                                    ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
<script type="text/javascript" src="<?php echo $this->scriptpath.'SimpleAjaxUploader.min.js'; ?>"></script>
<script type="text/javascript">

  var expenseJson;

  $(document).ready(function(){

   <?php
      if(Zend_Session::namespaceIsset('fixed_asset')) {
       $fixed_asset = new Zend_Session_Namespace('fixed_asset');
       $fid = base64_encode($fixed_asset->id);

       Zend_Session::namespaceUnset('fixed_asset');
   ?>
     var confirmMsg = confirm('Do you want to continue setting up the depreciation?');
     if(confirmMsg) {
      window.location.href='<?php echo $this->sitePath."transaction/fixedassets/add/id/".$fid; ?>';
     }
   <?php 
      }
    ?>
        
  $.ajax({
        type: "POST",
        url: "<?php echo $this->sitePath.'transaction/expense/ajax-refresh'; ?>",
        data: 'action=expenseRefresh',
        success: function (html) {
            expenseJson = $.parseJSON(html);
          //s  console.log(expenseJson);
        }
      }); 
  });
    
    var counter = 2;
    $("#expense_row").on("click", function () {
        /* if(counter>5){
                    alert("Only 5 shipping address allowed");
                    return false;
         } */   
        var expense_type = '<div id="expenseRefresh'+counter+'"><select name="expense_type_' +counter+ '" id="expense_type_' +counter+ '"  class="form-control" required><option value="">Select</option>';

         <?php
/*            foreach ($this->expenseAccount as $expense) {
                $id = $expense['id'];
                $name = $expense['account_name'];
*/         ?>
          var accountType = [];
          $.each(expenseJson, function(){
            //console.log(accountType);
              if($.inArray(this.account_type,accountType)==-1) {
                if(this.account_type==1) {
                  expense_type += '<optgroup label="Assets">';
                } else if(this.account_type==4) {
                  expense_type += '<optgroup label="Expense">';
                }
                accountType.push(this.account_type);
              }



               expense_type += '<option value="'+this.id+'">'+this.account_name+'</option>';

           });

         <?php
            /*}
*/         ?>

         expense_type += '</select></div>';

         <?php
            if($logSession->type!=5 && $logSession->proxy_type!=5) {
         ?>
          expense_type += '<a href="<?php echo $this->sitePath."settings/account"; ?>" class="add-expenseaccount" title="Click to add new expense" data-title="Click to add new expense" target="_blank" onclick="expenseAccountRefresh();"><i class="icon-plus-circle-2"></i> Add New Expense</a>  &nbsp;';
         <?php
            }
         ?>

         var tax_code = '<select name="tax_code_' +counter+ '" id="tax_code_' +counter+ '"  class="form-control" required  onchange="return calculateTotal();"><option value="">Select</option>';
          tax_code += '<option value="0" title="Not Applicable">NA</option>';
         <?php
            foreach ($this->taxCode as $tax) {
                $id = $tax['id']."_".$tax['tax_percentage'];
                $name = $tax['tax_code']." - ".$tax['tax_percentage']." %";
                $taxdesc = ucfirst(str_replace("\r\n", " ", $tax['description']));
                foreach ($this->purchase as $key => $purchase) {
                  if($tax['tax_code']==$key) {
                      $code = $purchase['name']." - ".$tax['tax_percentage']." %";
                  }
                }
         ?>
            tax_code += '<option value="<?php echo $id; ?>" title="<?php echo $taxdesc; ?>"><?php echo $code; ?></option>';
         <?php
            }
         ?>

         tax_code += '</select>';


         var newTextBoxDiv = $(document.createElement('tr'))
              .attr("id", 'TextBoxDiv' + counter);
         // alert(expense_type);
         newTextBoxDiv.html('<td style="width:2%;"><a href="javascript:void(0)" value="removeButton"  class="remove_expense"><i class="icon-cancel-circle-2"></i></a> </td>'+
                            '<td style="width:20%;"><br/>'+expense_type+'</td>' +
                            '<td style="width:10%;"><input type="text" name="product_id_'+counter+'" id="product_id_'+counter+'" class="form-control" autocomplete="off" placeholder="Enter Product ID" /></td>' +
                            '<td style="width:20%;"><input type="text" name="product_description_'+counter+'" id="product_description_'+counter+'"  autocomplete="off" required class="form-control" placeholder="Enter Product Description" /></td>' +
                            '<td style="width:7%;"><input type="text"  autocomplete="off" name="quantity_'+counter+'" id="quantity_'+counter+'" class="form-control" required number="true" minlength="1" maxlength="5" onkeyup="return calculateTotal();" pattern="[0-9]{1,5}" /></td>' +
                            '<td style="width:10%;"><input type="text" name="price_'+counter+'"  autocomplete="off" id="price_'+counter+'" class="form-control amount-align" required  number="true"  onkeyup="return calculateTotal();"  onchange="return numberWithCommasInput(this.value,this.id);" /></td>' +
                            '<td style="width:12%;">'+tax_code+'</td><td style="width:10%;"><input type="text" name="gst_amount_'+counter+'"  autocomplete="off" id="gst_amount_'+counter+'" class="form-control amount-align" required  number="true" value="0.00" readonly onkeyup="return calculateGstTotal();" onchange="return numberWithCommasInput(this.value,this.id);" /></td><td style="text-align:right; padding-right:20px;"><strong id="net_amount_'+counter+'"></strong>&nbsp;</td></tr>');

         newTextBoxDiv.appendTo("#expense_detail");
         $("#expense_counter").val(counter);
         counter++;
    });

    $(document).on('click',".remove_expense",function (){   
        /* if(counter==1){
            alert("No more shipping addresses to remove");
            return false;
        } */  

        counter--;

        $("#TextBoxDiv" + counter).remove();
        $("#expense_counter").val(counter-1);
        calculateTotal();

    });

function creditSelect() {
  var value = $("#credit_term").val();
    if(value!=1) {
        var creditDate = '';
        <?php
            foreach ($this->creditTerm as $key => $credit) {
         ?>
            if(value==<?php echo $key; ?>) {
                <?php
                  if($key!=1) {
                ?>
                creditDate = <?php echo $credit; ?>
                <?php 
                    }
                ?>
            }
         <?php
            }
         ?>
        var expdate = $("#exp-date").val();
        var split_date = expdate.split('-');
        var today = new Date(split_date[2],split_date[1]-1,split_date[0]);
        var date = new Date(split_date[2],split_date[1]-1,split_date[0]);
        date.setDate(today.getDate()+creditDate);
        var dd    =  date.getDate();
        var mm   = date.getMonth();
        if(dd<10) {
          dd = "0" + dd;
        } else {
            dd = dd;
        }
       if(mm<9) {
        mm = "0" + (mm+1);
        } else {
            mm = mm+1;
        }
        var yyyy = date.getFullYear(); 
        var fullDate = dd+"-"+mm+"-"+yyyy;
         $("#due_date").val(fullDate);
    } else {
        var expdate = $("#exp-date").val();
        var split_date = expdate.split('-');
        var today = new Date(split_date[2],split_date[1]-1,split_date[0]);
        var date = new Date(split_date[2],split_date[1]-1,split_date[0]);
        date.setDate(today.getDate());
        var dd    =  date.getDate();
        var mm   = date.getMonth();
        if(dd<10) {
          dd = "0" + dd;
        } else {
            dd = dd;
        }
       if(mm<9) {
        mm = "0" + (mm+1);
        } else {
            mm = mm+1;
        }
        var yyyy = date.getFullYear(); 
        var fullDate = dd+"-"+mm+"-"+yyyy;
         $("#due_date").val(fullDate);
    }
     triggerPayment();
}

function discountPayment(value) {
    if(value==1) {
        $("#discount_amount").removeAttr("disabled");
    } else if(value==2) {
        $("#discount_amount").val("0");
        $("#discount_amount").attr("disabled","true");
    }
}

function editTransaction(Idvalue,status,type) {
  if(type==5) {
    window.location.href='<?php echo $this->sitePath; ?>transaction/expense/view/id/'+Idvalue;
    //alert("Cannot edit this expense because transaction is verified");
  } else if(status==1) {
    window.location.href='<?php echo $this->sitePath; ?>transaction/expense/view/id/'+Idvalue;
    //alert("Cannot edit this expense because transaction is verified");
  } else {
        window.location.href='<?php echo $this->sitePath; ?>transaction/expense/edit/id/'+Idvalue;
    }
}


function discountAddPayment(value) {
    if(value==1) {
        $("#discount_payment_amount").removeAttr("disabled");
    } else if(value==2) {
        $("#discount_payment_amount").val("0");
        $("#discount_payment_amount").attr("disabled","true");
    }
}

function calculateTotal() {
    var expense_count   = $("#expense_counter").val();
    var gst_rate        = Number($("#total_gst_rate").val());
   // var discount_amount = $("#discount_amount").val();
    var sub_total  = 0.00;
    var sub_gst  = 0.00;
    var total_gst  = 0.00;
    var grand_total = 0.00;
    var grand_total_sgd = 0.00;

    for(var i = 1; i<=expense_count;i++) {
        var net_amount = 0.00;
        var total_gst  = 0.00;
        var subGst     = 0.00;
        var quantity = $("#quantity_"+i).val();
        var price    = $("#price_"+i).val();
        var tax_code = $("#tax_code_"+i).val(); 
        var myTax    = tax_code.split('_');
        if(quantity!=0 && quantity!='' && price!=0 && price!='') {
            var net_amount = (quantity * numberWithCommas(price,'format'));
        }
        if(myTax[0]!=0 && myTax[0]!='' && myTax[1]!=0 && myTax[1]!='') {
            $("#gst_amount_"+i).removeAttr("readonly");
            total_gst += parseFloat(myTax[1]);
        } else {
            $("#gst_amount_"+i).attr("readonly","readonly");
        }
        $("#net_amount_"+i).text(numberWithCommas(parseFloat(net_amount).toFixed(2),'normal'));
        sub_total += parseFloat(net_amount);
        sub_gst   += (parseFloat(net_amount) * parseFloat(total_gst) / 100);
        subGst    += (parseFloat(net_amount) * parseFloat(total_gst) / 100);

           if(subGst!=0.00) {
            $("#gst_amount_"+i).val(numberWithCommas(subGst,'normal'));
          } else {
            $("#gst_amount_"+i).val('0.00');
          }

    }
   // alert(sub_total);
   // sub_total -= parseFloat(discount_amount);
   // alert(sub_total);
   // alert(sub_gst);


    
    grand_total += parseFloat(sub_total) + parseFloat(sub_gst);
    $("#sub_total").text(numberWithCommas(parseFloat(sub_total).toFixed(2),'normal'));
    $("#total_gst").text(numberWithCommas(parseFloat(sub_gst).toFixed(2),'normal'));
    $("#grand_total").text(numberWithCommas(parseFloat(grand_total).toFixed(2),'normal'));
    //alert(gst_rate);
    gp_convertIt(parseFloat(sub_total),Number(sub_gst));
    /*if(gst_rate!=0) {
      gp_convertIt(parseFloat(sub_total)+Number(gst_rate));
    } else { 
      gp_convertIt(parseFloat(grand_total));
    }*/
}




function calculateGstTotal() {
    var expense_count   = $("#expense_counter").val();
    var gst_rate        = Number($("#total_gst_rate").val());
   // var discount_amount = $("#discount_amount").val();
    var sub_total  = 0.00;
    var sub_gst  = 0.00;
    var total_gst  = 0.00;
    var grand_total = 0.00;
    var grand_total_sgd = 0.00;

    for(var i = 1; i<=expense_count;i++) {
        var net_amount = 0.00;
        var total_gst  = $("#gst_amount_"+i).val();
        var subGst     = 0.00;
        var quantity = $("#quantity_"+i).val();
        var price    = $("#price_"+i).val();
        
        if(quantity!=0 && quantity!='' && price!=0 && price!='') {
            var net_amount = (quantity * numberWithCommas(price,'format'));
        }


        //console.log(total_gst);
        $("#net_amount_"+i).text(numberWithCommas(parseFloat(net_amount).toFixed(2),'normal'));
        sub_total += parseFloat(net_amount);
        sub_gst   += parseFloat(numberWithCommas(total_gst,'format'));
       // sub_gst   += (parseFloat(net_amount) * parseFloat(total_gst) / 100);
        //subGst    += (parseFloat(net_amount) * parseFloat(total_gst) / 100);


    }
   // alert(sub_total);
   // sub_total -= parseFloat(discount_amount);
   // alert(sub_total);
   //alert(sub_gst);


    
    grand_total += parseFloat(sub_total) + parseFloat(sub_gst);
    $("#sub_total").text(numberWithCommas(parseFloat(sub_total).toFixed(2),'normal'));
    $("#total_gst").text(numberWithCommas(parseFloat(sub_gst).toFixed(2),'normal'));
    $("#grand_total").text(numberWithCommas(parseFloat(grand_total).toFixed(2),'normal'));
    //alert(gst_rate);
    gp_convertIt(parseFloat(sub_total),Number(sub_gst));
    /*if(gst_rate!=0) {
      gp_convertIt(parseFloat(sub_total)+Number(gst_rate));
    } else { 
      gp_convertIt(parseFloat(grand_total));
    }*/
}




function payTotal() {
    var expense_count   = $("#expense_counter").val();
    var gst_rate        = Number($("#total_gst").val());
   // var discount_amount = $("#discount_amount").val();
    var sub_total  = 0.00;
    var sub_gst  = 0.00;
    var total_gst  = 0.00;
    var grand_total = 0.00;
    var grand_total_sgd = 0.00;

    for(var i = 1; i<=expense_count;i++) {
        var net_amount = 0.00;
        var total_gst  = $("#gst_amount_"+i).val();
        var quantity = $("#quantity_"+i).val();
        var price    = $("#price_"+i).val();
        var tax_code = $("#tax_code_"+i).val(); 
        var myTax    = tax_code.split('_');
        if(quantity!=0 && quantity!='' && price!=0 && price!='') {
            var net_amount = (quantity * numberWithCommas(price,'format'));
        }
        /*if(myTax[0]!=0 && myTax[0]!='' && myTax[1]!=0 && myTax[1]!='') {
            total_gst += parseFloat(myTax[1]);
        }*/ 
        $("#net_amount_"+i).text(numberWithCommas(parseFloat(net_amount).toFixed(2),'normal'));
        sub_total += parseFloat(net_amount);
        sub_gst   += parseFloat(numberWithCommas(total_gst,'format'));
    }
  
    grand_total += parseFloat(sub_total) + parseFloat(sub_gst);
    return numberWithCommas(parseFloat(grand_total).toFixed(2),'normal');
}

function paysubTotal() {
    var expense_count   = $("#expense_counter").val();
    var gst_rate        = Number($("#total_gst").val());
   // var discount_amount = $("#discount_amount").val();
    var sub_total  = 0.00;
    var sub_gst  = 0.00;
    var total_gst  = 0.00;
    var grand_total = 0.00;
    var grand_total_sgd = 0.00;

    for(var i = 1; i<=expense_count;i++) {
        var net_amount = 0.00;
        var total_gst  = $("#gst_amount_"+i).val();
        var quantity = $("#quantity_"+i).val();
        var price    = $("#price_"+i).val();
        var tax_code = $("#tax_code_"+i).val(); 
        var myTax    = tax_code.split('_');
        if(quantity!=0 && quantity!='' && price!=0 && price!='') {
            var net_amount = (quantity * numberWithCommas(price,'format'));
        }
        /*if(myTax[0]!=0 && myTax[0]!='' && myTax[1]!=0 && myTax[1]!='') {
            total_gst += parseFloat(myTax[1]);
        } */
        $("#net_amount_"+i).text(numberWithCommas(parseFloat(net_amount).toFixed(2),'normal'));
        sub_total += parseFloat(net_amount);
        sub_gst   += parseFloat(numberWithCommas(total_gst,'format'));
    }
  
    grand_total += parseFloat(sub_total) + parseFloat(sub_gst);
    return numberWithCommas(parseFloat(sub_total).toFixed(2),'normal');
}

function paygstTotal() {
    var expense_count   = $("#expense_counter").val();
    var gst_rate        = Number($("#total_gst").val());
   // var discount_amount = $("#discount_amount").val();
    var sub_total  = 0.00;
    var sub_gst  = 0.00;
    var total_gst  = 0.00;
    var grand_total = 0.00;
    var grand_total_sgd = 0.00;

    for(var i = 1; i<=expense_count;i++) {
        var net_amount = 0.00;
        var total_gst  = $("#gst_amount_"+i).val();
        var quantity = $("#quantity_"+i).val();
        var price    = $("#price_"+i).val();
        var tax_code = $("#tax_code_"+i).val(); 
        var myTax    = tax_code.split('_');
        if(quantity!=0 && quantity!='' && price!=0 && price!='') {
            var net_amount = (quantity * numberWithCommas(price,'format'));
        }
        /*if(myTax[0]!=0 && myTax[0]!='' && myTax[1]!=0 && myTax[1]!='') {
            total_gst += parseFloat(myTax[1]);
        } */
        $("#net_amount_"+i).text(numberWithCommas(parseFloat(net_amount).toFixed(2),'normal'));
        sub_total += parseFloat(net_amount);
        sub_gst   += parseFloat(numberWithCommas(total_gst,'format'));
    }
  
    grand_total += parseFloat(sub_total) + parseFloat(sub_gst);
    return numberWithCommas(parseFloat(sub_gst).toFixed(2),'normal');
}

function changeTransactionStatus(Idvalue,status,auth) {
  var location = $('#locations').val();
  var finance  = $('#financial_year').val();
  if(auth==1) {
    window.location.href='<?php echo $this->sitePath; ?>transaction/expense/index/verifyid/'+Idvalue+'/status/'+status+'/?location='+location+'&financial_year='+finance;
    } else if(auth==2) {
        if(status==1) {
          alert('You are not authorized to verify this transaction');
        } else if(status==2) {
          alert('You are not authorized to unverify this transaction');
        }
    }
}
function showExpense() {
    $('form').each(function(){
        this.reset();
    });
    $('#add_expense').slideToggle(1000);
} 
function hideExpense() {
    $('form').each(function(){
        this.reset();
    });
    $('#add_expense').slideToggle(1000);
} 
function deleteExpense(Idvalue) {
  var location = $('#locations').val();
  var finance  = $('#financial_year').val();
  var confirmMsg = confirm("Are you sure want to delete this expense transaction? You cannot undo this action");
    if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>transaction/expense/index/delid/'+Idvalue+'/?location='+location+'&financial_year='+finance;
    }
}
function copyTransaction(Idvalue) {
  var confirmMsg = confirm("Are you sure want to copy this expense transaction?");
    if(confirmMsg) {
        $.ajax({
            type: "POST",
            url: "<?php echo $this->sitePath; ?>transaction//ajax-call",
            data: "ajaxAction=copy_transaction&tid="+Idvalue,
            success: function (html) {
                $('#add_expense').hide(500);
                $('#copy_expense').hide(500);
                $('#copy_transaction').html(html);
                $('#copy_expense').show(1500);
            }
    });
    }
}

function copyExpense(Idvalue) {
  var confirmMsg = confirm("Are you sure want to copy this expense transaction? ");
    if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>transaction/expense/copy/id/'+Idvalue;
    }
}


function addPayment(pendingAmount,Idvalue,discountStatus,coa_link,status,pstatus) {
  if(pendingAmount<=0 || status==1) {
      alert("Full payment has been made for this expense");
      return false;
  } else {
    $('form').each(function(){
        this.reset();
    });

    var vendAccount = coa_link;
    //console.log($.inArray("2",custAccount));
    var payaccount = '';
    /*payaccount +='<optgroup label="Cash and Cash Equivalents">';*/
    <?php
      $opt1 = 0;
      $opt2 = 0;
      foreach ($this->cashAccount as $cash) {
        $pays = $cash['id']."_".$cash['level2']."_".$cash['account_type'];
    ?>
        payaccount +='<option value=<?php echo $cash['id']; ?>><?php echo ucfirst($cash['account_name']); ?></option>';
    <?php
      }
    ?>
            payaccount +='</optgroup>';

    $("#pay_account").html(payaccount);
    $("#expense_id").val(Idvalue);
    $("#currency_status").val(pstatus);
    $("#pay_amount").val(numberWithCommas(pendingAmount,'normal'));
    $("#pending_amount").val(pendingAmount);
    $("#add_receipt").hide();
    $("#add_payment").show();
    if(discountStatus==1) {
      $("select#payment_discount option[value='1']").attr("selected","selected"); 
      $("#discount_payment_amount").removeAttr("disabled");
    } else if(discountStatus==2) {
      $("select#payment_discount option[value='2']").attr("selected","selected"); 
      $("#discount_payment_amount").val("0");
      $("#discount_payment_amount").attr("disabled","true");
    }
      $("#pay_account").find('option').removeAttr("selected");
   // $("#pay_account").val(accountId);
   // $("#pay_account option[value='"+vendAccount+"']").attr("selected", "selected");
    $('#popup').bPopup({
            modalClose: false,
            easing: 'easeOutBack', 
            speed: 1000,
            transition: 'slideDown',
            follow: [false, false], 
    });
  }
}

 function saveDraft() {
  $(".btn").attr("disabled",true);
    $.ajax({
      type: "POST",
      url: "<?php echo $this->sitePath.'transaction/expense/ajax-call'; ?>",
      data: $('#add-expense').serialize(),
      success: function (html) {
          if(html=='success') {
             $('#add_expense').slideToggle(1000);
             $(".btn").attr("disabled",false);
              window.location.href='<?php echo $this->sitePath; ?>transaction/expense';
          } else {
             $('#failure').html('<strong>Expense cannot be saved as draft</strong>');
             $('#failure').fadeIn(1000);
             $('#failure').fadeOut(9000);
             $(".btn").attr("disabled",false);
          }
      }
    }); 
 }

/* function getReceipt(value) {
  if(value!='') {
      var i=0;
      var vendor_receipt = '<select name="receipts" id="receipts"  class="form-control" required><option value="">Select</option>';

         <?php
            foreach ($this->receipts as $receipt) {
        ?>
          if(value==<?php echo $receipt['fkbusiness_id'] ?>) {
        <?php
                $id   = $receipt['id']."-".$receipt['name']."-".$receipt['receipt'];
                $name = $receipt['name'];
         ?>
           vendor_receipt += '<option value="<?php echo $id; ?>"><?php echo $name; ?></option>';
           i++;
          }
         <?php
            }
         ?>
         vendor_receipt += '</select>';
         if(i==0) {
           $("#receipt_add").html("<p>No Receipts Found</p>");
         } else {
           $("#receipt_add").html(vendor_receipt);
         }
         $("#receipt_id").val("");
         $("#vendor_receipts").html("");
         $("#vendor_receipts").hide();
         $("#attach").show();

  }
}*/

 function attachReceipt() {
    var vendor = $("#vendor").val();
    if(vendor=='') {
        alert('Select any vendor to attach receipt');
    } else {
        $("#add_payment").hide();
        $("#add_receipt").show();
        $('#popup').bPopup({
                modalClose: false,
                easing: 'easeOutBack', 
                speed: 1000,
                transition: 'slideDown',
                follow: [false, false], 
        });
    }
 }

 function addReceipt() {
    var receipts      = $("#receipts").val();
    var receiptSplit  = receipts.split('-');
    var receiptId     = receiptSplit[0];
    var receiptName   = receiptSplit[1];
    var receiptFile   = receiptSplit[2];
    if(receiptId!='' && receiptName!='' && receiptFile!='') {
      var receipturl = '<a href="<?php echo $this->filepath; ?>'+receiptFile+'" target="_blank"> '+receiptName+' </a>';
      $("#receipt_id").val(receiptId);
      $("#attach").hide();
      $("#vendor_receipts").html("Receipt "+ receipturl +" have been attached");
      $("#vendor_receipts").show();
    }
    $("#popup").bPopup().close();
 }
 function bPopup_close() {
     $("#popup").bPopup().close();
 }

 function numberWithCommas(x,action) {
  if(action=='normal') {
    var amount = parseFloat(x).toFixed(2);
    var value = amount.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
    return value;
  } else if(action=='format')  {
    var value  = x.replace(/\,/g,''); 
    return value;
  }
}

 function numberWithCommasInput(x,id) {
    var amount = parseFloat(x).toFixed(2);
    var value  = amount.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
    $("#"+id).val(value);
}

/*function gp_convertIt(amount) {
  if (amount=='' || amount==0){
    return false;
  } else {
  var gp_from = document.getElementById('currency').value;
    if(gp_from!='SGD') {
      var gp_to   = 'SGD';
      var gp_amount = amount;
      $.getJSON( "http://www.geoplugin.net/currency_converter.gp?jsoncallback=?", { from:gp_from, to:gp_to, amount:gp_amount }, 
        function(output){
          $("#grand_total_sgd").html(output.to.symbol + output.to.amount);
          $("#foreign_currency").val(output.to.amount);
          $("#addpay_pay_amount").val(output.to.amount);
        });
    } else {
      $("#grand_total_sgd").html("$ 0.00");
      $("#foreign_currency").val("");
      $("#addpay_pay_amount").val(amount);
    }
  } 
}

function gp_convertItReturn(amount) {
  if (amount=='' || amount==0){
    return false;
  } else {
  var gp_from = document.getElementById('currency').value;
    if(gp_from!='SGD') {
      var gp_to   = 'SGD';
      var gp_amount = amount;
      $.getJSON( "http://www.geoplugin.net/currency_converter.gp?jsoncallback=?", { from:gp_from, to:gp_to, amount:gp_amount }, 
        function(output){
          return output.to.amount;
        });
    } else {
      return amount;
    }
  } 
}
*/

function originalRate(rate) {
  var gp_from = document.getElementById('currency').value;
  if(gp_from!='SGD') { 
    var amount  = numberWithCommas(paysubTotal(),'format');
    var gst     = numberWithCommas(paygstTotal(),'format');
    //console.log(gst);
    var original_amount = numberWithCommas(Number(rate)*(Number(amount)+Number(gst)),'normal');
    var sub_amount      = numberWithCommas(Number(rate)*amount,'normal');
    var sub_gst         = numberWithCommas(Number(rate)*gst,'normal');
    $("#sub_total_sgd").val(sub_amount);
    $("#total_gst_rate").val(sub_gst);
    $("#grand_total_sgd").html("$ "+ original_amount);
    $("#foreign_currency").val(original_amount);
    $("#addpay_pay_amount").val(original_amount);
  }
}

function gstRate(rate) {
  var gp_from = document.getElementById('currency').value;
  if(gp_from!='SGD') { 
    var sub_total = numberWithCommas($("#sub_total_sgd").val(),'format');
    var sgd_gst   = numberWithCommas(Number(sub_total)+Number(rate),'normal');
    $("#grand_total_sgd").html("$ "+ sgd_gst);
    $("#foreign_currency").val(sgd_gst);
    $("#addpay_pay_amount").val(sgd_gst);
  }
}

function gp_convertIt(amount,gst) {
  if (amount=='' || amount==0){
    return false;
  } else {
  var gp_from = document.getElementById('currency').value;
    if(gp_from!='SGD') {
      var gp_to   = 'SGD';
      var gp_amount = amount;
      $.ajax({
        type: "POST",
        url: "<?php echo $this->sitePath.'default/index/convert-currency'; ?>",
        data: 'action=converter&amount=1&from='+gp_from,
        success: function (html) {
          //var convert_amount = numberWithCommas(Number(html),'normal');
           var convert_rate = Number(html);
          $("#exchange_rate").val(convert_rate);
          var convert_amount = convert_rate*amount;
          var gst_amount     = convert_rate*gst;
          var grand_amount   = numberWithCommas(convert_amount+gst_amount,'normal');
          $("#total_gst_rate").val(numberWithCommas(gst_amount,'normal'));
          $("#grand_total_sgd").html("$ "+ grand_amount);
          $("#sub_total_sgd").val(convert_amount);
          $("#foreign_currency").val(grand_amount);
          $("#addpay_pay_amount").val(grand_amount);
        }
      });
    } else {
      $("#exchange_rate").val("");
      $("#grand_total_sgd").html("$ 0.00");
      $("#foreign_currency").val("");
      $("#sub_total_sgd").val("");
      $("#addpay_pay_amount").val(numberWithCommas(amount+gst,'normal'));
    }
  } 
}



function gp_convertItReturn(amount) {
  if (amount=='' || amount==0){
    return false;
  } else {
  var gp_from = document.getElementById('currency').value;
    if(gp_from!='SGD') {
      var gp_to   = 'SGD';
      var gp_amount = amount;
      $.ajax({
        type: "POST",
        url: "<?php echo $this->sitePath.'default/index/convert-currency'; ?>",
        data: 'action=converter&amount='+gp_amount+'&from='+gp_from,
        success: function (html) {
          var convert_amount = numberWithCommas(Number(html),'normal');
          return convert_amount;
        }
      });
    } else {
      return amount;
    }
  } 
}


function discountTriggerPayment(value) {
    if(value==1) {
        $("#addpay_discount_payment_amount").removeAttr("disabled");
    } else if(value==2) {
        $("#addpay_discount_payment_amount").val("0");
        $("#addpay_discount_payment_amount").attr("disabled","true");
    }
}

function triggerPayment() {
   /* var pay_account      = $("#payment_account").val();*/
    var credits          = $("#credit_term").val();
    //var amount           = payTotal();
    /*var payment_account  = pay_account.split('_');
    $("#addpay_pay_account").find('option').removeAttr("selected");
    $("#addpay_pay_account option[value='"+payment_account[0]+"']").attr("selected", "selected");*/
   // $("#addpay_pay_amount").val(amount);
    if(credits==1) {
      $("#payment_trigger").val("1");
      $("#trigger_payment").show();
    } else {
      $("#trigger_payment").hide();
      $("#payment_trigger").val("0");
    } 
}

function refreshList(type) {
  if(type==1) {
        var vendorId = $("#vendor").val();
        $.ajax({
        type: "POST",
        url: "<?php echo $this->sitePath.'transaction/expense/ajax-refresh'; ?>",
        data: 'action=vendorRefresh&id='+vendorId,
        success: function (html) {
            $("#vendor").html(html);
        }
      }); 
  } else if(type==2) {
       var payId = $("#payment_account").val();
        $.ajax({
        type: "POST",
        url: "<?php echo $this->sitePath.'transaction/expense/ajax-refresh'; ?>",
        data: 'action=payaccountRefresh&id='+payId,
        success: function (html) {
            $("#payRefresh").html(html);
        }
      }); 
  } 
}

function refreshExpenseList() {
  var expense_count   = $("#expense_counter").val();
      $.ajax({
        type: "POST",
        url: "<?php echo $this->sitePath.'transaction/expense/ajax-refresh'; ?>",
        data: 'action=expenseRefresh',
        success: function (html) {

          expenseJson = $.parseJSON(html);
          for(var i=1;i<=expense_count;i++) {
            var expenseSelect = '';
            var expenseValue = $("#expense_type_"+i).val();
            var expense_type = '<select name="expense_type_'+i+ '" id="expense_type_'+i+ '"  class="form-control" required><option value="">Select</option>';
              $.each(expenseJson, function(){
                  if(expenseValue==this.id)
                      expenseSelect = 'selected';
                  else
                      expenseSelect = '';
                  expense_type += '<option value='+this.id+' '+expenseSelect+'>'+this.account_name+'</option>'
             
              });
            expense_type += '</select>';
            $("#expenseRefresh"+i).html(expense_type);
          }

/*          console.log("ID: " + this.id);
            console.log("First Name: " + this.account_id);
            console.log("Last Name: " + this.account_name);
            console.log(" ");*/

            //$("#expenseRefresh"+id).html(html);
        }
      }); 
}

</script>
<script type="text/javascript">
   var btn = document.getElementById('file'),
       sizeBox = document.getElementById('sizeBox'), // container for file size info
       progress = document.getElementById('progress-bar'); // the element we're using for a progress bar

window.onload = function() {

    var uploader = new ss.SimpleUpload({
          button: btn, // file upload button
          url: "<?php echo $this->sitePath.'transaction/expense/ajax-upload/operation/add'; ?>", // server side handler
          name: 'uploadfile', // upload parameter name        
        //  progressUrl: 'extras/uploadProgress.php', // enables cross-browser progress support (more info below)
          responseType: 'json',
          allowedExtensions: ['jpg', 'jpeg', 'png', 'gif', 'docx', 'pdf', 'doc'],
          maxSize: 10240, // kilobytes
          hoverClass: 'ui-state-hover',
          focusClass: 'ui-state-focus',
          disabledClass: 'ui-state-disabled',
          onSubmit: function(filename, extension) {
              this.setFileSizeBox(sizeBox); // designate this element as file size container
              this.setProgressBar(progress); // designate as progress bar
              $("#progress-bar").show();
            },         
          onComplete: function(filename, response) {
              if (!response) {
                  alert(filename + 'upload failed');
                  return false;            
              } else {
                $("#progress-bar").hide();
                var filename = response.data['file'];
                var status = response.data['status'];
                if(status=='success') {
                  $(".view_remove_file").html("<a href='<?php echo $this->sitePath.$this->filepath; ?>"+ filename +"' target='_blank'>Click to View</a> &nbsp; <a href='javascript:void(0)'' title='Remove Attachment' data-title='Remove Attachment' onclick='removeAttachment();'><i class='icon-remove-sign'></i></a>");
                  $("#attached_file").val(filename);
                  $(".view_remove_file").show();
                  $(".attach_file").show();
                  $("input[name='uploadfile']").attr('disabled','disabled');  
                } else if(status=='failure') {
                  alert("Upload Error : "+filename);
                  $("input[name='uploadfile']").removeAttr('disabled');
                  return false;
                } 

              }

                //console.log(filename);
              // do something with response...
            }
    });

/*  $('#vendor').on("change",function(){
      var value = $(this).find('option:selected').val();
      var coa   = $(this).find('option:selected').data('coa');
      if(value!='') {
          $.ajax({
            type: "POST",
            url: "<?php echo $this->sitePath.'transaction/expense/ajax-refresh'; ?>",
            data: 'action=getPayAccount&coa='+coa,
            success: function (html) {
                $("#payment_account").html(html);
            }
          });
      } else {
        $("#payment_account").html('<option value="">Select</option>');
      }
  }); */    
};

function removeAttachment() {
  var attachedFile = $("#attached_file").val();
  if(attachedFile!='') {
    var confirmMsg = confirm('Are you sure want to remove the attachment?');
    if(confirmMsg) {
      $.ajax({
        type: "POST",
        url: "<?php echo $this->sitePath.'transaction/expense/ajax-remove'; ?>",
        data: 'action=fileRemove&id='+attachedFile,
        success: function (html) {
            if(html=='success') {
              $("#attached_file").val('');
              $(".view_remove_file").hide();
              $(".attach_file").hide();
              $("input[name='uploadfile']").removeAttr('disabled');
              alert("File Removed Successfully");
            } else {
              alert("Unable to remove the attached file. Kindly try again later");
            }
        }
      }); 
    }
  }
}


  function checkReceipt(value) {
        if((value!='')) {
            $.ajax({
              type: "POST",
              url: "<?php echo $this->sitePath.'transaction/expense/ajax-refresh'; ?>",
              data: 'action=check_receipt&receipt_no='+value,
              success: function (html) {
                  if(html=='1') {
                     $(".receipt_error").html("");
                     $(".receipt_error").hide();
                     return true;
                  } else if(html=='2') {
                     $(".receipt_error").html("Receipt No "+ value +" already exists");
                     $("#receipt").val("");
                     $(".receipt_error").show();
                  }
              }
            }); 
        } 
  }

  function numberWithOutCommasInput(x) {
  x=x.replace(/\,/g,''); 
  var value = parseFloat(x).toFixed(2);
  return value;
}
$(document).ready(function(){
   $('#show_filter').click(function () {
       $('#hide_filter').css('display','inline-block');
       $('#filters_id').css('display','block');
       $('#show_filter').css('display','none');
   }); 
   $('#hide_filter').click(function () {
       $('#show_filter').css('display','inline-block');
        $('#filters_id').css('display','none');
       $('#hide_filter').css('display','none');
   }); 
});
</script>