<?php
   $logSession = new Zend_Session_Namespace('sess_login');
?>
<div id="popup">
<span class="button b-close"><span>X</span></span>
<div class="row" id="add_payment">
 <h4>Add Payment</h4>
<div class="widget-container col-md-12 col-md-offset-1">
 <form class="form-horizontal" id="add-payment" method="post">
    <div class="form-group">
      <label class="control-label col-lg-4">Payment Date <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <input type="hidden" name="expense_id" id="expense_id" />
            <input type="hidden" name="pay_id" id="pay_id" />
            <input type="text" name="date" id="date" class="form-control date-pick" placeholder="Select Date"  autocomplete="off" />
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Payment / Accruals Account <span class="mandatory">*</span></label>
        <div class="col-lg-5">
             <select class="form-control" name="pay_account" id="pay_account">
                <option value="">Select</option>
                    <?php
                        if(isset($this->payAccount) && !empty($this->payAccount)) {
                            foreach ($this->payAccount as $payAccount) {
                    ?>
                        <option value="<?php echo $payAccount['id']; ?>"><?php echo $payAccount['account_name']; ?></option>
                    <?php
                            }
                        }
                    ?>                                                       
              </select>
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Amount <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <input type="text" name="pay_amount" id="pay_amount" class="form-control" placeholder="Enter Amount"  autocomplete="off" />
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Payment Method <span class="mandatory">*</span></label>
        <div class="col-lg-5">
          <select name="pay_method" id="pay_method" class="form-control">
            <option value="">Select</option>
           <?php 
                foreach ($this->payMethod as $key => $pay) {
           ?>
                <option value="<?php echo $key; ?>"><?php echo $pay; ?></option>
           <?php
                }
           ?>
          </select>
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Bank Cheque / Draft No </label>
        <div class="col-lg-5">
            <input type="text" name="cheque_draft_no" id="cheque_draft_no" class="form-control" placeholder="Enter Cheque / Draft No" autocomplete="off"  />
        </div>
    </div>
     <div class="form-group">
      <label class="control-label col-lg-4">Prompt Payment Discount <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <select class="form-control" name="payment_discount" id="payment_discount" onchange="discountPayment(this.value);">
                <option value="1">Yes</option>  
                <option value="2" selected>No</option>  
            </select>
        </div>
    </div>
     <div class="form-group">
      <label class="control-label col-lg-4">Discount Amount <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <input type="text" name="discount_amount" id="discount_amount" class="form-control" value="0" disabled autocomplete="off" />
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Additional Description / Notes </label>
        <div class="col-lg-5">
        <textarea name="description" id="description" class="form-control"></textarea>
        </div>
    </div>

     <div class="form-group">
        <div class="col-lg-8 col-lg-offset-3">
            <div class="form-actions">
               <input type="submit" name="update_payment" class="btn btn-primary " id="update_payment" value="Update Payment" />
                <button type="reset" class="btn" onclick="return bPopup_close();">Cancel</button>
            </div>
        </div>
     </div>

</form>
</div>
</div>
</div>

<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."transaction/expense/"; ?>">Expense</a></li>
   <li class="active">View</li>
</ul>


<div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            </div>
   </div>
<div class="row">
<div class="col-md-12">
                            <div class="square-widget">
                                <div class="widget-head clearfix">
                                    <h4 class="pull-left"><i class="icon-user-4"></i> Expense Transaction Details</h4>
                                </div>
                                <div class="widget-container" style="margin-left:50px;">
                                <div class="row">
                                    <div class="col-md-3">
                                        <strong>Expense No  </strong> <br/>
                                        <span><?php echo $this->expense[0]['expense_no']; ?></span>
                                    </div>
                                    <div class="col-md-3"> 
                                        <strong>Branch </strong><br>
                                        <span>
                                        <?php 
                                          if(isset($this->location) && !empty($this->location)) {
                                                foreach ($this->location as $location) {
                                                    if($location['id']==$this->expense[0]['fklocation_id']) {
                                                        echo ucfirst($location['name']);
                                                    }
                                                }
                                            }
                                        ?>
                                        </span>
                                        

                                    </div>
                                    <div class="col-md-3">
                                        <strong>Date </strong> <br/>
                                        <span><?php echo date("d-m-Y",strtotime($this->expense[0]['date'])); ?></span>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Receipt No  </strong> <br/>
                                        <span><?php echo $this->expense[0]['receipt_no']; ?></span>
                                    </div>
                                    
                                </div>
                                <br/>
                                <div class="row">
                                    <div class="col-md-3">
                                        <strong>Vendor  </strong> <br/>
                                        <span><?php echo $this->expense[0]['vendor_name']; ?></span>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Credit Term </strong> <br>
                                        <span>
                                        <?php 
                                          if(isset($this->creditTerm) && !empty($this->creditTerm)) {
                                              foreach ($this->creditTerm as $key => $credit) {
                                                if($key==$this->expense[0]['credit_term']) {
                                                  echo $credit;
                                                }
                                              }
                                          }
                                        ?>
                                        </span>
                                       
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Due Date </strong> <br>
                                        <span><?php echo date("d-m-Y",strtotime($this->expense[0]['due_date'])); ?></span>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Transaction Currency </strong> <br>
                                        <span>
                                        <?php 
                                          if(isset($this->currencies) && !empty($this->currencies)) {
                                            foreach ($this->currencies as $key => $currency) {
                                              if($key==$this->expense[0]['transaction_currency']) {
                                                  echo $currency." - ".$key;
                                                }
                                            }
                                          }
                                        ?>
                                        </span>
                                    </div>
                                    
                                    
                                </div>
                                <br/>
                                <div class="row">
                                <div class="col-md-3">
                                        <strong>Shipping Address </strong> <br>
                                        <span><?php if($this->expense[0]['shipping_address']==1) { echo "Default Shipping Address";} ?></span>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Prompt Payment Discount  </strong><br>
                                        <span><?php if($this->expense[0]['discount_status']==1) { echo "Yes";} else if($this->expense[0]['discount_status']==2) { echo "No"; } ?></span>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Permit No  </strong><br>
                                        <span><?php echo $this->expense[0]['permit_no']; ?></span>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>D.O / S.O No  </strong><br>
                                        <span><?php echo $this->expense[0]['do_so_no']; ?></span> 
                                    </div>
                                    
                                     
                                </div>
                                <br/>
                                 <div class="row">

                                  <div class="col-md-3">
                                            <strong>Receipt if any </strong><br>
                                            <span>
                                        <?php
                                          if(isset($this->expense[0]['fkreceipt_id']) && !empty($this->expense[0]['fkreceipt_id']) && file_exists($this->filepath.$this->expense[0]['fkreceipt_id'])) {
                                         ?>
                                            <a href="<?php echo $this->sitePath.$this->filepath.$this->expense[0]['fkreceipt_id']; ?>" target="_blank">Click to view</a>
                                             <?php 
                                          } else {
                                          ?>
                                          No attachments available
                                          <?php 
                                            }
                                          ?>
                                          </span>
                                    </div>
                                 
                                    <div class="col-md-3">
                                        <strong>Approval By / For </strong><br>
                                        <span>
                                        <?php 
                                            if(isset($this->approveUser) && !empty($this->approveUser)) {
                                                foreach ($this->approveUser as $approve) {
                                                 if($approve['account_type']==0) {
                                                        $account_type = "Developer";
                                                  } 
                                                  else if($approve['account_type']==1) {
                                                        $account_type = "Developer";
                                                  } 
                                                  else if($approve['account_type']==2) {
                                                        $account_type = "Super User";
                                                  } else if($approve['account_type']==3) {
                                                        $account_type = "Manager";
                                                  }
                                                  if($approve['id']==$this->expense[0]['approval_for']) {
                                                        echo $approve['username']." - ".$account_type;
                                                  }
                                                }
                                            }
                                        ?>
                                        </span>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Status </strong><br>
                                        <span>
                                        <?php 
                                            if($this->expense[0]['transaction_status']==1) {
                                                echo "Approved / Verified";
                                            } else if($this->expense[0]['transaction_status']==2) {
                                                echo "Saved / Unverified";
                                            } else if($this->expense[0]['transaction_status']==3) {
                                                echo "Draft";
                                            }
                                        ?>
                                        </span>
                                    </div>
                                 </div>

                                </div>
                            </div>
                        </div>
                </div>

<div class="row">
        <div class="col-md-12">
                            <div class="square-widget">
                                <h5 class="pull-left"><i class="icon-user-4"></i> Product Details</h5>
                                <div class="widget-container">
                                    <table class="table responsive">
                                        <thead>
                                            <tr>
                                                <th>
                                                    Expense Type
                                                </th>
                                                <th>
                                                    Product ID
                                                </th>
                                                <th>
                                                    Product Description
                                                </th>
                                                <th>
                                                    Quantity
                                                </th>
                                                <th>
                                                    Unit Price
                                                </th>
                                                <th>
                                                    Tax Code
                                                </th>
                                                <th>
                                                    GST
                                                </th>
                                                <th>
                                                    Amount
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody id="expense_detail">
                                        <?php
                                            $i = 1;
                                            $total_gst = 0.00;
                                            $sub_total = 0.00;
                                            if(isset($this->expenseList) && !empty($this->expenseList)) {
                                                foreach ($this->expenseList as $expenseList) {
                                                    $net_amount = $expenseList['quantity'] * $expenseList['unit_price'];
                                                    $total_gst += $expenseList['gst_amount'];
                                                    $sub_total += $net_amount;
                                        ?>
                                            <tr>
                                                <td style="width:20%;">
                                                <input type="hidden" name="update_expense_counter" id="update_expense_counter" value="<?php echo $i; ?>" />  
                                                    <?php
                                                        if(isset($this->expenseAccount) && !empty($this->expenseAccount)) {
                                                            foreach ($this->expenseAccount as $expense) {
                                                                if($expenseList['fkexpense_type']==$expense['id']) {
                                                                    echo $expense['account_name'];
                                                                }
                                                            }
                                                        }
                                                    ?>                                                      
                                                </td>
                                                <td style="width:15%;">
                                                    <?php echo $expenseList['product_id']; ?>
                                                </td>
                                                <td style="width:20%;">
                                                    <?php echo $expenseList['product_description']; ?>
                                                </td>
                                                <td style="width:5%;">
                                                    <?php echo $expenseList['quantity']; ?>
                                                </td>
                                                <td>
                                                   <?php echo number_format($expenseList['unit_price'],2,'.',','); ; ?>
                                                </td>
                                                <td>
                                                    <?php
                                                        if(isset($this->taxCode) && !empty($this->taxCode) && $expenseList['fktax_id']!=0) {
                                                            foreach ($this->taxCode as $tax) {
                                                                if($expenseList['fktax_id']==$tax['id']) {
                                                                  foreach ($this->purchase as $key => $purchase) {
                                                                    if($tax['tax_code']==$key) {
                                                                        echo $purchase['name']." - ".$tax['tax_percentage']." %";
                                                                    }
                                                                  }
                                                                   // echo $tax['tax_code']." - ".$tax['tax_percentage']." %";
                                                                }
                                                            }
                                                        } else {
                                                            echo "NA - Not Applicable";
                                                        }
                                                    ?>                                                  
                                                </td>
                                                <td>
                                                  <?php echo number_format($expenseList['gst_amount'],2,'.',','); ?>
                                                </td>
                                                <td>
                                                    <strong id="net_amount_<?php echo $i; ?>">
                                                    <?php
                                                       // $net_amount = ($expenseList['quantity'] * $expenseList['unit_price']) - $this->expense[0]['discount_amount'];
                                                       // $net_amount -= $this->expense[0]['discount_amount'];
                                                        echo number_format($net_amount,2,'.',',');
                                                    ?>
                                                    </strong>
                                                </td>
                                            </tr>

                                            <?php
                                                    //echo $expenseList['fktax_id'];
                                                     $i++;
                                                    }
                                                }
                                            ?>
                                            <input type="hidden" name="expense_counter" id="expense_counter" />
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                        <hr/>
                        <div class="row">
                            <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Sub Total : </label>
                                    <span id="sub_total"><?php 
                                   $net_total = $sub_total; 
                                   echo number_format($net_total,2,'.',',');
                                   ?></span> <br/>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Total GST : </label>
                                    <span id="total_gst"><?php echo number_format($total_gst,2,'.',','); ?></span>
                             </div>
                        </div>

                            <div class="row">
                            <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Grand Total : </label>
                                    <span id="grand_total"><?php 
                                    $over_all = $net_total+$total_gst; 
                                    echo number_format($over_all,2,'.',',');

                                    ?></span>
                                </div>
                             </div>
                             <div class="row">
                            <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Exchange Rate :</label>
                                   <span><?php echo $this->expense[0]['exchange_rate']; ?></span>
                             </div>
                             </div>
                             <div class="row">
                            <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">SGD GST :</label>
                                   <span><?php echo $this->expense[0]['total_gst']; ?></span>
                             </div>
                             </div>
                            <div class="row">
                            <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Grand Total SGD :</label>
                                    <span id="grand_total_sgd">
                                      <?php 
                                        if($this->expense[0]['total_gst']!=0.00) {
                                          $calculate_all = ($this->expense[0]['exchange_rate']*$net_total)+($this->expense[0]['total_gst']);
                                        } else {
                                          $calculate_all = $this->expense[0]['exchange_rate']*$over_all;
                                        }
                                        echo number_format($calculate_all,2,'.',','); 
                                        if($this->expense[0]['transaction_currency']!='SGD') {
                                          $totAmoumt = $calculate_all;
                                        } else {
                                          $totAmoumt = $over_all;
                                        }
                                    ?>
                                    </span>
                                </div>
                             </div>

</div>


<div class="row">
                         <div class="col-md-6 col-md-offset-5">
                            <div class="square-widget">
                                <h5 class="pull-left"><i class="icon-user-4"></i> Payment Details</h5>
                                <div class="widget-container">
                                    <table class="table responsive">
                                        <thead>
                                            <tr>
                                                <th>
                                                    Date
                                                </th>
                                                <th>
                                                    Payment Method
                                                </th>
                                                <th>
                                                    Bank Cheque / Draft No
                                                </th>
                                                <th style="text-align:right;">
                                                    Amount
                                                </th>
                                              <!--  <th>
                                                    Actions
                                                </th> -->
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php 
                                            $paid_amount = 0.00;   
                                            if(isset($this->expensePayment) && !empty($this->expensePayment)) {                                       
                                            foreach ($this->expensePayment  as $payment) {
                                                $paid_amount += $payment['payment_amount']+$payment['discount_amount'];
                                        ?>
                                            <tr>
                                                <td><?php echo date("d-m-Y",strtotime($payment['date'])); ?></td>
                                                <td>
                                                <?php 
                                                    foreach ($this->payMethod as $key => $pay) {
                                                        if($key==$payment['payment_method']) {
                                                            echo $pay;
                                                        }
                                                    }
                                                 ?>
                                                </td>
                                                <td><?php echo ucfirst($payment['cheque_draft_no']); ?></td>
                                                <td style="text-align:right;"><?php echo number_format($payment['payment_amount']+$payment['discount_amount'],2,'.',','); ?></td>
                                               <!-- <td>
                                                   <?php 
                                                        if($logSession->type!=5) {
                                                   ?>

                                            <a href="javascript:void(0)" onclick="return editPayment('<?php echo $this->exp_id; ?>','<?php echo $payment['id']; ?>','<?php echo $payment['discount_status']; ?>','<?php echo $payment['discount_amount']; ?>','<?php echo $payment['payment_description']; ?>','<?php echo date("d-m-Y",strtotime($payment['date'])); ?>','<?php echo $payment['fkpayment_account']; ?>','<?php echo $payment['payment_amount']; ?>','<?php echo $payment['payment_method']; ?>','<?php echo $payment['cheque_draft_no']; ?>')" data-original-title="Edit Payment" title="Edit Payment"><i class="icon-pencil-2"></i></a>

                                            <a href="javascript:void(0)" onclick="return deletePayment('<?php echo base64_encode($this->exp_id); ?>','<?php echo base64_encode($payment['id']); ?>');" data-original-title="Delete Payment" title="Delete Payment"><i class="icon-remove-2"></i></a>   

                                                    <?php
                                                        }
                                                    ?>                                                 
                                                </td> -->
                                            </tr>
                                        <?php
                                            }
                                            } else {
                                        ?>
                                        <tr>
                                          <td colspan="4"><h5 align="center"><strong>No Payment has been received yet</strong></h5></td>

                                          </tr>
                                        <?php
                                          }
                                        ?>
                                        </tbody>
                                        </table>
                                    </div>
                                </div>
                        </div>
                </div>

                 <div class="row">
                            <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Amount Due :</label>
                                    <span id="total_amount_paid">
                                    <?php 
                                    if($this->expense[0]['payment_status']==1) {
                                      echo "Nil";
                                    } else {
                                    echo number_format($totAmoumt - $paid_amount,2,'.',','); 
                                    }
                                    ?></span>
                                </div>
                             </div>
<script type="text/javascript">
/*
    $(function() {
      gp_convertIt_Onload('<?php echo $over_all; ?>','<?php echo $paid_amount; ?>');
    });*/

function editPayment(Expid,Idvalue,discount_status,discount_amount,description,date,pay_account,pay_amount,pay_method,cheque) {
    $("#expense_id").val(Expid);
    $("#pay_id").val(Idvalue);
    $("#payment_discount").val(discount_status);
    if(discount_status==1) {
        $("#discount_amount").removeAttr("disabled");
    } else {
        $("#discount_amount").attr("disabled","true");
    }
    $("#discount_amount").val(discount_amount);
    $("#description").val(description);
    $("#date").val(date);
    $("#pay_account").val(pay_account);
    $("#pay_amount").val(pay_amount);
    $("#pay_method").val(pay_method);
    $("#cheque_draft_no").val(cheque);
        $('#popup').bPopup({
            modalClose: false,
            easing: 'easeOutBack', 
            speed: 1000,
            transition: 'slideDown',
            follow: [false, false], 
    });
}

function deletePayment(Expid,Idvalue) {
  var confirmMsg = confirm("Are you sure want to delete this payment made for expense? You cannot undo this action");
    if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>transaction/expense/view/delid/'+Idvalue+'/id/'+Expid;
    }
}

function discountPayment(value) {
    if(value==1) {
        $("#discount_amount").removeAttr("disabled");
    } else if(value==2) {
        $("#discount_amount").val("0");
        $("#discount_amount").attr("disabled","true");
    }
}

 function bPopup_close() {
     $("#popup").bPopup().close();
 }

 
 function numberWithCommas(x,action) {
  if(action=='normal') {
    var amount = parseFloat(x).toFixed(2);
    var value = amount.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
    return value;
  } else if(action=='format')  {
    var value  = x.replace(/\,/g,''); 
    return value;
  }
}

/* function gp_convertIt_Onload(amount,paid_amount) {
  if (amount=='' || amount==0){
    return false;
  } else {
  var gp_from = '<?php echo $this->expense[0]['transaction_currency']; ?>';
    if(gp_from!='SGD') {
      var gp_to   = 'SGD';
      var gp_amount = amount;
      $.getJSON( "http://www.geoplugin.net/currency_converter.gp?jsoncallback=?", { from:gp_from, to:gp_to, amount:gp_amount }, 
        function(output){
          $("#grand_total_sgd").html(output.to.symbol+output.to.amount);
          $("#total_amount_paid").html(parseFloat(output.to.amount-paid_amount).toFixed(2));
        });
    } else {
      $("#total_amount_paid").html(numberWithCommas(amount-paid_amount,'normal'));
    }
  }
}*/

 function gp_convertIt_Onload(amount,paid_amount) {
  if (amount=='' || amount==0){
    return false;
  } else {
  var gp_from = '<?php echo $this->expense[0]['transaction_currency']; ?>';
    if(gp_from!='SGD') {
      var gp_to   = 'SGD';
      var gp_amount = amount;
      $.ajax({
        type: "POST",
        url: "<?php echo $this->sitePath.'default/index/convert-currency'; ?>",
        data: 'action=converter&amount='+gp_amount+'&from='+gp_from,
        success: function (html) {
          var convert_amount = numberWithCommas(Number(html),'normal');
          $("#grand_total_sgd").html("$ "+convert_amount);
          $("#total_amount_paid").html(parseFloat(convert_amount-paid_amount).toFixed(2));
        }
      });
    } else {
      $("#total_amount_paid").html(numberWithCommas(amount-paid_amount,'normal'));
    }
  }
}
</script>