<div id="popup">
<span class="button b-close"><span>X</span></span>


<div class="row">
 <h4 style="margin-left:20px;">Disposal</h4>
<div class="widget-container col-md-12 col-md-offset-1">
 <form class="form-horizontal" id="add-payment" method="post">

    <div class="form-group">
      <label class="control-label col-lg-4">Disposal Date <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <input type="hidden" name="ref_id" id="ref_id" value="<?php echo $this->expense[0]['id']; ?>" />
            <input type="text" name="dispose_date" id="dispose_date" class="form-control date-pick" placeholder="Select Date"  autocomplete="off" required value="<?php echo date('d-m-Y'); ?>" />
        </div>
    </div>

    <div class="form-group">
      <label class="control-label col-lg-4">Disposed Amount <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <input type="text" name="dispose_amount" id="dispose_amount" class="form-control amount-align" placeholder="Enter Amount"  autocomplete="off" value="0.00" onchange="return numberWithCommasInput(this.value,this.id);" />
            <input type="hidden" name="netdispose" id="netdispose" />
            <input type="hidden" name="accdepn" id="accdepn" />
            <input type="hidden" name="total" id="total" />
            <input type="hidden" name="dispose_type" id="dispose_type" value="3" />
            <input type="hidden" name="coa_id" id="coa_id" value="<?php echo $this->expense[0]['fa_coa']; ?>" />
            <input type="hidden" name="jlocation" id="jlocation" value="<?php echo $this->expense[0]['fklocation_id']; ?>" />
            <input type="hidden" name="jdescription" id="jdescription" value="<?php echo $this->expense[0]['faid/tag'].' - '.$this->expense[0]['fa_description']; ?>" />
        </div>
    </div>

    <div class="form-group">
    <label class="control-label col-lg-6 col-lg-offset-1"><input type="checkbox" name="receipt_check" id="receipt_check" onclick="return receiptCheck();" />
    <span>Do you want to enter the receipt details now?</span></label>
    </div>

     <div class="form-group receipt-detail" style="display:none;">
      <label class="control-label col-lg-4">Bank / Cash Account <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <select name="bank_coa" id="bank_coa" class="form-control" required>
              <option value="">Select</option>
               <?php
                  if(isset($this->cashAccount) && !empty($this->cashAccount)) {
                      foreach ($this->cashAccount as $cashAccount) {
                ?>
                      <option value="<?php echo $cashAccount['id'] ?>"><?php echo ucwords($cashAccount['account_name']); ?></option>
                <?php
                    }
                 }
               ?>  
            </select>
        </div>
    </div>

    <div class="form-group receipt-detail" style="display:none;">
      <label class="control-label col-lg-4">Refernce No <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <input type="text" name="reference_no" id="reference_no" class="form-control" required />
        </div>
    </div>

    <div class="form-group receipt-detail" style="display:none;">
      <label class="control-label col-lg-4">Description <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <textarea name="bank_description" id="bank_description" class="form-control" required></textarea>
        </div>
    </div>

     <div class="form-group">
        <div class="col-lg-8 col-lg-offset-3">
            <div class="form-actions">
               <input type="submit" name="disposal_submit" class="btn btn-primary " id="disposal_submit" value="Dispose" />
                <button type="reset" class="btn" onclick="return bPopup_close();">Cancel</button>
            </div>
        </div>
     </div>

</form>
</div>
</div>
</div>


<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."transaction/fixedassets/"; ?>">Fixed Assets</a></li>
   <li class="active">Edit</li>
</ul>
<div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            <div class="alert alert-success" id="success" style="display:none;">
            </div>
            <div class="alert alert-danger" id="failure" style="display:none;">
            </div>
            </div>
   </div>
   <?php
    $logSession = new Zend_Session_Namespace('sess_login');
   ?>
   <?php 
       if($logSession->type!=5 && $logSession->proxy_type!=5) {
   ?>
 
     <div class="row">


                        <div class="col-md-12 widget-module">

                            <div class="square-widget widget-collapsible">
                                <div class="widget-head clearfix">
                                    <h4 class="pull-left"><i class="icon-paragraph-justify-2"></i> Edit Fixed Assets Entry</h4>
                                </div>

                                <div class="widget-container col-md-12">
                                <form class="form-horizontal" id="add-fixedassets" method="post">

                                    <?php 

                                    $disabled = '';
                                    $readonly = '';
                                      

                                      if($this->expense[0]['depreciation_till']!=NULL && $this->expense[0]['status']==2) {
                                          $checked  = '';
                                          $disabled = '';
                                          $readonly = '';
                                      } else if($this->expense[0]['depreciation_till']==NULL && $this->expense[0]['status']==2) {
                                          $checked  = 'checked';
                                          $disabled = 'disabled';
                                          $readonly = 'readonly';
                                      } else  if($this->expense[0]['depreciation_till']!=NULL && $this->expense[0]['status']==1) {
                                        $checked  = '';

                                      } else {
                                          $checked  = '';
                                      }

                                      if($this->expense[0]['expense_id']!=0) {
                                        $checkbox = 'disabled';
                                      } else {
                                        $checkbox = '';
                                      }



                                    ?>

                                     <div class="form-group">
                                        <label class="control-label"><input type="checkbox" name="new_asset" id="new_asset" onclick="return newAsset();" class="form-controls"  <?php  echo $checkbox; ?>  <?php echo $checked; ?> />
                                        <span>New Assets?</span></label>
                                      </div>

                                        <div class="form-group">

                                            <div class="col-lg-2">
                                              <label>Date <span class="mandatory">*</span></label>
                                                <input type="text" name="date" id="date" class="form-control date-pick" placeholder="Select Date" value="<?php echo date('d-m-Y',strtotime($this->expense[0]['date'])); ?>" required autocomplete="off" />

                                                <input type="hidden" name="id" id="id" value="<?php echo $this->expense[0]['id']; ?>">

                                                <input type="hidden" name="expense_id" id="expense_id" value="<?php echo $this->expense[0]['expense_id']; ?>">

                                                <input type="hidden" name="submit_type" id="submit_type" value="<?php echo $this->expense[0]['status']; ?>" />

                                                <input type="hidden" name="today" id="today" class="form-control date-pick" value="<?php echo date('d-m-Y', strtotime('last day of previous month')); ?>" />

                                                <?php
                                                  $splitYear = explode('-', $this->fend);
                                                  $fend      = $splitYear[2].'-'.$splitYear[1].'-'.($splitYear[0]-1);
                                                ?>
                                                <input type="hidden" name="fend" id="fend" class="form-control date-pick" value="<?php echo $fend; ?>" />
                                            </div>

                                            <div class="col-lg-3">
                                            <label>Receipt No <span class="mandatory">*</span></label>
                                                <input type="text" name="receipt" id="receipt" class="form-control" placeholder="Enter Receipt No" value="<?php echo $this->expense[0]['receipt_no']; ?>" autocomplete="off" required  />
                                            </div> 

                                            <div class="col-lg-2">
                                             <label>Vendor <span class="mandatory">*</span> </label>
                                             <div id="vendorRefresh">
                                                <select class="select2" name="vendor" id="vendor" required>
                                                    <?php
                                                        if(isset($this->vendor) && !empty($this->vendor)) {
                                                            foreach ($this->vendor as $vendor) {
                                                              $coa = $vendor['coa_link'];
                                                                if($vendor['id']==$this->expense[0]['vendor_id'])
                                                                    $vendorSelect = 'selected';
                                                                else
                                                                    $vendorSelect = '';
                                                    ?>
                                                        <option value="<?php echo $vendor['id']; ?>" <?php echo $vendorSelect; ?> data-coa='<?php echo $coa; ?>'><?php echo ucfirst($vendor['vendor_name']); ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                    
                                                </select>
                                                </div>
                                            </div> 



                                            <div class="col-lg-3">
                                            <label>System generated Ref No <span class="mandatory">*</span></label>
                                                <input type="text" name="expense_no" id="expense_no" class="form-control" placeholder="System generated Ref No" required value="<?php echo $this->expense[0]['exp_ref_no']; ?>" autocomplete="off"  />
                                                
                                            </div> 


                                             <div class="col-lg-2">
                                             <label>Branch <span class="mandatory">*</span></label>
                                                <select class="select2" name="location" id="location" required>
                                                <!-- <option value="">Select</option> -->  
                                                     <?php
                                                        if(isset($this->location) && !empty($this->location)) {
                                                            foreach ($this->location as $location) {
                                                              if($location['id']==$this->expense[0]['fklocation_id']) {
                                                                $locationSelect = 'selected';
                                                              } else {
                                                                $locationSelect = '';
                                                              }
                                                    ?>
                                                        <option value="<?php echo $location['id']; ?>" <?php echo $locationSelect; ?>><?php echo ucwords($location['name']); ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                      
                                                </select>
                                            </div> 
                                             

                                        </div>

                                        <div class="form-group">

                                        <div class="col-lg-3">
                                             <label>FA COA <span class="mandatory">*</span></label>
                                             <select class="form-control" name="fa_coa" id="fa_coa" required onchange="return faYears(this.value);">
                                                    <option value="">Select</option>    
                                                    <?php
                                                        $useful_years = 0;
                                                        if(isset($this->fixedAccount) && !empty($this->fixedAccount)) {
                                                            foreach ($this->fixedAccount as $fixed) {
                                                                $id = $fixed['id'].'_'.$fixed['useful_years_of_life'];
                                                                if($this->expense[0]['fa_coa']==$fixed['id']) {
                                                                    $expenseSelect = 'selected';
                                                                   // $useful_years  = $fixed['useful_years_of_life'];
                                                                }
                                                                else {
                                                                    $expenseSelect = '';
                                                                  }
                                                    ?>
                                                        <option value="<?php echo $id; ?>" <?php echo $expenseSelect; ?>><?php echo ucfirst($fixed['account_name']); ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                      
                                                </select>
                                        </div>

                                         <div class="col-lg-3">
                                            <label>FA Description <span class="mandatory">*</span></label>
                                                <input type="text" name="description" id="description" class="form-control" placeholder="Enter Description" value="<?php echo $this->expense[0]['fa_description']; ?>" required autocomplete="off"  />
                                               
                                         </div>

                                         <div class="col-lg-2">
                                            <label>FA ID/ Tag <span class="mandatory"></span></label>
                                                <input type="text" name="fa_id" id="fa_id" class="form-control" placeholder="Enter FA ID / Tag" autocomplete="off" value="<?php echo $this->expense[0]['faid/tag']; ?>" onchange="checkFaid(this.value,<?php echo $this->expense[0]['id']; ?>);" />
                                                 <label for="fa_id" generated="true" class="error faid_error" style="display:none;"></label>
                                         </div>

                                          <div class="col-lg-2">
                                             <label>FA Life (Years) / % <span class="mandatory">*</span></label>
                                             <select class="form-control" name="fa_years" id="fa_years" required>
                                                    <option value="">Select</option>    
                                                    <?php
                                                        if(isset($this->faYears) && !empty($this->faYears)) {
                                                            foreach ($this->faYears as $key => $faYear) {
                                                              if($key==$this->expense[0]['fa_life']) 
                                                                    $faSelect = 'selected';
                                                                else 
                                                                    $faSelect = '';
                                                    ?>
                                                        <option value="<?php echo $key ?>" <?php echo $faSelect ?>><?php echo $faYear; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                      
                                                </select>
                                        </div>

                                        <div class="col-lg-2">
                                             <label>Depreciation Frequency <span class="mandatory">*</span></label>
                                             <select class="form-control" name="frequency" id="frequency" required>
                                                    <option value="">Select</option>    
                                                    <?php
                                                        if(isset($this->faFrequency) && !empty($this->faFrequency)) {
                                                            foreach ($this->faFrequency as $key => $frequency) {
                                                              if($key==$this->expense[0]['frequency']) 
                                                                    $frSelect = 'selected';
                                                                else 
                                                                    $frSelect = '';
                                                    ?>
                                                        <option value="<?php echo $key ?>" <?php echo $frSelect ?>><?php echo $frequency; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                      
                                                </select>
                                        </div>



                                        </div>    

                                        <div class="form-group">

                                        <?php
                                            //$this->expense[0]['disposal_amount'] = 9000;
                                           // $this->expense[0]['pl_amount'] = 250;
                                            $purchase_price = $this->expense[0]['purchase_price'];
                                            $accumulated    = ($this->accumulated+$this->expense[0]['accumulated_depreciation']);
                                            $disposal       = $this->expense[0]['disposal_amount'];
                                            $profit_loss    = $this->expense[0]['pl_amount'];
                                            $netbookvalue   = $purchase_price-$accumulated-$disposal+($profit_loss);


                                        ?>

                                          <div class="col-lg-2">
                                          <label>Purchase Price <span class="mandatory">*</span></label>
                                          <input type="text" name="purchase_price" id="purchase_price" class="form-control amount-align" required number="true"  value="<?php echo number_format($purchase_price,2,'.',','); ?>"  autocomplete="off" onchange="return numberWithCommasInput(this.value,this.id);" onkeyup="return netBook();" />
                                          </div>

                                     <?php
                                        if($this->expense[0]['status']!=1) {
                                     ?>

                                          <div class="col-lg-2">
                                              <label>Depreciation Till </label>
                                                <input type="text"  name="depreciation_date" id="depreciation_date" class="form-control date-pick" placeholder="Select Date" value="<?php if($this->expense[0]['depreciation_till']!=NULL) { echo date('d-m-Y',strtotime($this->expense[0]['depreciation_till'])); } ?>" required autocomplete="off"  <?php echo $disabled; ?>/>

                                                
                                            </div>

                                      <?php
                                          }
                                      ?>

                                          <div class="col-lg-2">
                                          <label>Accumulated Depreciation <span class="mandatory">*</span></label>
                                          <input type="text" name="accumulated_depreciation" id="accumulated_depreciation" class="form-control amount-align"  number="true"  value="<?php echo number_format($accumulated,2,'.',','); ?>"  autocomplete="off" onchange="return numberWithCommasInput(this.value,this.id);" onkeyup="return netBook();"  <?php  echo $readonly; ?> />
                                          </div>


                                          <div class="col-lg-2">
                                          <label>Disposal <span class="mandatory"></span></label>
                                          <input type="text" name="disposal" id="disposal" class="form-control amount-align"  number="true"  value="<?php echo number_format($disposal,2,'.',','); ?>"  autocomplete="off" onchange="return numberWithCommasInput(this.value,this.id);" readonly />
                                          </div>

                                          <div class="col-lg-2">
                                          <label>Net Book Value <span class="mandatory"></span></label>
                                          <input type="text" name="netbookvalue" id="netbookvalue" class="form-control amount-align"  number="true"  value="<?php echo number_format($netbookvalue,2,'.',','); ?>"  autocomplete="off" onchange="return numberWithCommasInput(this.value,this.id);" readonly />
                                          </div>

                                          <div class="col-lg-2">
                                          <label>Profit / Loss on Disposal <span class="mandatory"></span></label>
                                          <input type="text" name="pl_disposal" id="pl_disposal" class="form-control amount-align"  number="true"  value="<?php echo number_format($profit_loss,2,'.',','); ?>"  autocomplete="off" onchange="return numberWithCommasInput(this.value,this.id);" readonly />
                                          </div>

                                    <?php
                                        if($this->expense[0]['status']==1) {
                                     ?>

                                            <div class="col-lg-2">
                                              <label>Disposal Date <span class="mandatory"></span></label>
                                                <input type="text" name="dispdate" id="dispdate" class="form-control" placeholder="Select Date" value="<?php if($this->expense[0]['disposal_date']!=NULL) { echo date('d-m-Y',strtotime($this->expense[0]['disposal_date'])); } ?>"  autocomplete="off" readonly />

                                            </div>

                                     <?php
                                        }
                                     ?>


                                        </div>                                    


      

                             <div class="form-group">
                                     <?php
                                        if($this->expense[0]['status']!=1 && $this->expense[0]['status']!=3) {
                                     ?>
                                    <div class="col-lg-1">
                                         <div class="form-actions">
                                            <input type="submit" name="add_fixed_assets" class="add_fixed_assets btn btn-primary" id="add_fixed_assets" value="Add / Save"  /><br/>
                                            <i>Save Fixed Assets</i>
                                          </div>
                                      </div>
                                      <?php 
                                              if($logSession->type!=4 && $logSession->type!=5 && $logSession->proxy_type!=4 && $logSession->proxy_type!=5) {
                                      ?>
                                       <div class="col-lg-1" style="margin-left:10px;">
                                         <div class="form-actions">
                                            <input type="submit" name="approve_journal" class="btn btn-primary approve_fixed_assets" id="approve_journal" value="Approve" /><br/>
                                            <i>Once approved cannot be edited</i>
                                            </div>
                                         </div>
                                       <?php
                                                }
                                              }
                                        ?>

                                     <?php
                                        if($this->expense[0]['status']==1 && $this->expense[0]['status']!=3) {
                                     ?>

                                     <div class="col-lg-1">
                                         <div class="form-actions">
                                            <input type="button" name="depn_sch" class="btn btn-warning" id="depn_sch" value="View Depn Sch" onclick="return showSchedule();"  /><br/>
                                          </div>
                                      </div>


                                     <div class="col-lg-1" style="margin-left:20px;">
                                         <div class="form-actions">
                                            <input type="button" name="dispose_fa" class="btn btn-danger" id="dispose_fa" value="Dispose FA"  onclick="return disposeAmount();"/><br/>
                                          </div>
                                      </div>


                                     <?php
                                        }
                                     ?>


                                         <div class="col-lg-1" style="margin-left:0px;">
                                         <div class="form-actions">
                                         <a href="<?php echo $this->sitePath."transaction/fixedassets"; ?>">
                                            <button type="button" class="btn">Cancel</button>
                                         </a>
                                            </div>
                                         </div>
                                    </div>

                               

                                </form>
                                    
                                </div>
                            </div>
                        </div>

                        <?php
                            if($this->expense[0]['status']==1 && $this->expense[0]['status']!=3) {
                        ?>
                        <div class="col-md-3" id="depn_schedule" style="display:none;">

                          <div class="square-widget">
                                  <h5 class="pull-left"><i class="icon-clock-2"></i> Depreciation Schedule</h5>
                                  <div class="widget-container">
                                      <table class="table responsive">
                                          <thead>
                                              <tr>
                                                  <th>
                                                      Date
                                                  </th>
                                                  <th style="text-align:right;">
                                                      Amount
                                                  </th>
                                              </tr>
                                          </thead>
                                          <tbody>

                                          <?php 
                                            foreach($this->depnsch as $depn) {
                                              if($depn['status']==1) {
                                                $color = '#5cb85c';
                                              } else if($depn['status']==2) {
                                                $color = '#d9534f';
                                              }
                                          ?>

                                            <tr style="color:<?php echo $color; ?>; font-weight:bold;">
                                              <td><?php echo date('d-m-Y',strtotime($depn['date'])); ?></td>
                                              <td style="text-align:right;"><?php echo number_format($depn['amount'],2,'.',','); ?></td>
                                            </tr>

                                          <?php
                                            }
                                          ?>


                                          </tbody>
                                      </table>

                                  </div>
                            </div>
                          

                        </div>


                        <?php

                            }

                        ?>


                    </div>
     
   <?php 
        }
    ?>
<script type="text/javascript">

 $(document).ready(function(){

    <?php 
      if($this->expense[0]['status']!=2) {
    ?>

      $('.form-control').attr('disabled','disabled');
      $('.form-controls').attr('disabled','disabled');

    <?php
      }
    ?>

 });

 function netBook() {
  var price = $('#purchase_price').val();
  if($("#new_asset").is(':checked')) {
    var accDepn = 0.00;
    var amount = numberWithCommas(price,'format');
  } else {
    var accDepn = $('#accumulated_depreciation').val();
    var amount = numberWithCommas(price,'format')-numberWithCommas(accDepn,'format');
  }
  
  var netAmount = numberWithCommas(amount,'normal');
  $('#netbookvalue').val(netAmount);

}

function newAsset() {
  if($("#new_asset").is(':checked')) {
    $("#accumulated_depreciation").attr('readonly','readonly');
    $("#depreciation_date").attr('disabled','disabled');
  } else {
    $("#accumulated_depreciation").removeAttr('readonly');
    $("#depreciation_date").removeAttr('disabled'); 
  }
}

 function numberWithCommas(x,action) {
  if(action=='normal') {
    var amount = parseFloat(x).toFixed(2);
    var value = amount.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
    return value;
  } else if(action=='format')  {
    var value  = x.replace(/\,/g,''); 
    //alert(value);
    return value;
  }
}

 function numberWithCommasInput(x,id) {
    //return false;
    if(id=='') {
        var x = x.replace(",","");
        var amount = parseFloat(x).toFixed(2);
        var value  = amount.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
        return value;
    } else {
        var x = x.replace(",","");
        var amount = parseFloat(x).toFixed(2);
        var value  = amount.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
        $("#"+id).val(value);
    }
}


function faYears(value) {
  //alert(value);
  if(value!='') {
    var splitted = value.split('_');
    $("#fa_years").val(splitted[1]);
  } else {
    $("#fa_years").val('');
  }
}

function showSchedule() {
  $('#depn_schedule').slideToggle(1000);
} 

  function disposeAmount() {
    $("#dispose_date").removeAttr('disabled');
    $("#dispose_amount").removeAttr('disabled');
    $("#bank_coa").removeAttr('disabled');
    $("#bank_description").removeAttr('disabled');
    $("#reference_no").removeAttr('disabled');
    var netDispose = $("#netbookvalue").val();
    $("#netdispose").val(netDispose);
    var accDepn = $("#accumulated_depreciation").val();
    $("#accdepn").val(accDepn);
    var total = $("#purchase_price").val();
    $("#total").val(total);
    $('#popup').bPopup({
            modalClose: false,
            easing: 'easeOutBack', 
            speed: 1000,
            transition: 'slideDown',
            follow: [false, false], 
    });
  }

  function bPopup_close() {
    $("#popup").bPopup().close();
 }

   function receiptCheck() {
    if($("#receipt_check").is(':checked')) {
      $(".receipt-detail").show();
    } else {
      $(".receipt-detail").hide();
    }
  }



  function checkFaid(value,id) {
        if((value!='')) {
            $.ajax({
              type: "POST",
              url: "<?php echo $this->sitePath.'transaction/fixedassets/ajax-refresh'; ?>",
              data: 'action=check_faid_update&faid='+value+'&id='+id,
              success: function (html) {
                  if(html=='1') {
                     $(".faid_error").html("");
                     $(".faid_error").hide();
                     return true;
                  } else if(html=='2') {
                     $(".faid_error").html("FA ID / Tag "+ value +" already exists");
                     $("#fa_id").val("");
                     $(".faid_error").show();
                  }
              }
            }); 
        } 
  }

</script>
