        <div class="main-wrapper">
            <!-- TOP BAR -->
            <div class="top-bar">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4">
                            <!-- LOGO -->
                            <div class="branding">
                                 <a href="<?php echo $this->sitePath."index"; ?>" style="color: #FFF;
font-size: 20px;">Pinnacle One Accounting<!-- <img src="<?php echo $this->imagesPath; ?>logo.png" alt="Alpona Logo"> --></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>