<?php
  $logSession = new Zend_Session_Namespace('sess_login');

  function convertCurrency($amount, $from){
    $to   = 'SGD';
      $url  = "https://www.google.com/finance/converter?a=$amount&from=$from&to=$to";
      $data = file_get_contents($url);
      preg_match("/<span class=bld>(.*)<\/span>/",$data, $converted);
      $converted = preg_replace("/[^0-9.]/", "", $converted[1]);
      return round($converted, 3);
  }
?>
<div id="popup">
<span class="button b-close"><span>X</span></span>
<div class="row" id="add_receipt" style="display:none;">
<h4>Add Receipts</h4>
<div class="widget-container col-md-12 col-md-offset-1">
 <form class="form-horizontal" id="add-receipt" method="post">
<div class="form-group">
    <label class="control-label col-lg-4">Receipts <span class="mandatory">*</span></label>
      <div class="col-lg-5" id="receipt_add">
        <select name="receipts" id="receipts"  class="form-control" required>
        <option value="">Select</option>
         <?php
            foreach ($this->receipts as $receipt) {
              if($this->income[0]['fkcustomer_id']==$receipt['fkbusiness_id']) {
                  $id   = $receipt['id']."-".$receipt['name']."-".$receipt['receipt'];
                  $name = $receipt['name'];
                  if($this->income[0]['fkreceipt_id']==$receipt['id'])
                    $receiptSelect = 'selected';
                  else
                    $receiptSelect = '';
         ?>
           <option value="<?php echo $id; ?>" <?php echo $receiptSelect; ?>><?php echo $name; ?></option>
         <?php
                }
            }
         ?>
         </select>
      </div>
</div>
   <div class="form-group">
        <div class="col-lg-8 col-lg-offset-3">
            <div class="form-actions">
               <input type="button" name="attach_receipts" class="btn btn-primary " id="attach_receipts" value="Attach Receipt" onclick="return addReceipt();" />
                <button type="reset" class="btn" onclick="return bPopup_close();">Cancel</button>
            </div>
        </div>
     </div>
</form>
</div>
</div>
</div> 

<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."transaction/income/"; ?>">Income</a></li>
   <li class="active">Copy</li>
</ul>

  <div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            <div class="alert alert-success" id="success" style="display:none;">
            </div>
            <div class="alert alert-danger" id="failure" style="display:none;">
            </div>
            </div>
   </div>

 

     <div class="row">
 

                        <div class="col-md-12 widget-module">

                            <div class="square-widget widget-collapsible">
                                <div class="widget-head clearfix">
                                    <h4 class="pull-left"><i class="icon-paragraph-justify-2"></i> Copy Income Transaction</h4>

                                </div>

                                <div class="widget-container col-md-12">

                                <form class="form-horizontal" id="add-income" method="post" enctype="multipart/form-data">
                                        <div class="form-group">

                                             <div class="col-lg-2">
                                             <label>Branch <span class="mandatory">*</span></label>
                                                <select class="select2" name="location" id="location" required>
                                                <!-- <option value="">Select</option> -->  
                                                     <?php
                                                        if(isset($this->location) && !empty($this->location)) {
                                                            foreach ($this->location as $location) {
                                                              if($location['id']==$this->income[0]['fklocation_id']) {
                                                                $locationSelect = 'selected';
                                                              } else {
                                                                $locationSelect = '';
                                                              }
                                                    ?>
                                                        <option value="<?php echo $location['id']; ?>" <?php echo $locationSelect; ?>><?php echo ucwords($location['name']); ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                      
                                                </select>
                                            </div> 

                                            <div class="col-lg-3">
                                              <label>Date <span class="mandatory">*</span></label>
                                                <input type="text" name="date" id="date" class="form-control date-pick" placeholder="Select Date" value="<?php echo date('d-m-Y',strtotime($this->income[0]['date'])); ?>" />
                                                <input type="hidden" name="transaction_status" id="transaction_status" value="<?php echo $this->income[0]['transaction_status']; ?>">
                                            </div>
                                             
                                            <div class="col-lg-3">
                                            <label>Receipt No <span class="mandatory">*</span></label>
                                                <input type="text" name="receipt" id="receipt" class="form-control" placeholder="Enter Receipt No" onchange="checkReceipt(this.value);" />
                                                <label for="receipt" generated="true" class="error receipt_error" style="display:none;"></label>
                                            </div>    
                                            <div class="col-lg-2">
                                             <label>Customer / Payee <span class="mandatory">*</span> <a href="javascript:void(0)" title="Refresh List" data-title="Refresh List" target="_blank" onclick="return refreshList(1);"  class="customer-refresh" style="margin-left:0px;"><i class="icon-refresh"></i></a></label>
                                             <div id="customerRefresh">
                                                <select class="select2" name="customer" id="customer">
                                                    <?php
                                                        if(isset($this->customer) && !empty($this->customer)) {
                                                            foreach ($this->customer as $customer) {
                                                              $coa = $customer['coa_link'];
                                                                if($customer['id']==$this->income[0]['fkcustomer_id'])
                                                                    $customerSelect = 'selected';
                                                                else
                                                                    $customerSelect = '';
                                                    ?>
                                                        <option value="<?php echo $customer['id']; ?>" <?php echo $customerSelect; ?> data-coa='<?php echo $coa; ?>'><?php echo $customer['customer_name']; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                    
                                                </select>
                                              </div>
                                                <?php 
                                                      if($logSession->type!= 5 && $logSession->proxy_type!= 5) {
                                                 ?>
                                                <a href="<?php echo $this->sitePath."business/customer/add"; ?>" title="Click to add new customer" data-title="Click to add new customer" target="_blank" id="add-customer"><i class="icon-plus-circle-2"></i> Add New Customer</a>
                                                <?php
                                                        }
                                                ?>
                                            </div> 
                                           
                                            <div class="col-lg-2">
                                             <label>Credit Term <span class="mandatory">*</span></label>
                                                <select class="form-control" name="credit_term"  id="credit_term" onchange="triggerPayment();">
                                                    <?php
                                                        if(isset($this->creditTerm) && !empty($this->creditTerm)) {
                                                            foreach ($this->creditTerm as $key => $credit) {
                                                               if($key!=1) {
                                                                    $credits = $credit." Days";
                                                                } else {
                                                                    $credits = $credit;
                                                                }
                                                                if($key==$this->income[0]['credit_term'])
                                                                    $creditSelect = 'selected';
                                                                else
                                                                    $creditSelect = '';
                                                    ?>
                                                        <option value="<?php echo $key; ?>" <?php echo $creditSelect; ?>><?php echo $credits; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                       
                                                </select>
                                            </div> 



                                        </div>

                                        <div class="form-group">

                                        
                                             <div class="col-lg-2">
                                             <label>Currency <span class="mandatory">*</span></label>
                                                <select class="select2" name="currency" id="currency" onchange="return calculateTotal();">
                                                     <?php
                                                        if(isset($this->currencies) && !empty($this->currencies)) {
                                                            foreach ($this->currencies as $key => $currency) {
                                                                if($key==$this->income[0]['transaction_currency']) 
                                                                    $currencySelect = "selected";
                                                                else
                                                                    $currencySelect = "";
                                                    ?>
                                                        <option value="<?php echo $key; ?>" <?php echo $currencySelect; ?>><?php echo $currency; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                      
                                                </select>
                                            </div> 


                                            <div class="col-lg-2">
                                             <label>Type of Income <span class="mandatory">*</span> <a href="javascript:void(0)" title="Refresh List" data-title="Refresh List" target="_blank" onclick="return refreshList(3);"  class="incomeaccount-refresh" style="margin-left:0px;"><i class="icon-refresh"></i></a></label>
                                              <div id="incomeRefresh">
                                                <select class="form-control" name="income_type">
                                                    <?php
                                                        if(isset($this->incomeAccount) && !empty($this->incomeAccount)) {
                                                            foreach ($this->incomeAccount as $income) {
                                                                if($income['id']==$this->income[0]['fkincome_type']) 
                                                                    $incomeSelect = "selected";
                                                                else
                                                                    $incomeSelect = "";
                                                    ?>
                                                        <option value="<?php echo $income['id']; ?>" <?php echo $incomeSelect; ?>><?php echo $income['account_name']; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                      
                                                </select>
                                              </div>
                                                <?php 
                                                      if($logSession->type!= 5 && $logSession->proxy_type!= 5) {
                                                 ?>
                                                <a href="<?php echo $this->sitePath."settings/account"; ?>" title="Click to add new income" data-title="Click to add new income" target="_blank" id="add-incomeaccount"><i class="icon-plus-circle-2"></i> Add New Income</a>
                                                <?php
                                                        }
                                                ?>
                                            </div> 

                                            <div class="col-lg-4">
                                            <label>Description <span class="mandatory">*</span></label>
                                                <input type="text" name="description" id="description" class="form-control" placeholder="Enter Description" value="<?php echo $this->income[0]['transaction_description']; ?>">
                                            </div> 

                                            <div class="col-lg-2">
                                            <label>Amount <span class="mandatory">*</span></label>
                                                <input type="text" name="amount" id="amount" class="form-control amount-align"  value="<?php echo number_format($this->income[0]['amount'],2,'.',','); ?>"  onchange="return numberWithCommas(this.value,this.id);">
                                            </div> 

                                             <div class="col-lg-2">
                                             <label>Tax Code </label>
                                                <select class="form-control" name="tax_code" id="tax_code" onchange="return calculateTotal();">
                                                    <option value="0" title="Not Applicable">NA</option>     
                                                    <?php
                                                        if(isset($this->taxCode) && !empty($this->taxCode)) {
                                                            foreach ($this->taxCode as $tax) {
                                                                if($tax['id']==$this->income[0]['fktax_id']) 
                                                                    $taxSelect = "selected";
                                                                else
                                                                    $taxSelect = "";
                                                            foreach ($this->supply as $key => $supply) {
                                                                if($tax['tax_code']==$key) {
                                                                  $code = $supply['name'];
                                                                }
                                                              }
                                                    ?>
                                                        <option value="<?php echo $tax['id']."_".$tax['tax_percentage']; ?>" <?php echo $taxSelect; ?> title="<?php echo ucfirst($tax['description']); ?>"><?php echo $code." - ".$tax['tax_percentage']." %"; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                  
                                                </select>
                                            </div> 

                                        </div>

                                        <div class="form-group">

                                           <div class="col-lg-2">
                                            <label>GST Amount <!-- <span class="mandatory">*</span> --></label>
                                                <input type="text" name="gst_amount" id="gst_amount" class="form-control amount-align" autocomplete="off" number="true"  value="<?php echo number_format($this->income[0]['gst_amount'],2); ?>" onchange="return numberWithCommass(this.value,this.id);" <?php if($this->income[0]['fktax_id']==0) { echo "readonly"; } ?> />
                                            </div> 

                                          </div>

                    <div class="form-group">
                     <div class="col-lg-3">
                     <label>Attach Invoice or Receipt </label><br/>
                        <!-- <input type="file" name="file" id="file" class="btn" /> -->
                        <input type="button" class="btn btn-info" value="Choose File" id="file" name="file">
                     </div>
                      <div class="col-lg-3 attach_file" style="display:none;">
                       <label>Attached File : </label> <br/>
                       <input type="hidden" name="attached_file" id="attached_file" />
                         <div class="view_remove_file" style="display:none;">
                          
                         </div>
                     </div>

                    </div>

                  <div class="row">
                  <div class="col-lg-2">
                    <div class="progress progress-striped active" id="progress-bar" style="display:none;">
                        <div style="width: 100%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="10" role="progressbar" class="progress-bar progress-bar-success">
                            <span class="sr-only"></span>
                        </div>
                    </div>
                  </div>
                  </div>

                    <hr/>
                  <?php
                     if($this->income[0]['gst_amount']!=0.00) {
                       $tax_amount     = $this->income[0]['gst_amount'];
                     } else {
                       $tax_amount     = ($this->income[0]['amount'] * $this->income[0]['tax_value'] / 100);
                     }
                     $total_amount   = $this->income[0]['amount'] + $tax_amount;
                     if($this->income[0]['transaction_currency']!='SGD') {
                        $converted_amount = $total_amount*$this->income[0]['exchange_rate'];
                      } else {
                        $converted_amount = $total_amount;
                      }
                    // $pending_amount =  $converted_amount - $paid_amount;
                ?>
                  <div class="form-group">
                            <div class="col-lg-4 col-md-offset-10">
                              <div class="form-group">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Sub Total :</label>
                                   <div class="col-lg-4">
                                    <span id="sub_total"><?php echo number_format($this->income[0]['amount'],2,'.',','); ?></span>
                                </div>
                             </div>
                             <div class="form-group">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Total GST :</label>
                                   <div class="col-lg-4">
                                    <span id="total_gst"><?php echo number_format($tax_amount,2,'.',','); ?></span>
                                </div>
                             </div>
                             <div class="form-group">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Grand Total :</label>
                                   <div class="col-lg-4">
                                    <span id="grand_total"><?php echo number_format($total_amount,2,'.',','); ?></span>
                                </div>
                             </div>
                             <div class="form-group">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Exchange Rate :</label>
                                   <div class="col-lg-4">
                                    <input type="text" name="exchange_rate" id="exchange_rate" class="form-control" style="width:65%; height:30px;" number="true" onchange="return originalRate(this.value);" autocomplete="off" value="<?php echo $this->income[0]['exchange_rate']; ?>" />
                                    
                                </div>
                             </div>
                             <div class="form-group">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Grand Total SGD :</label>
                                   <div class="col-lg-4">
                                    <input type="hidden" name="foreign_currency" id="foreign_currency" />
                                    <span id="grand_total_sgd"><?php echo number_format($converted_amount,2,'.',','); ?></span>
                                </div>
                             </div>

                            </div>
                        </div>


<?php
  if($this->income[0]['credit_term']==1) {
?>



<div class="row" id="trigger_payment">
 <h4>Add Payment</h4>
    <div class="form-group">
     
        <div class="col-lg-2">
         <label>Payment Date <span class="mandatory">*</span></label>
            <input type="text" name="addpay_date" required id="addpay_date" class="form-control date-pick" placeholder="Select Date"  autocomplete="off" value="<?php echo date('d-m-Y'); ?>" />
        </div>
      
        <div class="col-lg-3">
        <label>Cash / Bank Account <span class="mandatory">*</span></label>
          <div id="add_pay_account_cash">
             <select class="form-control" name="addpay_pay_account" id="addpay_pay_account" required>
                <!-- <optgroup label="Cash and Cash Equivalents"> -->
                    <?php
                        if(isset($this->cashAccount) && !empty($this->cashAccount)) {
                            foreach ($this->cashAccount as $cash) {
                    ?>
                        <option value="<?php echo $cash['id']; ?>"><?php echo $cash['account_name']; ?></option>
                    <?php
                            }
                        }
                    ?>     
                </optgroup>                                                
              </select>
          </div>
        </div>
     
        <div class="col-lg-2">
         <label>Amount <span class="mandatory">*</span></label>
            <input type="text" name="addpay_pay_amount" id="addpay_pay_amount" class="form-control amount-align" required number="true" autocomplete="off"  onchange="return numberWithCommas(this.value,this.id);"  />
            <input type="hidden" name="addpay_pending_amount" id="addpay_pending_amount" class="form-control" autocomplete="off"   />
        </div>

      
        <div class="col-lg-2">
        <label>Payment Method <span class="mandatory">*</span></label>
          <select name="addpay_pay_method" id="addpay_pay_method" class="form-control" required>
            <option value="">Select</option>
           <?php 
                foreach ($this->payMethod as $key => $pay) {
           ?>
                <option value="<?php echo $key; ?>"><?php echo $pay; ?></option>
           <?php
                }
           ?>
          </select>
        </div>

        <div class="col-lg-2">
         <label>Bank Cheque / Draft No </label>
            <input type="text" name="addpay_cheque_draft_no" id="addpay_cheque_draft_no" class="form-control" placeholder="Enter Cheque / Draft No"  autocomplete="off"  />
        </div>
    </div>
    <div class="form-group">
     
        <div class="col-lg-2">
        <label>Prompt Payment Discount <span class="mandatory">*</span></label>
            <select class="form-control" name="addpay_payment_discount" id="addpay_payment_discount" onchange="discountTriggerPayment(this.value);">
                <option value="1">Yes</option>  
                <option value="2" selected>No</option>  
            </select>
        </div>

      
        <div class="col-lg-2">
        <label>Discount Amount <span class="mandatory">*</span></label>
            <input type="text" name="addpay_discount_payment_amount" id="addpay_discount_payment_amount" class="form-control amount-align" value="0" disabled  autocomplete="off"  onchange="return numberWithCommas(this.value,this.id);" />
        </div>

      
        <div class="col-lg-6">
        <label>Additional Description / Notes </label>
        <textarea name="addpay_description" id="addpay_description" class="form-control"></textarea>
        <input type="hidden" name="payment_trigger" id="payment_trigger" value="1" />
        </div>

    <div class="col-lg-3">
      <label><input type="checkbox" name="add_payment_status" id="add_payment_status" value="1" /> <span>Check this to confirm the full payment received</span> </label>
        
    </div>

    </div>


</div>


<?php 
  } else {
?>        




<div class="row" id="trigger_payment" style="display:none;">
 <h4>Add Payment</h4>
    <div class="form-group">
     
        <div class="col-lg-2">
         <label>Payment Date <span class="mandatory">*</span></label>
            <input type="text" name="addpay_date" required id="addpay_date" class="form-control date-pick" placeholder="Select Date"  autocomplete="off" value="<?php echo date('d-m-Y'); ?>" />
        </div>
      
        <div class="col-lg-3">
        <label>Cash / Bank Account <span class="mandatory">*</span></label>
          <div id="add_pay_account_cash">
             <select class="form-control" name="addpay_pay_account" id="addpay_pay_account" required>
                <!-- <optgroup label="Cash and Cash Equivalents"> -->
                    <?php
                        if(isset($this->cashAccount) && !empty($this->cashAccount)) {
                            foreach ($this->cashAccount as $cash) {
                    ?>
                        <option value="<?php echo $cash['id']; ?>"><?php echo $cash['account_name']; ?></option>
                    <?php
                            }
                        }
                    ?>     
                </optgroup>                                                
              </select>
          </div>
        </div>
     
        <div class="col-lg-2">
         <label>Amount <span class="mandatory">*</span></label>
            <input type="text" name="addpay_pay_amount" id="addpay_pay_amount" class="form-control amount-align" required number="true" autocomplete="off"  onchange="return numberWithCommas(this.value,this.id);"  />
            <input type="hidden" name="addpay_pending_amount" id="addpay_pending_amount" class="form-control" autocomplete="off"   />
        </div>

      
        <div class="col-lg-2">
        <label>Payment Method <span class="mandatory">*</span></label>
          <select name="addpay_pay_method" id="addpay_pay_method" class="form-control" required>
            <option value="">Select</option>
           <?php 
                foreach ($this->payMethod as $key => $pay) {
           ?>
                <option value="<?php echo $key; ?>"><?php echo $pay; ?></option>
           <?php
                }
           ?>
          </select>
        </div>

        <div class="col-lg-2">
         <label>Bank Cheque / Draft No </label>
            <input type="text" name="addpay_cheque_draft_no" id="addpay_cheque_draft_no" class="form-control" placeholder="Enter Cheque / Draft No"  autocomplete="off"  />
        </div>
    </div>
    <div class="form-group">
     
        <div class="col-lg-2">
        <label>Prompt Payment Discount <span class="mandatory">*</span></label>
            <select class="form-control" name="addpay_payment_discount" id="addpay_payment_discount" onchange="discountTriggerPayment(this.value);">
                <option value="1">Yes</option>  
                <option value="2" selected>No</option>  
            </select>
        </div>

      
        <div class="col-lg-2">
        <label>Discount Amount <span class="mandatory">*</span></label>
            <input type="text" name="addpay_discount_payment_amount" id="addpay_discount_payment_amount" class="form-control amount-align" value="0" disabled  autocomplete="off"  onchange="return numberWithCommas(this.value,this.id);" />
        </div>

      
        <div class="col-lg-6">
        <label>Additional Description / Notes </label>
        <textarea name="addpay_description" id="addpay_description" class="form-control"></textarea>
        <input type="hidden" name="payment_trigger" id="payment_trigger" value="0" />
        </div>

    <div class="col-lg-3">
      <label><input type="checkbox" name="add_payment_status" id="add_payment_status" value="1" /> <span>Check this to confirm the full payment received</span> </label>
        
    </div>

    </div>


</div>

<?php
  }
?>                


                                 <div class="form-group">
                                    <div class="col-lg-1">
                                         <div class="form-actions">
                                            <input type="hidden" name="action" id="action" value="save_draft_income" />
                                            <input type="button" name="save_draft_income" class="btn btn-primary" id="save_draft_income" value="Save as Draft" onclick="return saveDraft();" /><br/>
                                            <i>Save Draft Income</i>
                                          </div>
                                      </div>
                                       <div class="col-lg-3" style="margin-left:10px;">
                                        <div class="form-actions">
                                            <select class="form-control" name="approval_for" id="approval_for">
                                            <option value="">For Approval</option>
                                                        <?php
                                                            if(isset($this->approveUser) && !empty($this->approveUser)) {
                                                                foreach ($this->approveUser as $approve) {
                                                                  if($approve['account_type']==2) {
                                                                     $account_type = "Super User";
                                                                  } else if($approve['account_type']==3) {
                                                                     $account_type = "Manager";
                                                                  }
                                                                  if($approve['account_type']==3 && ($approve['id']==$logSession->id || $approve['id']==$logSession->proxy_id)) {
                                                                     } else {
                                                                  if($approve['id']==$this->income[0]['approval_for']) 
                                                                    $approveSelect = 'selected';
                                                                  else
                                                                    $approveSelect = '';
                                                        ?>
                                                            <option value="<?php echo $approve['id']; ?>" <?php echo $approveSelect; ?>><?php echo $approve['username']." - ".$account_type; ?></option>
                                                        <?php
                                                                }
                                                                }
                                                            }
                                                        ?>                                                      
                                                    </select>
                                          </div>
                                          
                                      </div>
                                      <div class="col-lg-1">
                                          <div class="form-actions">
                                            <input type="submit" name="unapprove_save" class="btn btn-primary add_approve_income_transaction" id="unapprove_save" value="For Approval" /><br/>
                                            <i>Save Income for approval</i>
                                          </div>
                                      </div>
                                      <?php 
                                            if($logSession->type!=4 && $logSession->type!=5 && $logSession->proxy_type!=4 && $logSession->proxy_type!=5) {
                                        ?>
                                       <div class="col-lg-1" style="margin-left:10px;">
                                         <div class="form-actions">
                                            <input type="submit" name="approve_income" class="btn btn-primary add_income_transaction" id="approve_income" value="Approve" /><br/>
                                            <i>Approve Income for account posting</i>
                                            </div>
                                         </div>
                                        <?php
                                                }
                                        ?>
                                         <div class="col-lg-1" style="margin-left:5px;">
                                         <div class="form-actions">
                                         <a href="<?php echo $this->sitePath."transaction/income"; ?>">
                                            <button type="button" class="btn">Cancel</button>
                                        </a>
                                            </div>
                                         </div>
                                    </div>
                                 

                                </form>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                <?php
                     $tax_amount     = ($this->income[0]['amount'] * $this->income[0]['tax_value'] / 100);
                     $total_amount   = $this->income[0]['amount'] + $tax_amount;
                     if($this->income[0]['transaction_currency']!='SGD') {
                        $converted_amount = convertCurrency($total_amount,$this->income[0]['transaction_currency']);
                      } else {
                        $converted_amount = $total_amount;
                      }
                ?>

                 <div class="row">
                        <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Total Amount :</label>
                                    <span id="">
                                    <?php  echo number_format($converted_amount,2,'.',','); ?>
                                    </span>
                                </div>
                               

                             </div>
<script type="text/javascript" src="<?php echo $this->scriptpath.'SimpleAjaxUploader.min.js'; ?>"></script>
<script type="text/javascript">
/*
function getReceipt(value) {
  if(value!='') {
      var i=0;
      var customer_receipt = '<select name="receipts" id="receipts"  class="form-control" required><option value="">Select</option>';

         <?php
            foreach ($this->receipts as $receipt) {
        ?>
          if(value==<?php echo $receipt['fkbusiness_id'] ?>) {
        <?php
                $id   = $receipt['id']."-".$receipt['name']."-".$receipt['receipt'];
                $name = $receipt['name'];
         ?>
           customer_receipt += '<option value="<?php echo $id; ?>"><?php echo $name; ?></option>';
           i++;
          }
         <?php
            }
         ?>
         customer_receipt += '</select>';
         if(i==0) {
           $("#receipt_add").html("<p>No Receipts Found</p>");
         } else {
           $("#receipt_add").html(customer_receipt);
         }
         $("#receipt_id").val("");
         $("#customer_receipts").html("");
         $("#customer_receipts").hide();
         $("#attach").show();

  }
}*/

 function attachReceipt() {
    var customer = $("#customer").val();
    if(customer=='') {
        alert('Select any customer to attach receipt');
    } else {
        $("#add_payment").hide();
        $("#add_receipt").show();
        $('#popup').bPopup({
                modalClose: false,
                easing: 'easeOutBack', 
                speed: 1000,
                transition: 'slideDown',
                follow: [false, false], 
        });
    }
 }


 function addReceipt() {
    var receipts      = $("#receipts").val();
    var receiptSplit  = receipts.split('-');
    var receiptId     = receiptSplit[0];
    var receiptName   = receiptSplit[1];
    var receiptFile   = receiptSplit[2];
    if(receiptId!='' && receiptName!='' && receiptFile!='') {
      var receipturl = '<a href="<?php echo $this->filepath; ?>'+receiptFile+'" target="_blank"> '+receiptName+' </a>';
      $("#receipt_id").val(receiptId);
      $("#attach").hide();
      $("#customer_receipts").html("Receipt "+ receipturl +" have been attached");
      $("#customer_receipts").show();
    }
    $("#popup").bPopup().close();
 }
   
function saveDraft() {
  $(".btn").attr("disabled",true);
    $.ajax({
      type: "POST",
      url: "<?php echo $this->sitePath.'transaction/income/ajax-call'; ?>",
      data: $('#add-income').serialize(),
      success: function (html) {
          if(html=='success') {
             $('#add_income').slideToggle(1000);
             $(".btn").attr("disabled",false);
              window.location.href='<?php echo $this->sitePath; ?>transaction/income';
          } else {
             $('#failure').html('<strong>Income cannot be saved as draft</strong>');
             $('#failure').fadeIn(1000);
             $('#failure').fadeOut(9000);
             $(".btn").attr("disabled",false);
          }
      }
    }); 
 }

  function bPopup_close() {
    $("#popup").bPopup().close();
 }

 function calculateTotal() {
    var sub_total  = 0.00;
    var sub_gst  = 0.00;
    var total_gst  = 0.00;
    var grand_total = 0.00;
    var grand_total_sgd = 0.00;

    var price     = $("#amount").val();
    var tax_code  = $("#tax_code").val(); 
    var gstAmount = $("#gst_amount").val();
    var myTax    = tax_code.split('_');
    var net_amount = numberWithOutCommasInput(price,'format');
    sub_total   += parseFloat(net_amount);
    if(myTax[0]!=0 && myTax[0]!='' && myTax[1]!=0 && myTax[1]!='') {
      $("#gst_amount").removeAttr("readonly");
        sub_gst   += (parseFloat(net_amount) * parseFloat(myTax[1]) / 100);
    } else {
      $("#gst_amount").attr("readonly","readonly");
    }

    grand_total += parseFloat(sub_total) + parseFloat(sub_gst);

    if(sub_gst!=0.00) {
      $("#gst_amount").val(numberWithCommasInput(sub_gst,'normal'));
    } else {
      $("#gst_amount").val('0.00');
    }
    $("#sub_total").text(numberWithCommasInput(parseFloat(sub_total).toFixed(2)));
    $("#total_gst").text(numberWithCommasInput(parseFloat(sub_gst).toFixed(2)));
    $("#grand_total").text(numberWithCommasInput(parseFloat(grand_total).toFixed(2)));
    gp_convertIt(parseFloat(grand_total));

}


function payTotal() {
    var sub_total  = 0.00;
    var sub_gst  = 0.00;
    var total_gst  = 0.00;
    var grand_total = 0.00;
    var grand_total_sgd = 0.00;

    var price     = $("#amount").val();
    var tax_code  = $("#tax_code").val(); 
    var gstAmount = $("#gst_amount").val();
    var myTax    = tax_code.split('_');
    var net_amount = numberWithOutCommasInput(price,'format');
    sub_total   += parseFloat(net_amount);
    if(myTax[0]!=0 && myTax[0]!='' && myTax[1]!=0 && myTax[1]!='') {
      if(gstAmount!=0.00) {
        sub_gst   += numberWithOutCommasInput(gstAmount,'format');
      } else {
        sub_gst   += (parseFloat(net_amount) * parseFloat(myTax[1]) / 100);
      }
    }

    grand_total += parseFloat(sub_total) + parseFloat(sub_gst);

    return numberWithCommasInput(parseFloat(grand_total).toFixed(2),'normal');

}

function numberWithCommas(x,id) {
  var amount = parseFloat(x).toFixed(2);
  var value  = amount.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
  $("#"+id).val(value);
  if(id!='addpay_pay_amount') {
    return calculateTotal();
  }
}

function numberWithCommass(x,id) {
  var amount = parseFloat(x).toFixed(2);
  var value  = amount.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
  $("#"+id).val(value);
  return gstTotal();
}


function numberWithCommasInput(x) {
  var amount = parseFloat(x).toFixed(2);
  var value  = amount.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
  return value;
}

function numberWithOutCommasInput(x) {
  x=x.replace(/\,/g,''); 
  var value = parseFloat(x).toFixed(2);
  return value;
}

function refreshList(type) {
  if(type==1) {
        var customerId = $("#customer").val();
        $.ajax({
        type: "POST",
        url: "<?php echo $this->sitePath.'transaction/income/ajax-refresh'; ?>",
        data: 'action=customerRefresh&id='+customerId,
        success: function (html) {
            $("#customer").html(html);
        }
      }); 
  } else if(type==2) {
       var payId = $("#payment_account").val();
        $.ajax({
        type: "POST",
        url: "<?php echo $this->sitePath.'transaction/income/ajax-refresh'; ?>",
        data: 'action=payaccountRefresh&id='+payId,
        success: function (html) {
            $("#payRefresh").html(html);
        }
      }); 
  } else if(type==3) {
        var incomeId = $("#income_type").val();
        $.ajax({
        type: "POST",
        url: "<?php echo $this->sitePath.'transaction/income/ajax-refresh'; ?>",
        data: 'action=incomeRefresh&id='+incomeId,
        success: function (html) {
            $("#incomeRefresh").html(html);
        }
      }); 
  }
}

</script>   
<script type="text/javascript">
   var btn = document.getElementById('file'),
       sizeBox = document.getElementById('sizeBox'), // container for file size info
       progress = document.getElementById('progress-bar'); // the element we're using for a progress bar

window.onload = function() {

          var uploader = new ss.SimpleUpload({
          button: btn, // file upload button
          url: "<?php echo $this->sitePath.'transaction/income/ajax-upload/operation/add'; ?>", // server side handler
          name: 'uploadfile', // upload parameter name        
        //  progressUrl: 'extras/uploadProgress.php', // enables cross-browser progress support (more info below)
          responseType: 'json',
          allowedExtensions: ['jpg', 'jpeg', 'png', 'gif', 'docx', 'pdf', 'doc'],
          maxSize: 10240, // kilobytes
          hoverClass: 'ui-state-hover',
          focusClass: 'ui-state-focus',
          disabledClass: 'ui-state-disabled',
          onSubmit: function(filename, extension) {
              this.setFileSizeBox(sizeBox); // designate this element as file size container
              this.setProgressBar(progress); // designate as progress bar
              $("#progress-bar").show();
            },         
          onComplete: function(filename, response) {
              if (!response) {
                  alert(filename + 'upload failed');
                  return false;            
              } else {
                $("#progress-bar").hide();
                var filename = response.data['file'];
                var status = response.data['status'];
                if(status=='success') {
                  $(".view_remove_file").html("<a href='<?php echo $this->sitePath.$this->filepath; ?>"+ filename +"' target='_blank'>Click to View</a> &nbsp; <a href='javascript:void(0)'' title='Remove Attachment' data-title='Remove Attachment' onclick='removeAttachment();'><i class='icon-remove-sign'></i></a>");
                  $("#attached_file").val(filename);
                  $(".view_remove_file").show();
                  $(".attach_file").show();
                  $("input[name='uploadfile']").attr('disabled','disabled');  
                } else if(status=='failure') {
                  alert("Upload Error : "+filename);
                  $("input[name='uploadfile']").removeAttr('disabled');
                  return false;
                } 

              }

                //console.log(filename);
              // do something with response...
            }
    });    

/*        $('#customer').on("change",function(){
            var value = $(this).find('option:selected').val();
            var coa   = $(this).find('option:selected').data('coa');
            if(value!='') {
                $.ajax({
                  type: "POST",
                  url: "<?php echo $this->sitePath.'transaction/income/ajax-refresh'; ?>",
                  data: 'action=getPayAccount&coa='+coa,
                  success: function (html) {
                      $("#payment_account").html(html);
                  }
                });
            } else {
              $("#payment_account").html('<option value="">Select</option>');
            }
      }); 

      var value1 = $(this).find('option:selected').val();
      var coa1   = "<?php echo $coa; ?>";
      var payacc = "<?php echo $this->income[0]['fkpayment_account']; ?>";
      if(value1!='') {
                $.ajax({
                  type: "POST",
                  url: "<?php echo $this->sitePath.'transaction/income/ajax-refresh'; ?>",
                  data: 'action=getPayAccount_update&coa='+coa1+'&payId='+payacc,
                  success: function (html) {
                      $("#payment_account").html(html);
                  }
                });
            } else {
              $("#payment_account").html('<option value="">Select</option>');
            }*/


};

function removeAttachment() {
  var attachedFile = $("#attached_file").val();
  if(attachedFile!='') {
    var confirmMsg = confirm('Are you sure want to remove the attachment?');
    if(confirmMsg) {
      $.ajax({
        type: "POST",
        url: "<?php echo $this->sitePath.'transaction/income/ajax-remove'; ?>",
        data: 'action=fileRemove&id='+attachedFile,
        success: function (html) {
            if(html=='success') {
              $("#attached_file").val('');
              $(".view_remove_file").hide();
              $(".attach_file").hide();
              $("input[name='uploadfile']").removeAttr('disabled');
              alert("File Removed Successfully");
            } else {
              alert("Unable to remove the attached file. Kindly try again later");
            }
        }
      }); 
    }
  }
}


  function checkReceipt(value) {
        if((value!='')) {
            $.ajax({
              type: "POST",
              url: "<?php echo $this->sitePath.'transaction/income/ajax-refresh'; ?>",
              data: 'action=check_receipt&receipt_no='+value,
              success: function (html) {
                  if(html=='1') {
                     $(".receipt_error").html("");
                     $(".receipt_error").hide();
                     return true;
                  } else if(html=='2') {
                     $(".receipt_error").html("Receipt No "+ value +" already exists");
                     $("#receipt").val("");
                     $(".receipt_error").show();
                  }
              }
            }); 
        } 
  }

  function originalRate(rate) {
  var gp_from = document.getElementById('currency').value;
  if(gp_from!='SGD') { 
    var amount  = numberWithOutCommasInput(payTotal(),'format');
    var original_amount = numberWithCommasInput(Number(rate)*amount,'normal');
    $("#grand_total_sgd").html("$ "+ original_amount);
    $("#foreign_currency").val(numberWithOutCommasInput(original_amount));
    $("#addpay_pay_amount").val(original_amount);
  }
}


function gstTotal() {
    var currency   = document.getElementById('currency').value;
    var amount     = numberWithOutCommasInput(payTotal(),'format');
    var gst_amount = $("#gst_amount").val();
    var totAmount  = Number(amount);
    if(currency!='SGD') {
      var rate            = $("#exchange_rate").val();
      var original_amount = numberWithCommasInput(Number(rate)*totAmount,'normal');
      $("#total_gst").html(gst_amount);
      $("#grand_total").html(numberWithCommasInput(totAmount,'normal'));
      $("#grand_total_sgd").html("$ "+ original_amount);
      $("#foreign_currency").val(numberWithOutCommasInput(original_amount));
      $("#addpay_pay_amount").val(original_amount);
    } else {
      $("#total_gst").html(gst_amount);
      $("#grand_total").html(numberWithCommasInput(totAmount,'normal'));
      $("#grand_total_sgd").html("$ 0.00");
      $("#foreign_currency").val(totAmount);
      $("#addpay_pay_amount").val(numberWithCommasInput(totAmount,'normal'));
    }
}

function gp_convertIt(amount) {
  if (amount=='' || amount==0){
    return false;
  } else {
  var gp_from = document.getElementById('currency').value;
    if(gp_from!='SGD') {
      var gp_to   = 'SGD';
      var gp_amount = amount;
      $.ajax({
        type: "POST",
        url: "<?php echo $this->sitePath.'default/index/convert-currency'; ?>",
        data: 'action=converter&amount=1&from='+gp_from,
        success: function (html) {
          //var convert_amount = numberWithCommas(Number(html),'normal');
           var convert_rate = Number(html);
          $("#exchange_rate").val(convert_rate);
          var convert_amount = numberWithCommasInput(convert_rate*amount,'normal');
          $("#grand_total_sgd").html("$ "+ convert_amount);
          $("#foreign_currency").val(numberWithOutCommasInput(convert_amount));
          $("#addpay_pay_amount").val(convert_amount);
        }
      });
    } else {
      $("#exchange_rate").val("");
      $("#grand_total_sgd").html("$ 0.00");
      $("#foreign_currency").val(amount);
      $("#addpay_pay_amount").val(numberWithCommasInput(amount,'normal'));
    }
  } 
}

function triggerPayment() {
   // var pay_account      = $("#payment_account").val();
    var credits          = $("#credit_term").val();
    //var amount           = $("#amount").val();
    /*var payment_account  = pay_account.split('_');
    $("#addpay_pay_account").find('option').removeAttr("selected");
    $("#addpay_pay_account option[value='"+payment_account[0]+"']").attr("selected", "selected");*/
    //$("#addpay_pay_amount").val(amount);
    if(credits==1) {
      $("#payment_trigger").val("1");
      $("#trigger_payment").show();
    } else {
      $("#trigger_payment").hide();
      $("#payment_trigger").val("0");
    } 
}
</script>