<?php
   $logSession = new Zend_Session_Namespace('sess_login');

  function convertCurrency($amount, $from){
    $to   = 'SGD';
      $url  = "https://www.google.com/finance/converter?a=$amount&from=$from&to=$to";
      $data = file_get_contents($url);
      preg_match("/<span class=bld>(.*)<\/span>/",$data, $converted);
      $converted = preg_replace("/[^0-9.]/", "", $converted[1]);
      return round($converted, 3);
  }
?>
<div id="popup">
<span class="button b-close"><span>X</span></span>
<div class="row" id="add_payment">
 <h4>Add Payment</h4>
<div class="widget-container col-md-12 col-md-offset-1">
 <form class="form-horizontal" id="add-payment" method="post">
    <div class="form-group">
      <label class="control-label col-lg-4">Payment Date <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <input type="hidden" name="expense_id" id="expense_id" />
            <input type="hidden" name="pay_id" id="pay_id" />
            <input type="text" name="date" id="date" class="form-control date-pick" placeholder="Select Date"  autocomplete="off" />
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Payment / Accruals Account <span class="mandatory">*</span></label>
        <div class="col-lg-5">
             <select class="form-control" name="pay_account" id="pay_account">
                <option value="">Select</option>
                    <?php
                        if(isset($this->payAccount) && !empty($this->payAccount)) {
                            foreach ($this->payAccount as $payAccount) {
                    ?>
                        <option value="<?php echo $payAccount['id']; ?>"><?php echo $payAccount['account_name']; ?></option>
                    <?php
                            }
                        }
                    ?>                                                       
              </select>
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Amount <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <input type="text" name="pay_amount" id="pay_amount" class="form-control" placeholder="Enter Amount"  autocomplete="off" />
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Payment Method <span class="mandatory">*</span></label>
        <div class="col-lg-5">
          <select name="pay_method" id="pay_method" class="form-control">
            <option value="">Select</option>
           <?php 
                foreach ($this->payMethod as $key => $pay) {
           ?>
                <option value="<?php echo $key; ?>"><?php echo $pay; ?></option>
           <?php
                }
           ?>
          </select>
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Bank Cheque / Draft No </label>
        <div class="col-lg-5">
            <input type="text" name="cheque_draft_no" id="cheque_draft_no" class="form-control" placeholder="Enter Cheque / Draft No" autocomplete="off"  />
        </div>
    </div>
     <div class="form-group">
      <label class="control-label col-lg-4">Prompt Payment Discount <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <select class="form-control" name="payment_discount" id="payment_discount" onchange="discountPayment(this.value);">
                <option value="1">Yes</option>  
                <option value="2" selected>No</option>  
            </select>
        </div>
    </div>
     <div class="form-group">
      <label class="control-label col-lg-4">Discount Amount <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <input type="text" name="discount_amount" id="discount_amount" class="form-control" value="0" disabled autocomplete="off" />
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Additional Description / Notes </label>
        <div class="col-lg-5">
        <textarea name="description" id="description" class="form-control"></textarea>
        </div>
    </div>

     <div class="form-group">
        <div class="col-lg-8 col-lg-offset-3">
            <div class="form-actions">
               <input type="submit" name="update_payment" class="btn btn-primary " id="update_payment" value="Update Payment" />
                <button type="reset" class="btn" onclick="return bPopup_close();">Cancel</button>
            </div>
        </div>
     </div>

</form>
</div>
</div>
</div>
 

<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li><a href="<?php echo $this->sitePath."transaction/income/"; ?>">Income</a></li>
   <li class="active">View</li>
</ul>

  <div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            </div>
   </div>
<div class="row">
<div class="col-md-12">
                            <div class="square-widget">
                                <div class="widget-head clearfix">
                                    <h4 class="pull-left"><i class="icon-user-4"></i> Income Transaction Details</h4>
                                </div>
                                <div class="widget-container" style="margin-left:50px;">
                                <div class="row">
                                    <div class="col-md-3">
                                            <strong>Income No  </strong> <br/>
                                            <span><?php echo $this->income[0]['income_no']; ?></span>
                                    </div>
                                      <div class="col-md-3"> 
                                        <strong>Branch </strong><br>
                                        <span>
                                        <?php 
                                          if(isset($this->location) && !empty($this->location)) {
                                                foreach ($this->location as $location) {
                                                    if($location['id']==$this->income[0]['fklocation_id']) {
                                                        echo ucfirst($location['name']);
                                                    }
                                                }
                                            }
                                        ?>
                                        </span>
                                        

                                    </div>
                                    <div class="col-md-3">
                                            <strong>Date </strong><br>
                                            <span><?php echo date("d-m-Y",strtotime($this->income[0]['date'])); ?></span>
                                    </div>
                                    <div class="col-md-3">
                                            <strong>Receipt No  </strong><br>
                                            <span><?php echo $this->income[0]['receipt_no']; ?></span>
                                    </div>
                                    
                                </div>
                                <br/>
                                <div class="row">

                                <div class="col-md-3">
                                            <strong>Customer / Payee  </strong><br>
                                            <span><?php echo ucfirst($this->income[0]['customer_name']); ?></span>
                                    </div>

                                <div class="col-md-3">
                                        <strong>Credit Term </strong> <br>
                                        <span>
                                        <?php 
                                          if(isset($this->creditTerm) && !empty($this->creditTerm)) {
                                              foreach ($this->creditTerm as $key => $credit) {
                                                if($key==$this->income[0]['credit_term']) {
                                                  echo $credit;
                                                }
                                              }
                                          }
                                        ?>
                                        </span>
                                       
                                    </div>
                                  
                                    <div class="col-md-3">
                                        <strong>Transaction Currency </strong><br>
                                        <span>
                                        <?php 
                                          if(isset($this->currencies) && !empty($this->currencies)) {
                                            foreach ($this->currencies as $key => $currency) {
                                              if($key==$this->income[0]['transaction_currency']) {
                                                  echo $currency." - ".$key;
                                                }
                                            }
                                          }
                                        ?>
                                        </span>
                                    </div>
                                    <div class="col-md-3"> 
                                        <strong>Type of Income </strong><br>
                                        <span>
                                        <?php 
                                          if(isset($this->incomeAccount) && !empty($this->incomeAccount)) {
                                                foreach ($this->incomeAccount as $income) {
                                                    if($income['id']==$this->income[0]['fkincome_type']) {
                                                        echo ucfirst($income['account_name']);
                                                    }
                                                }
                                            }
                                        ?>
                                        </span>
                                        

                                    </div>

                                   
                                    

                                </div>
                                <br/>
                                <div class="row">

                                 <div class="col-md-3">  
                                        <strong>Description </strong><br>
                                        <span><?php echo $this->income[0]['transaction_description']; ?></span>
                                    </div>

                                <div class="col-md-3">
                                        <strong>Amount </strong><br>
                                        <span><?php echo number_format($this->income[0]['amount'],2,'.',','); ?></span>
                                    </div>
                                    
                                    <div class="col-md-3">
                                        <strong>Tax Code </strong><br>
                                        <span>
                                        <?php 
                                          if(isset($this->taxCode) && !empty($this->taxCode) && $this->taxCode!=0 && $this->income[0]['fktax_id']!=0) {
                                            foreach ($this->taxCode as $tax) {
                                              if($tax['id']==$this->income[0]['fktax_id']) {
                                                foreach ($this->supply as $key => $supply) {
                                                    if($tax['tax_code']==$key) {
                                                      echo $supply['name']." - ".$tax['tax_percentage']." %";
                                                    }
                                                }
                                              }
                                            }
                                          } else {
                                           echo "NA - Not Applicable";
                                          }
                                        ?>
                                        </span>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Tax Percentage </strong><br>
                                        <span><?php echo $this->income[0]['tax_value']." %"; ?></span>
                                    </div>
                                    
                                
                                </div>
                                <br/>
                            <div class="row">

                            <div class="col-md-3">
                                        <strong>Gst Amount </strong><br>
                                        <span><?php echo number_format($this->income[0]['gst_amount'],2,'.',','); ?></span>
                                    </div>

                            <div class="col-md-3">
                                        <strong>Receipt if any </strong><br>
                                         <span>
                                        <?php
                                          if(isset($this->income[0]['fkreceipt_id']) && !empty($this->income[0]['fkreceipt_id']) && file_exists($this->filepath.$this->income[0]['fkreceipt_id'])) {
                                         ?>
                                       <a href="<?php echo $this->sitePath.$this->filepath.$this->income[0]['fkreceipt_id']; ?>" target="_blank">Click to view</a>
                                           <?php 
                                          } else {
                                          ?>
                                          No attachments available
                                          <?php 
                                            }
                                          ?>
                                          </span>
                                </div>

                            <div class="col-md-3">
                                        <strong>Approval By / For </strong><br>
                                        <span>
                                        <?php 
                                            if(isset($this->approveUser) && !empty($this->approveUser)) {
                                                foreach ($this->approveUser as $approve) {
                                                  if($approve['account_type']==0) {
                                                        $account_type = "Developer";
                                                  } 
                                                  else if($approve['account_type']==1) {
                                                        $account_type = "Developer";
                                                  } 
                                                  else if($approve['account_type']==2) {
                                                        $account_type = "Super User";
                                                  } else if($approve['account_type']==3) {
                                                        $account_type = "Manager";
                                                  }
                                                  if($approve['id']==$this->income[0]['approval_for']) {
                                                        echo $approve['username']." - ".$account_type;
                                                  }
                                                }
                                            }
                                        ?>
                                        </span>
                                    </div>
                                
                                 
                                    <div class="col-md-3">
                                        <strong>Status </strong><br>
                                        <span>
                                        <?php 
                                            if($this->income[0]['transaction_status']==1) {
                                                echo "Approved / Verified";
                                            } else if($this->income[0]['transaction_status']==2) {
                                                echo "Saved / Unverified";
                                            } else if($this->income[0]['transaction_status']==3) {
                                                echo "Draft";
                                            }
                                        ?>
                                        </span>
                                    </div>
                            </div>


                                </div>
                            </div>
                        </div>


                    <hr/>
                    <?php
                     if($this->income[0]['gst_amount']!=0.00) {
                       $tax_amount     = $this->income[0]['gst_amount'];
                     } else {
                       $tax_amount     = ($this->income[0]['amount'] * $this->income[0]['tax_value'] / 100);
                     }
                     $total_amount   = $this->income[0]['amount'] + $tax_amount;
                     if($this->income[0]['transaction_currency']!='SGD') {
                        $converted_amount = $total_amount*$this->income[0]['exchange_rate'];
                      } else {
                        $converted_amount = $total_amount;
                      }
                    // $pending_amount =  $converted_amount - $paid_amount;
                ?>
                        <div class="row">
                            <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Sub Total : </label>
                                   <span id="sub_total"><?php echo number_format($this->income[0]['amount'],2,'.',','); ?></span><br/>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Total GST : </label>
                                    <span id="total_gst"><?php echo number_format($tax_amount,2,'.',','); ?></span>
                             </div>
                        </div>

                            <div class="row">
                            <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Grand Total : </label>
                                    <span id="grand_total"><?php echo number_format($total_amount,2,'.',','); ?></span>
                                </div>
                             </div>
                             <div class="row">
                            <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Exchange Rate :</label>
                                   <span><?php echo $this->income[0]['exchange_rate']; ?></span>
                             </div>
                             </div>
                            <div class="row">
                            <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Grand Total SGD :</label>
                                    <span id="grand_total_sgd">
                                      <?php echo number_format($converted_amount,2,'.',','); ?> 
                                    </span>
                                </div>
                             </div>

</div>

<div class="row">
                         <div class="col-md-6 col-md-offset-5">
                            <div class="square-widget">
                                <h5 class="pull-left"><i class="icon-user-4"></i> Payment Details</h5>
                                <div class="widget-container">
                                    <table class="table responsive">
                                        <thead>
                                            <tr>
                                                <th>
                                                    Date
                                                </th>
                                                <th>
                                                    Payment Method
                                                </th>
                                                <th>
                                                    Bank Cheque / Draft No
                                                </th>
                                                <th style="text-align:right;">
                                                    Amount
                                                </th>
                                                <!--<th>
                                                    Actions
                                                </th>-->
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php 
                                        $paid_amount = 0.00;  
                                        if(isset($this->incomePayment) && !empty($this->incomePayment)) {
                                                                                    
                                            foreach ($this->incomePayment  as $payment) {
                                                $paid_amount += $payment['payment_amount']+$payment['discount_amount'];
                                        ?>
                                            <tr>
                                                <td><?php echo date("d-m-Y",strtotime($payment['date'])); ?></td>
                                                
                                                <td>
                                                <?php 
                                                    foreach ($this->payMethod as $key => $pay) {
                                                        if($key==$payment['payment_method']) {
                                                            echo $pay;
                                                        }
                                                    }
                                                 ?>
                                                </td>
                                                <td><?php echo ucfirst($payment['cheque_draft_no']); ?></td>
                                                <td style="text-align:right;"><?php echo number_format($payment['payment_amount']+$payment['discount_amount'],2,'.',','); ?></td>
                                                <!--<td>

                                                 <?php 
                                                        if($logSession->type!=5) {
                                                   ?>

                                            <a href="javascript:void(0)" onclick="return editPayment('<?php echo $this->inc_id; ?>','<?php echo $payment['id']; ?>','<?php echo $payment['discount_status']; ?>','<?php echo $payment['discount_amount']; ?>','<?php echo $payment['payment_description']; ?>','<?php echo date("d-m-Y",strtotime($payment['date'])); ?>','<?php echo $payment['fkpayment_account']; ?>','<?php echo $payment['payment_amount']; ?>','<?php echo $payment['payment_method']; ?>','<?php echo $payment['cheque_draft_no']; ?>')" data-original-title="Edit Payment" title="Edit Payment"><i class="icon-pencil-2"></i></a>

                                            <a href="javascript:void(0)" onclick="return deletePayment('<?php echo base64_encode($this->inc_id); ?>','<?php echo base64_encode($payment['id']); ?>');" data-original-title="Delete Payment" title="Delete Payment"><i class="icon-remove-2"></i></a>      

                                                    <?php
                                                        }
                                                    ?>                                                   
                                                </td>-->
                                            </tr>
                                        <?php
                                            }
                                           } else {
                                        ?>  
                                          <tr>
                                          <td colspan="4"><h5 align="center"><strong>No Payment has been received yet</strong></h5></td>

                                          </tr>
                                        <?php
                                          }
                                        ?>
                                        </tbody>
                                        </table>
                                    </div>
                                </div>
                        </div>
                </div>
             

                 <div class="row">
                       <!--  <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Total Amount :</label>
                                    <span id="">
                                    <?php  echo number_format($converted_amount,2,'.',','); ?>
                                    </span>
                                </div> -->
                                <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Paid Amount :</label>
                                    <span id="">
                                    <?php  echo number_format($paid_amount,2,'.',',');?>
                                    </span>
                                </div>
                            <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Amount Due :</label>
                                    <span id="">
                                    <?php  
                                    if($this->income[0]['payment_status']==1) {
                                      echo "Nil";
                                    } else {
                                    echo number_format($converted_amount-$paid_amount,2,'.',','); 
                                    }
                                    ?>
                                    </span>
                                </div>

                             </div>
<script type="text/javascript">

function editPayment(Incid,Idvalue,discount_status,discount_amount,description,date,pay_account,pay_amount,pay_method,cheque) {
    $("#income_id").val(Incid);
    $("#pay_id").val(Idvalue);
    $("#payment_discount").val(discount_status);
    if(discount_status==1) {
        $("#discount_amount").removeAttr("disabled");
    } else {
        $("#discount_amount").attr("disabled","true");
    }
    $("#discount_amount").val(discount_amount);
    $("#description").val(description);
    $("#date").val(date);
    $("#pay_account").val(pay_account);
    $("#pay_amount").val(pay_amount);
    $("#pay_method").val(pay_method);
    $("#cheque_draft_no").val(cheque);
        $('#popup').bPopup({
            modalClose: false,
            easing: 'easeOutBack', 
            speed: 1000,
            transition: 'slideDown',
            follow: [false, false], 
    });
}

function deletePayment(Incid,Idvalue) {
  var confirmMsg = confirm("Are you sure want to delete this payment made for expense? You cannot undo this action");
    if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>transaction/income/view/delid/'+Idvalue+'/id/'+Incid;
    }
}

function discountPayment(value) {
    if(value==1) {
        $("#discount_amount").removeAttr("disabled");
    } else if(value==2) {
        $("#discount_amount").val("0");
        $("#discount_amount").attr("disabled","true");
    }
}

 function bPopup_close() {
     $("#popup").bPopup().close();
 }
</script>