   <div class="row">
       <div class="col-md-12">
            <p>
              <a href="<?php echo $this->sitePath."transaction/invoice"; ?>" class="btn btn-danger border-none">Invoice</a><a href="<?php echo $this->sitePath."transaction/credit"; ?>" class="btn btn-default border-none">Credit Note</a>
            </p>
       </div>
   </div>

<div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            <div class="alert alert-success" id="success" style="display:none;">
            </div>
            <div class="alert alert-danger" id="failure" style="display:none;">
            </div>
            </div>
   </div>
   <?php
    $logSession = new Zend_Session_Namespace('sess_login');
    $productTitle = 'Product';
    if(isset($this->invoiceCustom[0]['default_product_title']) && $this->invoiceCustom[0]['default_product_title']==1) {
         $productTitle = 'Product';
    } else if(isset($this->invoiceCustom[0]['default_product_title']) && $this->invoiceCustom[0]['default_product_title']==2) {
         $productTitle = 'Service';
    } else if(isset($this->invoiceCustom[0]['default_product_title']) && $this->invoiceCustom[0]['default_product_title']==3) {
         $productTitle = 'Product / Service';
    }
   ?>
   <?php 
        if($logSession->type!=5 && $logSession->proxy_type!=5) {   
   ?>
     <div class="row">


                        <div class="col-md-12 widget-module">

                            <div class="square-widget widget-collapsible">
                                <div class="widget-head clearfix">
                                    <h4 class="pull-left"><i class="icon-paragraph-justify-2"></i> New Invoice</h4>

                                </div>

                                <div class="widget-container col-md-12">

                                <form class="form-horizontal" id="add-invoice" method="post">
                                        <div class="form-group">
                                            <div class="col-lg-2">
                                              <label>Date <span class="mandatory">*</span></label>
                                                <input type="text" name="date" id="date" class="form-control date-pick" placeholder="Select Date" value="<?php echo date('d-m-Y'); ?>" autocomplete="off"  onchange="return creditSelect();"/>
                                            </div>
                                             
                                            <!-- <div class="col-lg-2">
                                            <label>Invoice No </label>
                                            <?php
                                              $invoicePrefix = $this->invoiceCustom[0]['invoice_prefix'];
                                              $invoiceSplit  = explode("-", $this->invoiceNo);
                                              if($invoicePrefix!=$invoiceSplit[0]) {
                                                $invoiceNo = $invoicePrefix."-".$invoiceSplit[1];
                                              } else {
                                                $invoiceNo = $this->invoiceNo;
                                              }
                                            ?>
                                                <input type="hidden" name="invoice_custom" id="invoice_custom" value="<?php echo $invoicePrefix; ?>" />
                                                <input type="text" name="invoice_no" id="invoice_no" class="form-control" readonly value="<?php echo $invoiceNo; ?>" />
                                            </div>     -->
                                            <div class="col-lg-2">
                                             <label>Customer Name <span class="mandatory">*</span> <a href="javascript:void(0)" title="Refresh List" data-title="Refresh List" target="_blank" onclick="return refreshList(1);" class="customer-refresh" style="margin-left:0px;"><i class="icon-refresh"></i></a></label>
                                             <div id="customerRefresh">
                                                <select class="select2" name="customer" id="customer" onchange="return shippingAddress(this.value);">
                                                    <option value="">Select</option>
                                                    <?php
                                                        if(isset($this->customer) && !empty($this->customer)) {
                                                            foreach ($this->customer as $customer) {
                                                              $coa = $customer['coa_link'].",".$customer['other_coa_link'];
                                                                if($this->customer_id == $customer['id'])
                                                                    $customerSelect = 'selected';
                                                                else
                                                                    $customerSelect = '';  
                                                    ?>
                                                        <option value="<?php echo $customer['id']; ?>" <?php echo $customerSelect; ?> data-coa='<?php echo $coa; ?>'><?php echo $customer['customer_name']; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                    
                                                </select>
                                                </div>
                                                <a href="<?php echo $this->sitePath."business/customer/add"; ?>" title="Click to add new customer" data-title="Click to add new customer" target="_blank" id="add-customer"><i class="icon-plus-circle-2"></i> Add New Customer</a>
                                            </div> 
                                            <div class="col-lg-2">
                                             <label>Shipping Address </label>
                                                <select class="form-control" name="shipping_address" id="shipping_address">
                                                    <option value="">Select</option>
                                                </select>
                                            </div>  
                                            <div class="col-lg-2">
                                             <label>Credit Term <span class="mandatory">*</span></label>
                                                <select class="form-control" name="credit_term" id="credit_term" onchange="return creditSelect();">
                                                    <?php
                                                        $days = '';
                                                        if(isset($this->creditTerm) && !empty($this->creditTerm)) {
                                                            foreach ($this->creditTerm as $key => $credit) {
                                                                if($key!=1) {
                                                                    $credits = $credit." Days";
                                                                } else {
                                                                    $credits = $credit;
                                                                }
                                                                if(isset($this->invoiceCustom[0]['default_credit_term']) && !empty($this->invoiceCustom[0]['default_credit_term'])) {
                                                                  if($this->invoiceCustom[0]['default_credit_term']==$key) {
                                                                      if($key!=1) {
                                                                          $days = $credit;
                                                                      } 
                                                                      $creditSelect = 'selected';
                                                                  }
                                                                  else {
                                                                      $creditSelect = '';
                                                                  }
                                                                }
                                                    ?>
                                                        <option value="<?php echo $key; ?>" <?php echo $creditSelect; ?>><?php echo $credits; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                       
                                                </select>
                                            </div> 

                                            <div class="col-lg-2">
                                              <label>Due Date </label>
                                              <?php
                                              if(isset($days) && $days!='' && !empty($days)) {
                                                $cur_date = date('d-m-Y');
                                                $mod_date = strtotime($cur_date."+ ".$days." days");
                                                $due_date = date('d-m-Y',$mod_date);
                                               } else {
                                                $due_date = date('d-m-Y');
                                              //  $mod_date = strtotime($cur_date."+ 15 days");
                                              //  $due_date = date('d-m-Y',$mod_date);
                                               }
                                              ?>
                                                <input type="text" name="due_date" id="due_date" class="form-control date-pick" placeholder="Select Date" value="<?php echo $due_date; ?>" autocomplete="off" />
                                            </div>

                                            
                                         <div class="col-lg-2">
                                             <label>Currency <span class="mandatory">*</span></label>
                                                <select class="select2" name="currency" id="currency" onchange="return reloadPage(this.value);">
                                                     <?php
                                                        if(isset($this->currencies) && !empty($this->currencies)) {
                                                            foreach ($this->currencies as $key => $currency) {
                                                              if(isset($this->currency_id) && !empty($this->currency_id)) {
                                                                if($this->currency_id==$key) {
                                                                  $currencySelect = 'selected';
                                                                } else {
                                                                  $currencySelect = '';
                                                                }
                                                              } else { 
                                                                if(isset($this->invoiceCustom[0]['default_currency']) && !empty($this->invoiceCustom[0]['default_currency'])) {
                                                                  if($this->invoiceCustom[0]['default_currency']==$key) {
                                                                    $currencySelect = 'selected';
                                                                  }
                                                                  else {
                                                                    $currencySelect = '';
                                                                  }
                                                                } else {
                                                                  if($key=='SGD') 
                                                                      $currencySelect = "selected";
                                                                  else
                                                                      $currencySelect = "";
                                                                }
                                                              }
                                                    ?>
                                                        <option value="<?php echo $key; ?>" <?php echo $currencySelect; ?>><?php echo $currency; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                      
                                                </select>
                                            </div> 


                                            
                                        </div>

                                        <div class="form-group">

                                            
                                            <div class="col-lg-2">
                                              <label>Prompt Payment Discount <span class="mandatory">*</span></label>
                                                <select class="form-control" name="payment_discount" id="payment_discount" onchange="discountPayment(this.value);">
                                                 <option value="1">Yes</option>  
                                                 <option value="2" selected>No</option>  
                                                </select>
                                            </div>

                                            <div class="col-lg-2">
                                              <label>Non-Revenue Supply (Tax) <span class="mandatory">*</span></label>
                                                 <select class="form-control" name="non_revenue_tax" id="non_revenue_tax">
                                                 <option value="1">Yes</option>  
                                                 <option value="2" selected>No</option>  
                                                </select>
                                            </div>

                                             <div class="col-lg-2">
                                              <label>D.O / S.O No </label>
                                                <input type="text" name="do_so_no" id="do_so_no" class="form-control" placeholder="Enter D.O / S.O No" autocomplete="off" />
                                            </div>

                                             <div class="col-lg-2">
                                              <label>Memo </label><br/>
                                                <textarea name="memo" id="memo" class="form-control notes"></textarea>
                                            </div>

                                        </div>

                        <div class="col-md-12">
                            <div class="square-widget">
                                
                                <div class="widget-container">
                                    <table class="table responsive">
                                        <thead>
                                            <tr>
                                            <th style="width:2%;"></th>
                                                <th>
                                                    <?php echo $productTitle; ?> ID
                                                </th>
                                                <th>
                                                    <?php echo $productTitle; ?> Description <a href="javascript:void(0)" title="Refresh List" data-title="Refresh List" target="_blank" onclick="return refreshProductList();" class="product-refresh" style="margin-left:0px;"><i class="icon-refresh"></i></a>
                                                </th>
                                                <th>
                                                    Quantity
                                                </th>
                                                <th>
                                                    Unit Price
                                                </th>
                                                 <th>
                                                    Discount
                                                </th>
                                                <th>
                                                    Tax Code
                                                </th>
                                                <th style="text-align:center;">
                                                    Amount
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody id="invoice_detail">
                                            <tr>
                                                <td style="width:2%;"></td>
                                                <td style="width:15%;">
                                                    <input type="text" name="product_id_1" id="product_id_1" class="form-control" required readonly />
                                                </td>
                                                <td style="width:20%;">
                                                    <div id="productRefresh1">
                                                    <select name="product_description_1" id="product_description_1" class="form-control" onchange="return productSelect(1,this.value);" required>
                                                        <option value="">Select</option>
                                                        <?php
                                                            foreach ($this->product as $product) {
                                                              if(isset($this->currency_id) && !empty($this->currency_id)) {
                                                                if($this->currency_id==$product['currency']) {
                                                        ?>
                                                            <option value="<?php echo $product['id']."_".$product['product_id']."_".$product['price']; ?>"><?php echo ucfirst($product['name']); ?></option>
                                                        <?php
                                                                }
                                                              } else if(isset($this->invoiceCustom[0]['default_currency']) && !empty($this->invoiceCustom[0]['default_currency'])) {
                                                                if($this->invoiceCustom[0]['default_currency']==$product['currency']) {
                                                        ?>
                                                              <option value="<?php echo $product['id']."_".$product['product_id']."_".$product['price']; ?>"><?php echo ucfirst($product['name']); ?></option>
                                                        <?php
                                                                }
                                                              } else if($product['currency']=='SGD') {
                                                        ?>
                                                          <option value="<?php echo $product['id']."_".$product['product_id']."_".$product['price']; ?>"><?php echo ucfirst($product['name']); ?></option>

                                                        <?php
                                                              }
                                                            }
                                                        ?>
                                                        
                                                    </select>
                                                    </div>
                                                <?php 
                                                    if($logSession->type!= 5 && $logSession->proxy_type!= 5) {
                                                 ?>
                                                    <a href="<?php echo $this->sitePath."settings/add-product"; ?>" title="Click to add new <?php echo $productTitle; ?>" data-title="Click to add new <?php echo $productTitle; ?>" target="_blank" class="add-product"><i class="icon-plus-circle-2"></i> Add New <?php echo $productTitle; ?></a>  &nbsp; 
                                                <?php
                                                    }
                                                ?>
                                                </td>
                                                <td style="width:7%;">
                                                    <input type="text" name="quantity_1" id="quantity_1" class="form-control" required number="true" minlength="1" maxlength="5" onkeyup="return calculateTotal();" autocomplete="off" />
                                                </td>
                                                <td style="width:15%;">
                                                    <input type="text" name="price_1" id="price_1" class="form-control amount-align"  required number="true" onkeyup="return calculateTotal();" readonly />
                                                </td>
                                                <td style="width:10%;">
                                                    <input type="text" name="discount_amount_1" id="discount_amount_1" class="form-control amount-align"  number="true" minlength="1" onkeyup="return calculateTotal();" onchange="return numberWithCommasInput(this.value,this.id);" autocomplete="off" />
                                                </td>
                                                <td style="width:15%;">
                                                    <select class="form-control" name="tax_code_1" id="tax_code_1" required  onchange="return calculateTotal();">
                                                    <option value="">Select</option>
                                                     <?php
                                                        if(isset($this->invoiceCustom[0]['default_tax_code']) && $this->invoiceCustom[0]['default_tax_code']==0) {
                                                            $selected = 'selected';
                                                        } else {
                                                            $selected = '';
                                                        }
                                                    ?>
                                                     <option value="0" title="Not Applicable" <?php echo $selected; ?>>NA</option>      
                                                    <?php
                                                      $taxSelect = '';
                                                        if(isset($this->taxCode) && !empty($this->taxCode)) {
                                                            foreach ($this->taxCode as $tax) {
                                                              if(isset($this->invoiceCustom[0]['default_tax_code']) && !empty($this->invoiceCustom[0]['default_tax_code'])) {
                                                                  if($this->invoiceCustom[0]['default_tax_code']==$tax['id']) {
                                                                    $taxSelect = 'selected';
                                                                  }
                                                                  else {
                                                                    $taxSelect = '';
                                                                  }
                                                                }
                                                              foreach ($this->supply as $key => $supply) {
                                                                if($tax['tax_code']==$key) {
                                                                  $code = $supply['name'];
                                                                }
                                                              } 
                                                    ?>
                                                        <option value="<?php echo $tax['id']."_".$tax['tax_percentage']; ?>" title="<?php echo ucfirst(str_replace("\r\n", " ", $tax['description'])); ?>" <?php echo $taxSelect; ?>><?php echo $code." - ".$tax['tax_percentage']." %"; ?></option>
                                                    <?php
                                                            }
                                                        }
                                                    ?>                                                  
                                                </select>
                                                </td>
                                                <td style="text-align:right; padding-right:40px;">
                                                    <strong id="net_amount_1">0.00</strong>
                                                </td>
                                            </tr>
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <hr/>
                        <div class="form-group">
                            <div class="col-lg-4 col-md-offset-10">
                              <div class="form-group">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Sub Total :</label>
                                   <div class="col-lg-4">
                                    <span id="sub_total">0.00</span>
                                </div>
                             </div>
                             <div class="form-group">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Total GST :</label>
                                   <div class="col-lg-4">
                                    <span id="total_gst">0.00</span>
                                </div>
                             </div>
                             <div class="form-group">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Grand Total :</label>
                                   <div class="col-lg-4">
                                    <span id="grand_total">0.00</span>
                                </div>
                             </div>
                             <div class="form-group">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Grand Total SGD :</label>
                                   <div class="col-lg-4">
                                    <span id="grand_total_sgd">0.00</span>
                                </div>
                             </div>

                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-lg-3">
                                <input type="hidden" name="product_counter" id="product_counter" value="1" />
                                <a href="javascript:void(0)" id="invoice_row" class="btn btn-primary green" type="button">Add Row</a>
                            </div>
                        </div>


<div class="row" id="trigger_payment" style="display:none;">
 <h4>Add Payment</h4>
    <div class="form-group">
     
        <div class="col-lg-2">
         <label>Payment Date <span class="mandatory">*</span></label>
            <input type="text" name="addpay_date" required id="addpay_date" class="form-control date-pick" placeholder="Select Date"  autocomplete="off" value="<?php echo date('d-m-Y'); ?>" />
        </div>
      
        <div class="col-lg-3">
        <label>Payment / Accruals Account <span class="mandatory">*</span></label>
             <select class="form-control" name="addpay_pay_account" id="addpay_pay_account" required>
               <option value="">Select</option>  
                    <?php
                       /* if(isset($this->payAccount) && !empty($this->payAccount)) {
                            foreach ($this->payAccount as $payAccount) {*/
                    ?>
                        <!-- <option value="<?php echo $payAccount['id']; ?>"><?php echo $payAccount['account_name']; ?></option> -->
                    <?php
                          /*  }
                        }*/
                    ?>     
                                                                     
              </select>
        </div>
     
        <div class="col-lg-2">
         <label>Amount <span class="mandatory">*</span></label>
            <input type="text" name="addpay_pay_amount" id="addpay_pay_amount" class="form-control amount-align" required number="true" autocomplete="off"  onchange="return numberWithCommasInput(this.value,this.id);"  />
            <input type="hidden" name="addpay_pending_amount" id="addpay_pending_amount" class="form-control" autocomplete="off"   />
        </div>

      
        <div class="col-lg-2">
        <label>Payment Method <span class="mandatory">*</span></label>
          <select name="addpay_pay_method" id="addpay_pay_method" class="form-control" required>
            <option value="">Select</option>
           <?php 
                foreach ($this->payMethod as $key => $pay) {
           ?>
                <option value="<?php echo $key; ?>"><?php echo $pay; ?></option>
           <?php
                }
           ?>
          </select>
        </div>

        <div class="col-lg-2">
         <label>Bank Cheque / Draft No </label>
            <input type="text" name="addpay_cheque_draft_no" id="addpay_cheque_draft_no" class="form-control" placeholder="Enter Cheque / Draft No"  autocomplete="off"  />
        </div>
    </div>
    <div class="form-group">
     
        <div class="col-lg-2">
        <label>Prompt Payment Discount <span class="mandatory">*</span></label>
            <select class="form-control" name="addpay_payment_discount" id="addpay_payment_discount" onchange="discountTriggerPayment(this.value);">
                <option value="1">Yes</option>  
                <option value="2" selected>No</option>  
            </select>
        </div>

      
        <div class="col-lg-2">
        <label>Discount Amount <span class="mandatory">*</span></label>
            <input type="text" name="addpay_discount_payment_amount" id="addpay_discount_payment_amount" class="form-control amount-align" value="0" disabled  autocomplete="off"  onchange="return numberWithCommasInput(this.value,this.id);" />
        </div>

      
        <div class="col-lg-6">
        <label>Additional Description / Notes </label>
        <textarea name="addpay_description" id="addpay_description" class="form-control"></textarea>
        <input type="hidden" name="payment_trigger" id="payment_trigger" value="0" />
        </div>
    </div>


</div>


                             <div class="form-group">
                                    <div class="col-lg-1">
                                         <div class="form-actions">
                                            <input type="hidden" name="action" id="action" value="save_draft_invoice" />
                                            <input type="button" name="save_draft_invoice" class="btn btn-primary" id="save_draft_invoice" value="Save as Draft" onclick="return saveDraft();" /><br/>
                                            <i>Save Draft Invoice</i>
                                          </div>
                                      </div>
                                      <div class="col-lg-3" style="margin-left:10px;">
                                        <div class="form-actions">
                                            <select class="form-control" name="approval_for" id="approval_for">
                                            <option value="">For Approval</option>
                                                        <?php
                                                            if(isset($this->approveUser) && !empty($this->approveUser)) {
                                                                foreach ($this->approveUser as $approve) {
                                                                  if($approve['account_type']==2) {
                                                                     $account_type = "Super User";
                                                                  } else if($approve['account_type']==3) {
                                                                     $account_type = "Manager";
                                                                  }
                                                                  if($approve['account_type']==3 && ($approve['id']==$logSession->id || $approve['id']==$logSession->proxy_id)) {
                                                                     } else {
                                                        ?>
                                                            <option value="<?php echo $approve['id']; ?>" ><?php echo $approve['username']." - ".$account_type; ?></option>
                                                        <?php
                                                                    }
                                                                }
                                                            }
                                                        ?>                                                      
                                                    </select>
                                          </div>
                                          
                                      </div>
                                       <div class="col-lg-1" style="margin-left:10px;">
                                         <div class="form-actions">
                                            <input type="submit" name="unapprove_save" class="btn btn-primary add_approve_invoice_transaction" id="unapprove_save" value="For Approval" /><br/>
                                            <i>Save Invoice for approval</i>
                                          </div>
                                      </div>
                                      <?php 
                                              if($logSession->type!=4 && $logSession->type!=5 && $logSession->proxy_type!=4 && $logSession->proxy_type!=5) {
                                       ?>
                                       <div class="col-lg-1" style="margin-left:10px;">
                                         <div class="form-actions">
                                            <input type="submit" name="approve_invoice" class="btn btn-primary add_invoice_transaction" id="approve_invoice" value="Approve" /><br/>
                                            <i>Approve Invoice for account posting</i>
                                            </div>
                                         </div>
                                       <?php
                                                }
                                        ?>
                                         <div class="col-lg-1" style="margin-left:0px;">
                                         <div class="form-actions">
                                         <a href="<?php echo $this->sitePath."transaction/invoice"; ?>">
                                            <button type="button" class="btn">Cancel</button>
                                        </a>
                                            </div>
                                         </div>
                                    </div>

                               

                                </form>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
     
   <?php 
        }
    ?>
 
<script type="text/javascript">


  var productJson;

  $(document).ready(function(){


  $('#customer').on("change",function(){
      //alert("ok");
      var value = $(this).find('option:selected').val();
      var coa   = $(this).find('option:selected').data('coa');
      if(value!='') {
          $.ajax({
            type: "POST",
            url: "<?php echo $this->sitePath.'transaction/invoice/ajax-refresh'; ?>",
            data: 'action=getPayAccount&coa='+coa,
            success: function (html) {
              //  $("#payment_account").html(html);
                $("#addpay_pay_account").html(html);
            }
          });
      } else {
       // $("#payment_account").html('<option value="">Select</option>');
        $("#addpay_pay_account").html('<option value="">Select</option>');
      }
  });
        
     $.ajax({
        type: "POST",
        url: "<?php echo $this->sitePath.'transaction/invoice/ajax-refresh'; ?>",
        data: 'action=productRefresh',
        success: function (html) {
            productJson = $.parseJSON(html);
          //  console.log(productJson);
        }
      }); 
  });

  $(function() {
      var credit = $("#credit_term").val();
      if(credit==1) {
        $("#payment_trigger").val("1");
        $("#trigger_payment").show();
     }
  });
      var counter = 2;
    $("#invoice_row").on("click", function () {
        /* if(counter>5){
                    alert("Only 5 shipping address allowed");
                    return false;
         } */   

         var tax_code = '<select name="tax_code_' +counter+ '" id="tax_code_' +counter+ '"  class="form-control" required  onchange="return calculateTotal();"><option value="">Select</option>';

         <?php

            if(isset($this->invoiceCustom[0]['default_tax_code']) && $this->invoiceCustom[0]['default_tax_code']==0) {
              $selected = 'selected';
            } else {
              $selected = '';
            }
         ?>
         tax_code += '<option value="0" title="Not Applicable" <?php echo $selected; ?>>NA</option>';

         <?php
            $taxSelect = '';
            foreach ($this->taxCode as $tax) {
                $id = $tax['id']."_".$tax['tax_percentage'];
                $name = $tax['tax_code']." - ".$tax['tax_percentage']." %";
                $taxdesc = ucfirst(str_replace("\r\n", " ", $tax['description']));
                if(isset($this->invoiceCustom[0]['default_tax_code']) && !empty($this->invoiceCustom[0]['default_tax_code'])) {
                  if($this->invoiceCustom[0]['default_tax_code']==$tax['id']) {
                     $taxSelect = 'selected';
                  }
                  else {
                     $taxSelect = '';
                  }
                } 
                foreach ($this->supply as $key => $supply) {
                  if($tax['tax_code']==$key) {
                      $code = $supply['name']." - ".$tax['tax_percentage']." %";
                  }
                }
         ?>
           tax_code += '<option value="<?php echo $id; ?>" title="<?php echo $taxdesc; ?>" <?php echo $taxSelect; ?>><?php echo $code; ?></option>';
         <?php
            }
         ?>

         tax_code += '</select>';

        var product_desc = '<div id="productRefresh'+counter+'"><select name="product_description_' +counter+ '" id="product_description_' +counter+ '"  class="form-control" required  onchange="return productSelect('+counter+',this.value);"><option value="">Select</option>';

         <?php
            /*foreach ($this->product as $product) {
                $id = $product['id']."_".$product['product_id']."_".$product['price'];
                $name = $product['name'];*/
         ?>

         $.each(productJson, function(){
            var idValue = this.id+"_"+this.product_id+"_"+this.price;
            product_desc += '<option value="'+idValue+'">'+this.name+'</option>';
         
         });
           
         <?php
          //  }
         ?>

         product_desc += '</select></div>';


         var newTextBoxDiv = $(document.createElement('tr'))
              .attr("id", 'TextBoxDiv' + counter);
         // alert(expense_type);
         newTextBoxDiv.html('<td style="width:2%;"><a href="javascript:void(0)" value="removeButton"  class="remove_product"><i class="icon-cancel-circle-2"></i></a> </td>'+
                            '<td style="width:15%;"><input type="text" name="product_id_'+counter+'" id="product_id_'+counter+'" class="form-control" required readonly /></td>' +
                            '<td style="width:20%;">'+product_desc+'<a href="<?php echo $this->sitePath."settings/add-product"; ?>" title="Click to add new <?php echo $productTitle; ?>" data-title="Click to add new <?php echo $productTitle; ?>" target="_blank" class="add-product" onclick="productRefresh();"><i class="icon-plus-circle-2"></i> Add New <?php echo $productTitle; ?></a>  &nbsp; </td>' +
                            '<td style="width:7%;"><input type="text" name="quantity_'+counter+'" id="quantity_'+counter+'" class="form-control" required  number="true" autocomplete="off" minlength="1" maxlength="5"  onkeyup="return calculateTotal();" /></td>' +
                            '<td style="width:15%;"><input type="text" name="price_'+counter+'" id="price_'+counter+'" class="form-control amount-align"  required  readonly number="true"  onkeyup="return calculateTotal();" readonly /></td>' +
                            '<td style="width:12%;"><input type="text" name="discount_amount_'+counter+'" id="discount_amount_'+counter+'" class="form-control amount-align" autocomplete="off" number="true" minlength="1"  onkeyup="return calculateTotal();" onchange="return numberWithCommasInput(this.value,this.id);" /></td>'+
                            '<td style="width:15%;">'+tax_code+'</td><td style="text-align:right; padding-right:40px;"><strong id="net_amount_'+counter+'"></strong>&nbsp;</td></tr>');

         newTextBoxDiv.appendTo("#invoice_detail");
        $("#product_counter").val(counter);
         counter++;
    });

    $(document).on('click',".remove_product",function (){   
        /* if(counter==1){
            alert("No more shipping addresses to remove");
            return false;
        } */  

        counter--;

        $("#TextBoxDiv" + counter).remove();
        $("#product_counter").val(counter-1);
        calculateTotal();
    });

/*function shippingAddress(value) {
    var i=1;
    shipping_address = '';
    if(value=='') {
        $("#shipping_address").html('<option value="">Select Shipping Address</option>');
    } else {
        shipping_address += '<option value="0">Default Shipping Address</option>';
         <?php
            foreach ($this->shipping as $shipping) {
                $id = $shipping['id'];
         ?>
            if(value==<?php echo $shipping['fkcustomer_id']; ?>) {
                shipping_address += '<option value="<?php echo $id; ?>">Shipping Address '+i+'</option>';
                i++;
            }
         <?php
            }
         ?>
         $("#shipping_address").html(shipping_address);
    }
}*/

function shippingAddress(value) {
  if(value!='') {
    $.ajax({
        type: "POST",
        url: "<?php echo $this->sitePath.'transaction/invoice/ajax-refresh'; ?>",
        data: 'action=shippingDetails&cust_id='+value,
        success: function (html) {
           $("#shipping_address").html(html);
        }
      }); 
  } else {
    $("#shipping_address").html('<option value="">Select</option>');
  }
}

function productSelect(idValue,pid) {
    var prod_id    = pid.split('_');
    $("#product_id_"+idValue).val(prod_id[1]);
    $("#price_"+idValue).val(numberWithCommasInput(prod_id[2],''));
    calculateTotal();
}

function creditSelect() {
    var value = $("#credit_term").val();
    if(value!=1) {
        var creditDate = '';
        <?php
            foreach ($this->creditTerm as $key => $credit) {
         ?>
            if(value==<?php echo $key; ?>) {
                <?php
                  if($key!=1) {
                ?>
                creditDate = <?php echo $credit; ?>
                <?php 
                    }
                ?>
            }
         <?php
            }
         ?>
        var invdate = $("#date").val();
        var split_date = invdate.split('-');
        var today = new Date(split_date[2],split_date[1]-1,split_date[0]);
        var date = new Date(split_date[2],split_date[1]-1,split_date[0]);
        date.setDate(today.getDate()+creditDate);
        var dd    =  date.getDate();
        var mm   = date.getMonth();
        if(dd<10) {
          dd = "0" + dd;
        } else {
            dd = dd;
        }
       if(mm<10) {
        mm = "0" + (mm+1);
        } else {
            mm = mm+1;
        }
        var yyyy = date.getFullYear(); 
        var fullDate = dd+"-"+mm+"-"+yyyy;
         $("#due_date").val(fullDate);
    } else {
        var invdate = $("#date").val();
        var split_date = invdate.split('-');
        var today = new Date(split_date[2],split_date[1]-1,split_date[0]);
        var date = new Date(split_date[2],split_date[1]-1,split_date[0]);
        date.setDate(today.getDate());
        var dd    =  date.getDate();
        var mm   = date.getMonth();
        if(dd<10) {
          dd = "0" + dd;
        } else {
            dd = dd;
        }
       if(mm<10) {
        mm = "0" + (mm+1);
        } else {
            mm = mm+1;
        }
        var yyyy = date.getFullYear(); 
        var fullDate = dd+"-"+mm+"-"+yyyy;
         $("#due_date").val(fullDate);
    }
     triggerPayment();
}

function discountPayment(value) {
    if(value==1) {
        $("#discount_amount").removeAttr("disabled");
    } else if(value==2) {
        $("#discount_amount").val("0");
        $("#discount_amount").attr("disabled","true");
    }
}


function discountAddPayment(value) {
    if(value==1) {
        $("#discount_payment_amount").removeAttr("disabled");
    } else if(value==2) {
        $("#discount_payment_amount").val("0");
        $("#discount_payment_amount").attr("disabled","true");
    }
}

function calculateTotal() {
    var invoice_count   = $("#product_counter").val();
    var sub_total  = 0.00;
    var sub_gst  = 0.00;
    var total_gst_amount  = 0.00;
    var grand_total = 0.00;
    var grand_total_sgd = 0.00;
    for(var i = 1; i<=invoice_count;i++) {
        var net_amount = 0.00;
        var total_gst  = 0.00;
        var quantity = $("#quantity_"+i).val();
        var price    = $("#price_"+i).val();
        var discount_amount = $("#discount_amount_"+i).val();
        var tax_code = $("#tax_code_"+i).val(); 
        var myTax    = tax_code.split('_');
        if(quantity!=0 && quantity!='' && price!=0 && price!='') {
            var net_amount = (quantity * numberWithCommas(price,'format')) - numberWithCommas(discount_amount,'format');
        }
        if(myTax[0]!=0 && myTax[0]!='' && myTax[1]!=0 && myTax[1]!='') {
            total_gst = parseFloat(myTax[1]);
        }
        $("#net_amount_"+i).text(numberWithCommas(parseFloat(net_amount).toFixed(2),'normal'));
        sub_total += parseFloat(net_amount);
        sub_gst   += (parseFloat(net_amount) * parseFloat(total_gst) / 100);
    }
   // total_gst_amount += (parseFloat(sub_total) * parseFloat(total_gst) / 100);
    grand_total += parseFloat(sub_total) + parseFloat(sub_gst);
    $("#sub_total").text(numberWithCommas(parseFloat(sub_total).toFixed(2),'normal'));
    $("#total_gst").text(numberWithCommas(parseFloat(sub_gst).toFixed(2),'normal'));
    $("#grand_total").text(numberWithCommas(parseFloat(grand_total).toFixed(2),'normal'));
    gp_convertIt(parseFloat(grand_total));
}


function payTotal() {
    var invoice_count   = $("#product_counter").val();
    var sub_total  = 0.00;
    var sub_gst  = 0.00;
    var total_gst_amount  = 0.00;
    var grand_total = 0.00;
    var grand_total_sgd = 0.00;
    for(var i = 1; i<=invoice_count;i++) {
        var net_amount = 0.00;
        var total_gst  = 0.00;
        var quantity = $("#quantity_"+i).val();
        var price    = $("#price_"+i).val();
        var discount_amount = $("#discount_amount_"+i).val();
        var tax_code = $("#tax_code_"+i).val(); 
        var myTax    = tax_code.split('_');
        if(quantity!=0 && quantity!='' && price!=0 && price!='') {
            var net_amount = (quantity * numberWithCommas(price,'format')) - numberWithCommas(discount_amount,'format');
        }
        if(myTax[0]!=0 && myTax[0]!='' && myTax[1]!=0 && myTax[1]!='') {
            total_gst = parseFloat(myTax[1]);
        }
        $("#net_amount_"+i).text(numberWithCommas(parseFloat(net_amount).toFixed(2),'normal'));
        sub_total += parseFloat(net_amount);
        sub_gst   += (parseFloat(net_amount) * parseFloat(total_gst) / 100);
    }
   // total_gst_amount += (parseFloat(sub_total) * parseFloat(total_gst) / 100);
    grand_total += parseFloat(sub_total) + parseFloat(sub_gst);
    return numberWithCommas(parseFloat(grand_total).toFixed(2),'normal');
}


function changeTransactionStatus(Idvalue,status) {
    window.location.href='<?php echo $this->sitePath; ?>transaction/expense/index/verifyid/'+Idvalue+'/status/'+status;
}

function deleteExpense(Idvalue) {
  var confirmMsg = confirm("Are you sure want to delete this expense transaction? You cannot undo this action");
    if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>transaction/expense/index/delid/'+Idvalue;
    }
}
function copyTransaction(Idvalue) {
  var confirmMsg = confirm("Are you sure want to copy this expense transaction?");
    if(confirmMsg) {
        $.ajax({
            type: "POST",
            url: "<?php echo $this->sitePath; ?>transaction//ajax-call",
            data: "ajaxAction=copy_transaction&tid="+Idvalue,
            success: function (html) {
                $('#add_expense').hide(500);
                $('#copy_expense').hide(500);
                $('#copy_transaction').html(html);
                $('#copy_expense').show(1500);
            }
    });
    }
}

 function numberWithCommas(x,action) {
  if(action=='normal') {
    var value = x.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
    return value;
  } else if(action=='format')  {
    var value  = x.replace(/\,/g,''); 
    return value;
  }
}

 function numberWithCommasInput(x,id) {
    if(id=='') {
        var amount = parseFloat(x).toFixed(2);
        var value  = amount.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
        return value;
    } else {
        var amount = parseFloat(x).toFixed(2);
        var value  = amount.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
        $("#"+id).val(value);
    }
}

 function saveDraft() {
  $(".btn").attr("disabled",true);
    $.ajax({
      type: "POST",
      url: "<?php echo $this->sitePath.'transaction/invoice/ajax-call'; ?>",
      data: $('#add-invoice').serialize(),
      success: function (html) {
          if(html=='success') {
             $(".btn").attr("disabled",false);
              window.location.href='<?php echo $this->sitePath; ?>transaction/invoice';
          } else {
             $('#failure').html('<strong>Invoice cannot be saved as draft</strong>');
             $('#failure').fadeIn(1000);
             $('#failure').fadeOut(9000);
             $(".btn").attr("disabled",false);
          }
      }
    }); 
 }
 
 function gp_convertIt(amount) {
  if (amount=='' || amount==0){
    return false;
  } else {
  var gp_from = document.getElementById('currency').value;
    if(gp_from!='SGD') {
      var gp_to   = 'SGD';
      var gp_amount = amount;
      $.getJSON( "http://www.geoplugin.net/currency_converter.gp?jsoncallback=?", { from:gp_from, to:gp_to, amount:gp_amount }, 
        function(output){
          $("#grand_total_sgd").html(output.to.symbol+output.to.amount);
        });
    } else {
      $("#grand_total_sgd").html("$ 0.00");
    }
  }
}

function refreshList(type) {
  if(type==1) {
        var customerId = $("#customer").val();
        $.ajax({
        type: "POST",
        url: "<?php echo $this->sitePath.'transaction/invoice/ajax-refresh'; ?>",
        data: 'action=customerRefresh&id='+customerId,
        success: function (html) {
            $("#customer").html(html);
        }
      }); 
  } 
}


function refreshProductList() {
        var invoice_count   = $("#product_counter").val();
        $.ajax({
        type: "POST",
        url: "<?php echo $this->sitePath.'transaction/invoice/ajax-refresh'; ?>",
        data: 'action=productRefresh',
        success: function (html) {
                productJson = $.parseJSON(html);
                for(var i=1;i<=invoice_count;i++) {
                  var productSelect = '';
                  var productValue = $("#product_description_"+i).val();
                  var product_desc = '<select name="product_description_'+i+ '" id="product_description_' +i+ '"  class="form-control" required onchange="return productSelect('+i+',this.value);"><option value="">Select</option>';
                    $.each(productJson, function(){
                        var idValue = this.id+"_"+this.product_id+"_"+this.price;
                        if(productValue==idValue) 
                            productSelect = 'selected';
                        else
                            productSelect = '';
                        product_desc += '<option value='+idValue+' '+productSelect+'>'+this.name+'</option>'
                   
                    });
                  product_desc += '</select>';
                  $("#productRefresh"+i).html(product_desc);
                }
        }
      }); 
}


function discountTriggerPayment(value) {
    if(value==1) {
        $("#addpay_discount_payment_amount").removeAttr("disabled");
    } else if(value==2) {
        $("#addpay_discount_payment_amount").val("0");
        $("#addpay_discount_payment_amount").attr("disabled","true");
    }
}

function triggerPayment() {
    var credits          = $("#credit_term").val();
    var amount           = payTotal();
    $("#addpay_pay_amount").val(amount);
    if(credits==1) {
      $("#payment_trigger").val("1");
      $("#trigger_payment").show();
    } else {
      $("#trigger_payment").hide();
      $("#payment_trigger").val("0");
    } 
}

 function reloadPage(value) {
  window.location.href='<?php echo $this->sitePath; ?>transaction/invoice/add/currency/'+value;
 }

</script>