<?php
   $logSession = new Zend_Session_Namespace('sess_login');
    $productTitle = 'Product';
    if(isset($this->invoiceCustom[0]['default_product_title']) && $this->invoiceCustom[0]['default_product_title']==1) {
         $productTitle = 'Product';
    } else if(isset($this->invoiceCustom[0]['default_product_title']) && $this->invoiceCustom[0]['default_product_title']==2) {
         $productTitle = 'Service';
    } else if(isset($this->invoiceCustom[0]['default_product_title']) && $this->invoiceCustom[0]['default_product_title']==3) {
         $productTitle = 'Product / Service';
    }

  function convertCurrency($amount, $from){
      $to   = 'SGD';
      $url  = "https://www.google.com/finance/converter?a=$amount&from=$from&to=$to";
      $data = file_get_contents($url);
      preg_match("/<span class=bld>(.*)<\/span>/",$data, $converted);
      $converted = preg_replace("/[^0-9.]/", "", $converted[1]);
      return round($converted, 3);
  }
?>
<div id="popup">
<span class="button b-close"><span>X</span></span>
<div class="row" id="add_payment">
 <h4>Add Payment</h4>
<div class="widget-container col-md-12 col-md-offset-1">
 <form class="form-horizontal" id="add-payment" method="post">
    <div class="form-group">
      <label class="control-label col-lg-4">Payment Date <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <input type="hidden" name="invoice_id" id="invoice_id" />
            <input type="hidden" name="pay_id" id="pay_id" />
            <input type="text" name="date" id="date" class="form-control date-pick" placeholder="Select Date"  autocomplete="off"  />
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Payment / Accruals Account <span class="mandatory">*</span></label>
        <div class="col-lg-5">
             <select class="form-control" name="pay_account" id="pay_account">
                <option value="">Select</option>
                    <?php
                        if(isset($this->payAccount) && !empty($this->payAccount)) {
                            foreach ($this->payAccount as $payAccount) {
                    ?>
                        <option value="<?php echo $payAccount['id']; ?>"><?php echo $payAccount['account_name']; ?></option>
                    <?php
                            }
                        }
                    ?>                                                       
              </select>
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Amount <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <input type="text" name="pay_amount" id="pay_amount" class="form-control" placeholder="Enter Amount"  autocomplete="off"  />
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Payment Method <span class="mandatory">*</span></label>
        <div class="col-lg-5">
          <select name="pay_method" id="pay_method" class="form-control">
            <option value="">Select</option>
           <?php 
                foreach ($this->payMethod as $key => $pay) {
           ?>
                <option value="<?php echo $key; ?>"><?php echo $pay; ?></option>
           <?php
                }
           ?>
          </select>
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Bank Cheque / Draft No </label>
        <div class="col-lg-5">
            <input type="text" name="cheque_draft_no" id="cheque_draft_no" class="form-control" placeholder="Enter Cheque / Draft No"  autocomplete="off"  />
        </div>
    </div>
     <div class="form-group">
      <label class="control-label col-lg-4">Prompt Payment Discount <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <select class="form-control" name="payment_discount" id="payment_discount" onchange="discountPayment(this.value);">
                <option value="1">Yes</option>  
                <option value="2" selected>No</option>  
            </select>
        </div>
    </div>
     <div class="form-group">
      <label class="control-label col-lg-4">Discount Amount <span class="mandatory">*</span></label>
        <div class="col-lg-5">
            <input type="text" name="discount_amount" id="discount_amount" class="form-control" value="0" disabled  autocomplete="off" />
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-lg-4">Additional Description / Notes </label>
        <div class="col-lg-5">
        <textarea name="description" id="description" class="form-control"></textarea>
        </div>
    </div>

     <div class="form-group">
        <div class="col-lg-8 col-lg-offset-3">
            <div class="form-actions">
               <input type="submit" name="update_payment" class="btn btn-primary " id="update_payment" value="Update Payment" />
                <button type="reset" class="btn" onclick="return bPopup_close();">Cancel</button>
            </div>
        </div>
     </div>

</form>
</div>
</div>
</div>

   <div class="row">
       <div class="col-md-12">
            <p>
              <a href="<?php echo $this->sitePath."transaction/invoice"; ?>" class="btn btn-danger border-none">Invoice</a><a href="<?php echo $this->sitePath."transaction/credit"; ?>" class="btn btn-default border-none">Credit Note</a>
            </p>
       </div>
   </div>

<div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            </div>
   </div>
<div class="row">
<div class="col-md-12">
                            <div class="square-widget">
                                <div class="widget-head clearfix">
                                    <h4 class="pull-left"><i class="icon-user-4"></i> Invoice Transaction Details</h4>
                                </div>
                                <div class="widget-container" style="margin-left:50px;">
                                <div class="row">
                                    <div class="col-md-3">
                                        <strong>Invoice No </strong> <br/>
                                        <span><?php echo $this->invoice[0]['invoice_no']; ?></span>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Date </strong> <br/>
                                        <span><?php echo date("d-m-Y",strtotime($this->invoice[0]['date'])); ?></span>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Customer / Payee </strong> <br/>
                                        <span><?php echo $this->invoice[0]['customer_name']; ?></span>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Credit Term </strong> <br/>
                                        <span>
                                        <?php 
                                          if(isset($this->creditTerm) && !empty($this->creditTerm)) {
                                              foreach ($this->creditTerm as $key => $credit) {
                                                if($key==$this->invoice[0]['credit_term']) {
                                                  if($key==1) {
                                                      echo $credit;
                                                  } else if($key!=1) {
                                                      echo $credit." Days";
                                                  }
                                                }
                                              }
                                          }
                                        ?>
                                        </span>
                                       
                                    </div>
                                </div>
                                <br/>
                                <div class="row">
                                    <div class="col-md-3">
                                        <strong>Transaction Currency </strong><br>
                                        <span>
                                        <?php 
                                          if(isset($this->currencies) && !empty($this->currencies)) {
                                            foreach ($this->currencies as $key => $currency) {
                                              if($key==$this->invoice[0]['transaction_currency']) {
                                                  echo $currency." - ".$key;
                                                }
                                            }
                                          }
                                        ?>
                                        </span>
                                        
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Due Date </strong><br>
                                        <span><?php echo date("d-m-Y",strtotime($this->invoice[0]['due_date'])); ?></span>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Prompt Payment Discount  </strong><br>
                                        <span><?php if($this->invoice[0]['discount_status']==1) { echo "Yes";} else if($this->invoice[0]['discount_status']==2) { echo "No"; } ?></span>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Non Revenue Supply (Tax)</strong><br>
                                        <span><?php if($this->invoice[0]['non_revenue_tax']==1) { echo "Yes";} else if($this->invoice[0]['non_revenue_tax']==2) { echo "No"; } ?></span> 
                                    </div>
                                </div>
                                <br/>
                                <div class="row">
                                    <div class="col-md-3">
                                        <strong>Memo  </strong><br/>
                                        <span><?php echo $this->invoice[0]['memo']; ?></span> 
                                    </div>
                                    <div class="col-md-3">
                                        <strong>D.O / S.O No </strong><br/>
                                        <span><?php echo $this->invoice[0]['do_so_no']; ?></span>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Shipping Address  </strong><br/>
                                        <span>
                                        <?php 
                                        if($this->invoice[0]['fkshipping_address']==0) {
                                            echo "Default Shipping Address";
                                        } else {
                                            echo ucfirst($this->invoice[0]['shipping_address1']); 
                                        }
                                        ?>
                                        </span>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Approval By / For </strong><br>
                                        <span>
                                        <?php 
                                            if(isset($this->approveUser) && !empty($this->approveUser)) {
                                                foreach ($this->approveUser as $approve) {
                                                  if($approve['account_type']==0) {
                                                        $account_type = "Developer";
                                                  } 
                                                  else if($approve['account_type']==1) {
                                                        $account_type = "Developer";
                                                  } 
                                                  else if($approve['account_type']==2) {
                                                        $account_type = "Super User";
                                                  } else if($approve['account_type']==3) {
                                                        $account_type = "Manager";
                                                  }
                                                  if($approve['id']==$this->invoice[0]['approval_for']) {
                                                        echo $approve['username']." - ".$account_type;
                                                  }
                                                }
                                            }
                                        ?>
                                        </span>
                                    </div>
                                    
                                </div>

                                <br/>
                                <div class="row">
                                <div class="col-md-3">
                                        <strong>Status  </strong><br/>
                                        <span>
                                       <?php
                                         if($this->invoice[0]['invoice_status']==1) {
                                            $status = "Saved";
                                         } else if($this->invoice[0]['invoice_status']==2) {
                                            $status = "Saved";
                                         } else if($this->invoice[0]['invoice_status']==3) {
                                            $status = "Draft";
                                         } 
                                         if($this->invoice[0]['sent_status']==1) {
                                            $status .= " & Sent";
                                         }
                                         echo $status;
                                        ?>
                                        </span> 
                                    </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
<div class="row">
                         <div class="col-md-12">
                            <div class="square-widget">
                                <h5 class="pull-left"><i class="icon-user-4"></i> Product Details</h5>
                                <div class="widget-container">
                                    <table class="table responsive">
                                        <thead>
                                            <tr>
                                            <th style="width:2%;"></th>
                                                <th>
                                                    <?php echo $productTitle; ?> ID
                                                </th>
                                                <th>
                                                    <?php echo $productTitle; ?> Description
                                                </th>
                                                <th>
                                                    Quantity
                                                </th>
                                                <th>
                                                    Unit Price
                                                </th>
                                                 <th>
                                                    Discount
                                                </th>
                                                <th>
                                                    Tax Code
                                                </th>
                                                <th>
                                                    Amount
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody id="invoice_detail">
                                        <?php
                                            $j=1;
                                            $total_gst = 0.00;
                                            $sub_total = 0.00;
                                            foreach ($this->invoiceProductList  as $invoiceProduct) {
                                                $net_amount = $invoiceProduct['quantity'] * $invoiceProduct['unit_price'] - $invoiceProduct['discount_amount'];
                                                $total_gst += $net_amount * $invoiceProduct['tax_value'] / 100;
                                                $sub_total += $net_amount;
                                        ?>
                                            <tr>
                                                <td style="width:2%;"></td>
                                                <td style="width:15%;">
                                                    <?php echo $invoiceProduct['product_id']; ?>
                                                </td>
                                                <td style="width:20%;">
                                                        <?php
                                                            foreach ($this->product as $product) {
                                                                if($invoiceProduct['product_description']==$product['id']) {
                                                                    echo ucfirst($product['name']);
                                                                }
                                                            }
                                                        ?>
                                                        
                                                </td>
                                                <td style="width:5%;">
                                                    <?php echo $invoiceProduct['quantity']; ?>
                                                </td>
                                                <td>
                                                    <?php echo number_format($invoiceProduct['unit_price'],2,'.',','); ?>
                                                </td>
                                                <td>
                                                    <?php echo number_format($invoiceProduct['discount_amount'],2,'.',','); ?>
                                                </td>
                                                <td style="width:15%;">
                                                    <?php
                                                        if(isset($this->taxCode) && !empty($this->taxCode) && $this->taxCode!=0 && $this->invoiceProduct['fktax_id']!=0) {
                                                            foreach ($this->taxCode as $tax) {
                                                                if($invoiceProduct['fktax_id']==$tax['id']) {
                                                                  foreach ($this->supply as $key => $supply) {
                                                                      if($tax['id']==$key) {
                                                                        echo $supply['name']." - ".$tax['tax_percentage']." %";
                                                                      }
                                                                  }
                                                                }
                                                            }
                                                        } else {
                                                         echo "NA - Not Applicable";
                                                        }
                                                    ?>                                                  
                                                </td>
                                                <td>
                                                    <strong id="net_amount_<?php echo $j; ?>"><?php echo number_format($net_amount,2,'.',','); ?></strong>
                                                </td>
                                            </tr>
                                            <?php 
                                                    $j++;
                                                }
                                            ?>
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <hr/>
                        <div class="row">
                            <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Sub Total : </label>
                                    <span id="sub_total"><?php echo number_format($sub_total,2,'.',','); ?></span> <br/>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Total GST : </label>
                                    <span id="total_gst"><?php echo number_format($total_gst,2,'.',','); ?></span>
                             </div>
                        </div>

                            <div class="row">
                            <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Grand Total : </label>
                                    <span id="grand_total"><?php 
                                   $over_all = $sub_total+$total_gst; 
                                        echo number_format($over_all,2,'.',',');
                                   ?></span>
                                </div>
                             </div>
                            <div class="row">
                            <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Grand Total SGD :</label>
                                    <span id="grand_total_sgd"></span>
                                </div>
                             </div>

                            </div>


<div class="row">
                         <div class="col-md-12">
                            <div class="square-widget">
                                <h5 class="pull-left"><i class="icon-user-4"></i> Payment Details</h5>
                                <div class="widget-container">
                                    <table class="table responsive">
                                        <thead>
                                            <tr>
                                                <th>
                                                    Date
                                                </th>
                                                <th>
                                                    Payment Method
                                                </th>
                                                <th>
                                                    Bank Cheque / Draft No
                                                </th>
                                                <th>
                                                    Amount
                                                </th>
                                                <!-- <th>
                                                    Actions
                                                </th> -->
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php 
                                            $paid_amount = 0.00;          
                                             if(isset($this->invoicePayment) && !empty($this->invoicePayment)) {                                
                                            foreach ($this->invoicePayment  as $payment) {
                                                $paid_amount += $payment['payment_amount'];
                                        ?>
                                            <tr>
                                                <td><?php echo date("d-m-Y",strtotime($payment['date'])); ?></td>
                                                <td>
                                                <?php 
                                                    foreach ($this->payMethod as $key => $pay) {
                                                        if($key==$payment['payment_method']) {
                                                            echo $pay;
                                                        }
                                                    }
                                                 ?>
                                                </td>
                                                <td><?php echo ucfirst($payment['cheque_draft_no']); ?></td>
                                                <td><?php echo number_format($payment['payment_amount'],2,'.',','); ?></td>
                                             <!--   <td>
                                                     <?php 
                                                        if($logSession->type!=5) {
                                                   ?>
                                            <a href="javascript:void(0)" onclick="return editPayment('<?php echo $this->inv_id; ?>','<?php echo $payment['id']; ?>','<?php echo $payment['discount_status']; ?>','<?php echo $payment['discount_amount']; ?>','<?php echo $payment['payment_description']; ?>','<?php echo date("d-m-Y",strtotime($payment['date'])); ?>','<?php echo $payment['fkpayment_account']; ?>','<?php echo $payment['payment_amount']; ?>','<?php echo $payment['payment_method']; ?>','<?php echo $payment['cheque_draft_no']; ?>')" data-original-title="Edit Payment" title="Edit Payment"><i class="icon-pencil-2"></i></a>

                                            <a href="javascript:void(0)" onclick="return deletePayment('<?php echo base64_encode($this->inv_id); ?>','<?php echo base64_encode($payment['id']); ?>');" data-original-title="Delete Payment" title="Delete Payment"><i class="icon-remove-2"></i></a>  

                                                <?php
                                                        }
                                                    ?>                                                       
                                                </td> -->
                                            </tr>
                                        <?php
                                            }
                                        ?>
                                          <tr>
                                           <td colspan="3"><h5 align="right"><strong>Total</strong></h5></td>
                                           <td><?php echo number_format($paid_amount,2,'.',','); ?></td>
                                          </tr>
                                        <?php
                                           } else {
                                        ?>  
                                          <tr>
                                           <td colspan="4"><h5 align="center"><strong>No Payment has been received yet</strong></h5></td>
                                          </tr>
                                        <?php
                                          }
                                        ?>
                                        </tbody>
                                        </table>
                                    </div>
                                </div>
                        </div>
                </div>


<div class="row">
                         <div class="col-md-12">
                            <div class="square-widget">
                                <h5 class="pull-left"><i class="icon-user-4"></i> Credit Notes if any</h5>
                                <div class="widget-container">
                                    <table class="table responsive">
                                        <thead>
                                            <tr>
                                            <th>
                                                Date
                                            </th>
                                            <th>
                                                Credit Note No
                                            </th>
                                            <th>
                                               Description
                                            </th>
                                            <th style="text-align:center; padding-right:35px;">
                                               Total Amount
                                            </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php 
                                            $total_credit = 0.00;               
                                             if(isset($this->invoiceCredit) && !empty($this->invoiceCredit)) {                           
                                            foreach ($this->invoiceCredit  as $invCre) {
                                               $total_amount   = $invCre['amount'] + $invCre['tax_amount'];
                                               if($this->invoice[0]['transaction_currency']!='SGD') {
                                                  $converted_amount = convertCurrency($total_amount,$this->invoice[0]['transaction_currency']);
                                               } else {
                                                  $converted_amount = $total_amount;
                                               }
                                               $total_credit  += $converted_amount;
                                        ?>
                                            <tr>
                                                <td><?php echo date("d-m-Y",strtotime($invCre['date'])); ?></td>
                                                <td><?php echo $invCre['credit_no']; ?></td>
                                                <td><?php echo ucfirst($invCre['memo']); ?></td>
                                                <td style="text-align:center; "><?php echo number_format($converted_amount,2,'.',','); ?></td>

                                            </tr>
                                        <?php
                                            }
                                        ?>
                                          <tr>
                                          <td colspan="3" align="right">
                                            <h5 align="right"><strong>Total</strong></h5>
                                          </td>
                                          <td style="text-align:center; "><?php echo number_format($total_credit,2,'.',','); ?></td>
                                          </tr>
                                        <?php
                                           } else {
                                        ?>  
                                          <tr>
                                           <td colspan="5"><h5 align="center"><strong>No Credit Note has been added under this invoice</strong></h5></td>
                                          </tr>
                                        <?php
                                          }
                                        ?>
                                        </tbody>
                                        </table>
                                    </div>
                                </div>
                        </div>
                </div>


                 <div class="row">
                            <div class="col-md-4 col-md-offset-9">
                                   <label class="col-lg-4 control-label" style="padding-top:0px;">Amount Due :</label>
                                    <span id="total_amount_paid"></span>
                                </div>
                             </div>
<script type="text/javascript">

$(function() {
    gp_convertIt_Onload('<?php echo $over_all; ?>','<?php echo $paid_amount+$total_credit; ?>');
 });

function editPayment(Invid,Idvalue,discount_status,discount_amount,description,date,pay_account,pay_amount,pay_method,cheque) {
    $("#invoice_id").val(Invid);
    $("#pay_id").val(Idvalue);
    $("#payment_discount").val(discount_status);
    $("#discount_amount").val(discount_amount);
    $("#description").val(description);
    $("#date").val(date);
    $("#pay_account").val(pay_account);
    $("#pay_amount").val(pay_amount);
    $("#pay_method").val(pay_method);
    $("#cheque_draft_no").val(cheque);
        $('#popup').bPopup({
            modalClose: false,
            easing: 'easeOutBack', 
            speed: 1000,
            transition: 'slideDown',
            follow: [false, false], 
    });
}

 function numberWithCommas(x,action) {
  if(action=='normal') {
    var amount = parseFloat(x).toFixed(2);
    var value = amount.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
    return value;
  } else if(action=='format')  {
    var value  = x.replace(/\,/g,''); 
    return value;
  }
}

function deletePayment(Invid,Idvalue) {
  var confirmMsg = confirm("Are you sure want to delete this payment made for invoice? You cannot undo this action");
    if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>transaction/invoice/view/delid/'+Idvalue+'/id/'+Invid;
    }
}

 function bPopup_close() {
     $("#popup").bPopup().close();
 }

/*  function gp_convertIt_Onload(amount,paid_amount) {
  if (amount=='' || amount==0){
    return false;
  } else {
  var gp_from = '<?php echo $this->invoice[0]['transaction_currency']; ?>';
    if(gp_from!='SGD') {
      var gp_to   = 'SGD';
      var gp_amount = amount;
      $.getJSON( "http://www.geoplugin.net/currency_converter.gp?jsoncallback=?", { from:gp_from, to:gp_to, amount:gp_amount }, 
        function(output){
          $("#grand_total_sgd").html(output.to.symbol+output.to.amount);
          var convert_amount = numberWithCommas(output.to.amount,'format');
          $("#total_amount_paid").html(numberWithCommas(convert_amount-paid_amount,'normal'));
        });
    } else {
        $("#total_amount_paid").html(numberWithCommas(amount-paid_amount,'normal'));
    }
  }
}*/

function gp_convertIt_Onload(amount,paid_amount) {
  if (amount=='' || amount==0){
    return false;
  } else {
  var gp_from = '<?php echo $this->invoice[0]['transaction_currency']; ?>';
    if(gp_from!='SGD') {
      var gp_to   = 'SGD';
      var gp_amount = amount;
      $.ajax({
        type: "POST",
        url: "<?php echo $this->sitePath.'default/index/convert-currency'; ?>",
        data: 'action=converter&amount='+gp_amount+'&from='+gp_from,
        success: function (html) {
          var convert_amount = numberWithCommas(Number(html),'normal');
          $("#grand_total_sgd").html("$ "+convert_amount);
          $("#total_amount_paid").html(numberWithCommas(Number(html)-paid_amount,'normal'));
        }
      });
    } else {
        $("#total_amount_paid").html(numberWithCommas(amount-paid_amount,'normal'));
    }
  }
}
</script>