<?php
  function convertCurrency($amount, $from){
    $to   = 'SGD';
      $url  = "https://www.google.com/finance/converter?a=$amount&from=$from&to=$to";
      $data = file_get_contents($url);
      preg_match("/<span class=bld>(.*)<\/span>/",$data, $converted);
      $converted = preg_replace("/[^0-9.]/", "", $converted[1]);
      return round($converted, 3);
  }
?>
<ul class="breadcrumb">
   <li><a href="<?php echo $this->sitePath."default"; ?>"><i class="icon-home"></i></a></li>
   <li class="active">Credit Note</li>
</ul>
   <div class="row">
       <div class="col-md-12">
            <p>
              <a href="<?php echo $this->sitePath."transaction/invoice"; ?>" class="btn btn-default border-none">Invoice</a><a href="<?php echo $this->sitePath."transaction/credit"; ?>" class="btn btn-danger border-none">Credit Note</a>
            </p>
       </div>
   </div>




<div class="row">
           <div class="col-md-4 col-md-offset-4">
           <?php 
                if(isset($this->success) && !empty($this->success)) {
           ?>
                <div class="alert alert-success">
                   <strong><?php echo $this->success; ?></strong>
                </div>
            <?php
                } else if(isset($this->error) && !empty($this->error)) {
            ?>
                <div class="alert alert-danger">
                   <strong><?php echo $this->error; ?></strong>
                </div>
            <?php 
                }
            ?>
            </div>
   </div>
   <?php
     if(!empty($_GET['location']) && $_GET['location']) { 
         $show_filter = 'display:none;';
          $hide_filter = '';
        } else {   
           $show_filter = '';
          $hide_filter = 'display:none;';
          
        }
    $logSession = new Zend_Session_Namespace('sess_login');
   ?>
   <?php 
        if($logSession->type!=5 && $logSession->proxy_type!=5) {
   ?>
   <div class="row">
       <div class="col-md-12 grid-spacing">
       <a href="<?php echo $this->sitePath."transaction/credit/add"; ?>" class="btn btn-primary" type="button">Add Credit Note</a>
       <a href="javascript:void(0)" class="btn btn-primary" id="show_filter" style="<?php echo $show_filter; ?>" type="button">Show Filters</a>
       <a href="javascript:void(0)" class="btn btn-primary" id="hide_filter" type="button" style="<?php echo $hide_filter; ?>">Hide Filters</a>

            <!-- Element to pop up -->    
       </div>
   </div>
      
   <?php 
        }
    ?>

<div class="row" id="filters_id" style="<?php echo $hide_filter; ?>">
    <div class="col-md-12">

      <form class="form-horizontal" id="filter-by" method="get" novalidate="novalidate">
        <div class="form-group">

          <label class="col-lg-5 control-label">Branch </label>
          <div class="col-lg-3">
               <select class="form-control" name="location" id="locations" required>
                  <!-- <option value="all" <?php if($this->setlocation=='all') { echo "selected"; } ?>>All Branch</option> -->
                  <?php
                     if(isset($this->locations) && !empty($this->locations)) {
                        foreach ($this->locations as $location) {
                          if(isset($this->setlocation) && !empty($this->setlocation)) {
                            if($location['id']==$this->setlocation) {
                                 $locationSelect = 'selected';
                              } else {
                                 $locationSelect = '';
                              }
                          } else {
                             if($location['is_default']==1) {
                                 $locationSelect = 'selected';
                              } else {
                                 $locationSelect = '';
                              }
                          }
                  ?>
                        <option value="<?php echo $location['id']; ?>" <?php echo $locationSelect; ?>><?php echo ucwords($location['name']); ?></option>
                   <?php
                          }
                        }
                   ?>                                                      
                 </select>
          </div>

        </div>


        <div class="form-group">

          <label class="col-lg-5 control-label">Financial Year </label>
          <div class="col-lg-3">
               <select class="form-control" name="financial_year" id="financial_year" required>
                  <option value="all" <?php if($this->setfinance=='all') { echo "selected"; } ?>>All Financial Year</option>
                  <?php
                     $financeSelect = '';
                     if(isset($this->finance) && !empty($this->finance)) {
                        foreach ($this->finance as $finance) {
                          $start = date('d-m-Y',strtotime($finance['financial_start']));
                          $end   = date('d-m-Y',strtotime($finance['financial_end']));
                          if(isset($this->setfinance) && !empty($this->setfinance)) {
                            if($finance['id']==$this->setfinance) {
                                 $financeSelect = 'selected';
                              } else {
                                 $financeSelect = '';
                              }
                          } else {
                             if($finance['id']==$this->checkFinance) {
                                 $financeSelect = 'selected';
                              } else {
                                 $financeSelect = '';
                              }
                          }
                  ?>
                        <option value="<?php echo $finance['id']; ?>" <?php echo $financeSelect; ?>><?php echo $start." to ".$end; ?></option>
                   <?php
                          }
                        }
                   ?>                                                      
                 </select>
          </div>

        </div>


        <div class="form-group">
         <label class="col-lg-5 control-label">&nbsp;</label>
           <div class="col-lg-3">
              <div class="form-actions">
                <button type="submit" id="update" class="btn btn-primary">Filter</button>
                <a class="btn btn-default" href="<?php echo $this->sitePath."transaction/credit" ?>">
                Cancel</a>
              </div>
           </div>
        </div>
      </form>

    </div>
  </div>


 <div class="row">
                  <div class="col-md-12">
                          <h5 style="text-align:right;">
                            <strong>Sort By:</strong>
                            <a href="<?php echo $this->sitePath."transaction/credit" ?>" class="btn btn-primary" type="button"><?php if(isset($this->sort) && $this->sort=='') { ?><i class="icon-ok"><?php } ?></i> All</a>
                            <a href="<?php echo $this->sitePath."transaction/credit/index/sort/1" ?>" class="btn btn-primary" type="button"><?php if(isset($this->sort) && $this->sort==1) { ?><i class="icon-ok"><?php } ?></i> Verified</a>
                             <a href="<?php echo $this->sitePath."transaction/credit/index/sort/2" ?>" class="btn btn-primary" type="button"><?php if(isset($this->sort) && $this->sort==2) { ?><i class="icon-ok"><?php } ?></i> Unverified</a>
                             </h5>
                        </div>

                        <div class="col-md-12">
                            <div class="box-widget">
                                <table class="table responsive" id="credit-table">
                                    <thead>
                                        <tr>
                                            <th>
                                                Date
                                            </th>
                                            <th style="display:none;">Sortable Date</th>
                                            <th>
                                                Credit Note No
                                            </th>
                                            <th>
                                                Customer
                                            </th>
                                            <th>
                                               Branch
                                            </th>
                                            <th>
                                               Ref Invoice no
                                            </th>
                                            <th style="text-align:center;">
                                               Total Amount
                                            </th>
                                             <th>
                                                Status
                                            </th>
                                            <th style="text-align:center;">
                                                Actions
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php 
                                        if(isset($logSession->proxy_type) && !empty($logSession->proxy_type)) {
                                          $user_type = $logSession->proxy_type;
                                        } else {
                                          $user_type = $logSession->type;
                                        }
                                        $i=1;
                                        foreach($this->result as $results) {
                                            $exp_amount = 0.00;
                                            $total_amount   = $results['amount'] + $results['tax_amount'];

                                            foreach($this->creditExpense as $invExp) {
                                            if($invExp['id']==$results['id']) {
                                              $exp_amount = $invExp['amount'] + $invExp['tax_amount'];
                                            }
                                           }

                                           $total_amount = $total_amount-$exp_amount;

                                            if($results['transaction_currency']!='SGD') {
                                               $converted_amount = $results['exchange_rate']*$total_amount;
                                            } else {
                                              $converted_amount = $total_amount;
                                            }
                                    ?>
                                        <tr>
                                        <td><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['credit_status']; ?>','<?php echo $user_type; ?>')"><?php echo date("d-m-Y",strtotime($results['date'])); ?></a></td>
                                        <td style="display:none;"><?php echo date("Ymd",strtotime($results['date'])); ?></td>
                                        <td><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['credit_status']; ?>','<?php echo $user_type; ?>')"><?php echo $results['credit_no']; ?></a></td>
                                        <td><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['credit_status']; ?>','<?php echo $user_type; ?>')"><?php echo ucfirst($results['customer_name']); ?></a></td>
                                        <td><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['credit_status']; ?>','<?php echo $user_type; ?>')"><?php echo ucwords($results['location']); ?></a></td>
                                        <td><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['credit_status']; ?>','<?php echo $user_type; ?>')"><?php echo $results['invoice_no']; ?></a></td>
                                        <td style="text-align:right;"><a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['credit_status']; ?>','<?php echo $user_type; ?>')" style="margin-right:20px;"><?php echo number_format($converted_amount,2,'.',','); ?></a></td>
                                        <td>
                                        <a href="javascript:void(0)" class="setView" onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['credit_status']; ?>','<?php echo $user_type; ?>')">
                                        <?php
                                         if($results['credit_status']==1) {
                                            $status = "Approved";
                                         } else if($results['credit_status']==2) {
                                            $status = "Pending Approval";
                                         } else if($results['credit_status']==3) {
                                            $status = "Draft";
                                         } 
                                         if($results['sent_status']==1) {
                                            $status .= " & Sent";
                                         }
                                         echo $status;
                                        ?>
                                        </a>
                                        </td>
                                        <td class="action-bar" style=" ">



                                  <div class="btn-group col-md-2 col-md-offset-3">
                                    <button data-toggle="dropdown" class="btn btn-small dropdown-toggle"> <span class="caret"></span></button>
                                    <ul class="dropdown-menu" style="min-width:0px !important;">
                                        <li><a href="<?php echo $this->sitePath."transaction/credit/view/id/".base64_encode($results['id']); ?>">View</a></li>
                                         <?php 
                                            if($logSession->type!=5 && $logSession->proxy_type!=5) {
                                         ?>
                                       <li><a href="javascript:void(0)" class="<?php if($results['credit_status']==1) { echo "disable-indication disabled"; } ?>"  onclick="return editTransaction('<?php echo base64_encode($results['id']); ?>','<?php echo $results['credit_status']; ?>')">Edit</a></li>
                                        <?php 
                                            if($results['credit_status']!=3) {
                                         ?>
                                        <li><a href="javascript:void(0)" onclick="return copyCredit('<?php echo base64_encode($results['id']); ?>')">Copy</a></li>
                                        <?php
                                            }
                                        ?>
                                        <?php
                                            }
                                        ?>
                                        <?php 
                                            if($logSession->type!=5 && $logSession->proxy_type!=5) {
                                         ?>
                                         <?php 
                                            if($results['credit_status']!=3) {
                                         ?>
                                         <!-- <li><a href="" class="widget-remove" onclick="return markSent('<?php echo base64_encode($results['id']); ?>')">Mark as sent</a></li> -->
                                         <?php
                                            }
                                        ?>
                                        <li><a href="" class="widget-remove" onclick="return deleteCredit('<?php echo base64_encode($results['id']); ?>')">Delete</a></li>
                                        <?php
                                            }
                                        ?>
                                    </ul>
                                    </div>


                                    <div class="col-md-2" style="margin-left:10px;">
                                        <?php 
                                          if(($logSession->proxy_type==2 || $logSession->type==2)) {
                                              $authorised = 1;
                                          } else if (($logSession->type==3 && $logSession->id==$results['approval_for']) || ($logSession->proxy_type==3 && $logSession->proxy_id==$results['approval_for'])) {
                                             $authorised = 1;
                                          }  else {
                                             $authorised = 2;
                                          }
                                          if($results['credit_status']==1) {
                                        ?>
                                          <a class="btn btn-mini btn-success" href="javascript:void(0)" data-original-title="Unverify"  onclick="changeTransactionStatus('<?php echo base64_encode($results['id']); ?>',2,'<?php echo $authorised; ?>')"><i class="icon-ok"></i></a>
                                        <?php 
                                          } else if($results['credit_status']==2) {
                                        ?>
                                          <a class="btn btn-mini btn-default" href="javascript:void(0)" data-original-title="Verify"  onclick="changeTransactionStatus('<?php echo base64_encode($results['id']); ?>',1,'<?php echo $authorised; ?>')"><i class="icon-ok"></i></a>
                                        <?php 
                                          } 
                                           if($results['credit_status']==3) {
                                        ?>
                                         <a class="btn btn-mini btn-default" href="javascript:void(0)" data-original-title="Draft"><i class="icon-envelope"></i></a>
                                        <?php 
                                          }
                                        ?>
                                        </div>
                                                             
                                        </td>
                                        </tr>
                                    <?php 
                                        }
                                    ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
<script type="text/javascript">

function changeTransactionStatus(Idvalue,status,auth) {
  var location = $('#locations').val();
  var finance  = $('#financial_year').val();
  if(auth==1) {
    window.location.href='<?php echo $this->sitePath; ?>transaction/credit/index/verifyid/'+Idvalue+'/status/'+status+'/?location='+location+'&financial_year='+finance;
    } else if(auth==2) {
        if(status==1) {
          alert('You are not authorized to verify this transaction');
        } else if(status==2) {
          alert('You are not authorized to unverify this transaction');
        }
    }
}

function copyCredit(Idvalue) {
  var confirmMsg = confirm("Are you sure want to copy this credit note? ");
    if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>transaction/credit/copy/id/'+Idvalue;
    }
}
 
function markSent(Idvalue) {
  var confirmMsg = confirm("Are you sure want to mark this credit note as sent?");
    if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>transaction/credit/index/sentid/'+Idvalue;
    }
}

function deleteCredit(Idvalue) {
  var location = $('#locations').val();
  var finance  = $('#financial_year').val();
  var confirmMsg = confirm("Are you sure want to delete this credit note? You cannot undo this action");
    if(confirmMsg) {
            window.location.href='<?php echo $this->sitePath; ?>transaction/credit/index/delid/'+Idvalue+'/?location='+location+'&financial_year='+finance;
    }
}

function editTransaction(Idvalue,status,type) {
  if(type==5) {
    window.location.href='<?php echo $this->sitePath; ?>transaction/credit/view/id/'+Idvalue;
   // alert("Cannot edit this credit note because transaction is verified");
  } else if(status==1) {
    window.location.href='<?php echo $this->sitePath; ?>transaction/credit/view/id/'+Idvalue;
   // alert("Cannot edit this credit note because transaction is verified");
  } else {
        window.location.href='<?php echo $this->sitePath; ?>transaction/credit/edit/id/'+Idvalue;
    }
}
$(document).ready(function(){
   $('#show_filter').click(function () {
       $('#hide_filter').css('display','inline-block');
       $('#filters_id').css('display','block');
       $('#show_filter').css('display','none');
   }); 
   $('#hide_filter').click(function () {
       $('#show_filter').css('display','inline-block');
        $('#filters_id').css('display','none');
       $('#hide_filter').css('display','none');
   }); 
});
</script>